### ISSUE TITLE
add scroll btn left and right

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#1]
[![Screenshot_2022-06-01_12-19-16.png](https://mrkr.io/s/62975944e9be9840eebc4d35/2)](https://mrkr.io/s/62975944e9be9840eebc4d35/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62975944e9be9840eebc4d3d_bdf53e9fec4ec9c4)

**Console:** [ℹ️  2 info 📃  3 logs ](https://app.marker.io/i/62975944e9be9840eebc4d3d_bdf53e9fec4ec9c4?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1099</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62975944e9be9840eebc4d3d_bdf53e9fec4ec9c4) - This issue was marked as open in Marker.io.

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62975944e9be9840eebc4d3d_bdf53e9fec4ec9c4) - This issue was marked as resolved in Marker.io.
