### ISSUE TITLE
setting filter selection not working for 18k yellow gold

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#10]
[![Screenshot_2022-06-01_12-47-23.png](https://mrkr.io/s/62975fdbe9be9840eebc62f6/2)](https://mrkr.io/s/62975fdbe9be9840eebc62f6/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/settings](https://zcova-uat.com/settings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62975fdbe9be9840eebc62fd_da572f7ae75e0b7e)

**Console:** [ℹ️  2 info 📃  2 logs ](https://app.marker.io/i/62975fdbe9be9840eebc62fd_da572f7ae75e0b7e?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1144</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed
