### ISSUE TITLE
Footer About ZCOVA

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#105]
[![Screenshot_2022-06-22_08-10-57.png](https://mrkr.io/s/62b2ce913cd9f43339d1e384/2)](https://mrkr.io/s/62b2ce913cd9f43339d1e384/0)

- remove virtual appointment temporarily

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b2ce913cd9f43339d1e387_4df2f6c44c992fe1?comments=1)

**Source URL:** [https://zcova-uat.com/appointment](https://zcova-uat.com/appointment)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b2ce913cd9f43339d1e387_4df2f6c44c992fe1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1651 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b2ce913cd9f43339d1e387_4df2f6c44c992fe1) - This issue was marked as resolved in Marker.io.
