### ISSUE TITLE
Footer (Products)

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#106]
[![Screenshot_2022-06-22_08-19-49.png](https://mrkr.io/s/62b2d0a5c0839fbb7787a6fa/2)](https://mrkr.io/s/62b2d0a5c0839fbb7787a6fa/0)

- Change engagement ring link to: https://zcova-uat.com/settings?start=setting

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b2d0a5c0839fbb7787a6fd_735e03415120d8ac?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b2d0a5c0839fbb7787a6fd_735e03415120d8ac)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1651 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b2d0a5c0839fbb7787a6fd_735e03415120d8ac) - This issue was marked as resolved in Marker.io.
