### ISSUE TITLE
Homepage 28mil change

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#107]
[![Screenshot_2022-06-22_08-35-54.png](https://mrkr.io/s/62b2d46a47082cd835519e46/2)](https://mrkr.io/s/62b2d46a47082cd835519e46/0)

-change the highlighted ones.

1. Change to: USD 6.9mil Saved
2. Change to: 7000+ Happy Customers
3. Change to: 700+ Reviews

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b2d46a47082cd835519e49_1bade2f65a73cbd9?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b2d46a47082cd835519e49_1bade2f65a73cbd9)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1651 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b2d46a47082cd835519e49_1bade2f65a73cbd9) - This issue was marked as resolved in Marker.io.
