### ISSUE TITLE
Product Size

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#108]
[![Screenshot_2022-06-23_08-14-37.png](https://mrkr.io/s/62b420edba944a36d7f7c5ba/2)](https://mrkr.io/s/62b420edba944a36d7f7c5ba/0)

- In the backend we removed all the sizes, but it still appears in the front end when I select a metal. Fix this

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b420edba944a36d7f7c5be_663182f2910605e6?comments=1)

**Source URL:** [https://zcova-uat.com/settings/selected-setting/1](https://zcova-uat.com/settings/selected-setting/1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b420edba944a36d7f7c5be_663182f2910605e6)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1756 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b420edba944a36d7f7c5be_663182f2910605e6) - This issue was marked as resolved in Marker.io.
