### ISSUE TITLE
Product metal

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#109]
[![Screenshot_2022-06-23_08-16-55.png](https://mrkr.io/s/62b42177e1e5033aed935917/2)](https://mrkr.io/s/62b42177e1e5033aed935917/0)

When click on the metal icon, the photo and metal button should change, including the price. fix this

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b42177e1e5033aed93591a_46547c8fce088d3c?comments=1)

**Source URL:** [https://zcova-uat.com/settings/selected-setting/1](https://zcova-uat.com/settings/selected-setting/1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b42177e1e5033aed93591a_46547c8fce088d3c)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1756 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b42177e1e5033aed93591a_46547c8fce088d3c) - This issue was marked as resolved in Marker.io.
