### ISSUE TITLE
Bulk upload products

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#110]
[![Screenshot_2022-06-23_09-18-29.png](https://mrkr.io/s/62b42fe5df693ccce7f4dece/2)](https://mrkr.io/s/62b42fe5df693ccce7f4dece/0)

Clean all old products and reupload based on this excel file for Engagement Ring, Wedding Ring, Birthstone, Earrings, Necklace and Bracelet:
https://docs.google.com/spreadsheets/d/1-rm-truG-dTBsekbHR3MzAl7Ol4exRs9ktrb0mb2JDU/edit?usp=sharing

For photos please refer to:
https://drive.google.com/drive/folders/13uGDNKr78qcC8p4l1fO4EMf9aQcGWMvv?usp=sharing

*Please ignore those labelled (TBC)

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b42fe5df693ccce7f4ded1_9b867f9185f92270?comments=1)

**Source URL:** [https://zcova-uat.com/settings?start=setting](https://zcova-uat.com/settings?start=setting)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b42fe5df693ccce7f4ded1_9b867f9185f92270)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1409 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b42fe5df693ccce7f4ded1_9b867f9185f92270) - This issue was marked as resolved in Marker.io.
