### ISSUE TITLE
Wedding ring filter error

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#111]
[![Screenshot_2022-06-23_09-22-48.png](https://mrkr.io/s/62b430e8bd1c8448231e0aed/2)](https://mrkr.io/s/62b430e8bd1c8448231e0aed/0)

Tried to select women + white gold and this error popped up

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b430e8bd1c8448231e0af0_3e499d5ce1ca7fc8?comments=1)

**Source URL:** [https://zcova-uat.com/wedding-rings](https://zcova-uat.com/wedding-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b430e8bd1c8448231e0af0_3e499d5ce1ca7fc8)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1409 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b430e8bd1c8448231e0af0_3e499d5ce1ca7fc8) - This issue was marked as resolved in Marker.io.
