### ISSUE TITLE
Gemstone landing ICL certificate

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#112]
[![Screenshot_2022-06-27_01-40-48.png](https://mrkr.io/s/62b90aa037eef79753543ea3/2)](https://mrkr.io/s/62b90aa037eef79753543ea3/0)

- change the button text to " Find Out More "

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b90aa037eef79753543ea6_c1cddd642ae5facc?comments=1)

**Source URL:** [https://zcova-uat.com/gemstone-landing](https://zcova-uat.com/gemstone-landing)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b90aa037eef79753543ea6_c1cddd642ae5facc)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1762 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b90aa037eef79753543ea6_c1cddd642ae5facc) - This issue was marked as resolved in Marker.io.
