### ISSUE TITLE
Bracelets page remove 'gemstone bracelet'

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#113]
[![Screenshot_2022-06-27_02-41-21.png](https://mrkr.io/s/62b918d1bd1c844823276bbc/2)](https://mrkr.io/s/62b918d1bd1c844823276bbc/0)

remove this for now

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b918d1bd1c844823276bbf_870b5f8cac5631e0?comments=1)

**Source URL:** [https://zcova-uat.com/bracelets?style=Personalised+Name+Bracelet](https://zcova-uat.com/bracelets?style=Personalised+Name+Bracelet)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b918d1bd1c844823276bbf_870b5f8cac5631e0)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1251 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b918d1bd1c844823276bbf_870b5f8cac5631e0) - This issue was marked as resolved in Marker.io.
