### ISSUE TITLE
Bracelets page

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#114]
[![Screenshot_2022-06-27_02-42-41.png](https://mrkr.io/s/62b91921ba944a36d7015bec/2)](https://mrkr.io/s/62b91921ba944a36d7015bec/0)

Should not have women / men here

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b91921ba944a36d7015bef_c276fa5fe63b11d6?comments=1)

**Source URL:** [https://zcova-uat.com/bracelets?style=Personalised+Name+Bracelet](https://zcova-uat.com/bracelets?style=Personalised+Name+Bracelet)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b91921ba944a36d7015bef_c276fa5fe63b11d6)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1501 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b91921ba944a36d7015bef_c276fa5fe63b11d6) - This issue was marked as resolved in Marker.io.
