### ISSUE TITLE
Necklace page remove 'women / men'

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#115]
[![Screenshot_2022-06-27_03-08-44.png](https://mrkr.io/s/62b91f3c3cd9f43339df48c0/2)](https://mrkr.io/s/62b91f3c3cd9f43339df48c0/0)

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b91f3c3cd9f43339df48c3_d86fdaccc2d6e2c8?comments=1)

**Source URL:** [https://zcova-uat.com/necklaces](https://zcova-uat.com/necklaces)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b91f3c3cd9f43339df48c3_d86fdaccc2d6e2c8)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1501 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b91f3c3cd9f43339df48c3_d86fdaccc2d6e2c8) - This issue was marked as resolved in Marker.io.
