### ISSUE TITLE
Birthstone page missing prices

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#116]
[![Screenshot_2022-06-27_03-43-38.png](https://mrkr.io/s/62b9276947082cd8355f0434/2)](https://mrkr.io/s/62b9276947082cd8355f0434/0)

14K prices are missing for these 4 products

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b9276a47082cd8355f0437_088e74bf3c619a37?comments=1)

**Source URL:** [https://zcova-uat.com/birthstones](https://zcova-uat.com/birthstones)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b9276a47082cd8355f0437_088e74bf3c619a37)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2002 x 1300</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b9276a47082cd8355f0437_088e74bf3c619a37) - This issue was marked as resolved in Marker.io.
