### ISSUE TITLE
Cilia earrings

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#117]
[![Screenshot_2022-06-27_04-00-04.png](https://mrkr.io/s/62b92b4447082cd8355f0ae8/2)](https://mrkr.io/s/62b92b4447082cd8355f0ae8/0)

All the cilia earrings in 'earrings' have no images but the front end is showing images. Is the database getting confused because the product name is the same even though URL is different?

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b92b4447082cd8355f0aeb_2372da551d4f6d4e?comments=1)

**Source URL:** [https://zcova-uat.com/admin/jewellery/earring/edit-jewellery/14](https://zcova-uat.com/admin/jewellery/earring/edit-jewellery/14)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b92b4447082cd8355f0aeb_2372da551d4f6d4e)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1584 x 867</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b92b4447082cd8355f0aeb_2372da551d4f6d4e) - **Isabel (isabel@zcova.com)** commented via Marker.io:

> There are also 2 price fields

[Reply here](https://app.marker.io/i/62b92b4447082cd8355f0aeb_2372da551d4f6d4e)

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b92b4447082cd8355f0aeb_2372da551d4f6d4e) - This issue was marked as resolved in Marker.io.
