### ISSUE TITLE
Engagement Ring landing Drop down at the bottom

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#118]
[![Screenshot_2022-06-29_05-40-28.png](https://mrkr.io/s/62bbe5cc83c72308b1b99d72/2)](https://mrkr.io/s/62bbe5cc83c72308b1b99d72/0)

- Change the text

Round Brilliant Diamond
Princess Diamond
Emerald Diamond
Oval Diamond
Marquise Diamond
Radiant Diamond
Pear Diamond
Heart Diamond
Cushion Diamond
Asscher Diamond

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62bbe5cc83c72308b1b99d75_415b33f963a8b3dc?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62bbe5cc83c72308b1b99d75_415b33f963a8b3dc)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.4.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1740 x 913</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62bbe5cc83c72308b1b99d75_415b33f963a8b3dc) - This issue was marked as resolved in Marker.io.
