### ISSUE TITLE
allow to unselect both to show all

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#12]
[![Screenshot_2022-06-01_12-51-39.png](https://mrkr.io/s/629760db18e6a362d1b6e50b/2)](https://mrkr.io/s/629760db18e6a362d1b6e50b/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/wedding-rings](https://zcova-uat.com/wedding-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629760db18e6a362d1b6e512_cce4983b39779585)

**Console:** [ℹ️  2 info 📃  2 logs ](https://app.marker.io/i/629760db18e6a362d1b6e512_cce4983b39779585?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1144</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed
