### ISSUE TITLE
Product Description

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#121]
[![Screenshot_2022-07-01_02-20-56.png](https://mrkr.io/s/62be5a087295a3a829681772/2)](https://mrkr.io/s/62be5a087295a3a829681772/0)

Need much longer length and able to enter next line.

---

**Reported by:** i (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62be5a087295a3a829681775_85f357c2c2a8cf26?comments=1)

**Source URL:** [https://zcova-uat.com/earrings/selected-earring/27](https://zcova-uat.com/earrings/selected-earring/27)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62be5a087295a3a829681775_85f357c2c2a8cf26)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1439 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62be5a087295a3a829681775_85f357c2c2a8cf26) - This issue was marked as resolved in Marker.io.
