### ISSUE TITLE
Dropdown Menu

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#122]
[![Screenshot_2022-07-01_09-29-09.png](https://mrkr.io/s/62bebe651643fb2ce068427a/2)](https://mrkr.io/s/62bebe651643fb2ce068427a/0)

Refer to this file:
https://docs.google.com/spreadsheets/d/1hY6Il9MNbykjeIEFHquxEilmHG9Q0t3VegmboWM1AXw/edit?usp=sharing

'Sitemap' tab
-Change from 'old link' to 'new link'
-Instructions for 'KIV' and 'MISSING' are at the top

'Menu' tab
-change links in dropdown menu
-Instructions for 'KIV' and yellow highlight are at the top

'Footer' tab
-change to these links
-Added in new 'Our Policies' under Policies

---

**Reported by:** i (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62bebe651643fb2ce068427d_d5bd122cf7acc9ee?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62bebe651643fb2ce068427d_d5bd122cf7acc9ee)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1439 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62bebe651643fb2ce068427d_d5bd122cf7acc9ee) - This issue was marked as resolved in Marker.io.
