### ISSUE TITLE
Change website links

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#123]
[![Screenshot_2022-07-05_06-13-13.png](https://mrkr.io/s/62c3d679dc2ef4a677563626/2)](https://mrkr.io/s/62c3d679dc2ef4a677563626/0)

Refer to 'WEBSITE (ALL)' tab:
https://docs.google.com/spreadsheets/d/1hY6Il9MNbykjeIEFHquxEilmHG9Q0t3VegmboWM1AXw/edit?usp=sharing

Ignore those marked 'KIV' in red until after website is live.

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c3d679dc2ef4a677563629_f346ed36a9eb7625?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c3d679dc2ef4a677563629_f346ed36a9eb7625)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1047 x 867</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c3d679dc2ef4a677563629_f346ed36a9eb7625) - This issue was marked as resolved in Marker.io.
