### ISSUE TITLE
Our policies - Change links

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#124]
[![Screenshot_2022-07-05_06-25-43.png](https://mrkr.io/s/62c3d967680df53e372b2640/2)](https://mrkr.io/s/62c3d967680df53e372b2640/0)

1.0 services
a. www.zcova.com/dual-cert
c. www.zcova.com/360-video
e. www.zcova.com/gia-graded-mined-diamond
g. www.zcova.com/refurbish

2.0 policies
b. www.zcova.com/malaysian-payment
f. www.zcova.com/privacy-policy

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c3d967680df53e372b2643_c015bfd1e6455189?comments=1)

**Source URL:** [https://zcova-uat.com/our-policies](https://zcova-uat.com/our-policies)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c3d967680df53e372b2643_c015bfd1e6455189)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1188 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c3d967680df53e372b2643_c015bfd1e6455189) - This issue was marked as resolved in Marker.io.
