### ISSUE TITLE
Gemstone education change link

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#125]
[![Screenshot_2022-07-05_06-27-19.png](https://mrkr.io/s/62c3d9c77295a3a82972af9f/2)](https://mrkr.io/s/62c3d9c77295a3a82972af9f/0)

https://zcova-uat.com/gemstone?start=gemstone

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c3d9c77295a3a82972afa2_8ce2438ea89d4285?comments=1)

**Source URL:** [https://zcova-uat.com/gemstone-education](https://zcova-uat.com/gemstone-education)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c3d9c77295a3a82972afa2_8ce2438ea89d4285)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1188 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c3d9c77295a3a82972afa2_8ce2438ea89d4285) - This issue was marked as resolved in Marker.io.
