### ISSUE TITLE
Sapphire page change link

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#126]
[![Screenshot_2022-07-05_06-28-08.png](https://mrkr.io/s/62c3d9f8f17e4939cfd3cafc/2)](https://mrkr.io/s/62c3d9f8f17e4939cfd3cafc/0)

https://zcova-uat.com/gemstone?start=gemstone

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c3d9f8f17e4939cfd3caff_866123126890234f?comments=1)

**Source URL:** [https://zcova-uat.com/sapphire](https://zcova-uat.com/sapphire)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c3d9f8f17e4939cfd3caff_866123126890234f)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1188 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c3d9f8f17e4939cfd3caff_866123126890234f) - This issue was marked as resolved in Marker.io.
