### ISSUE TITLE
Promise page change link 2

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#128]
[![Screenshot_2022-07-05_06-30-48.png](https://mrkr.io/s/62c3da98447e86beaffe7614/2)](https://mrkr.io/s/62c3da98447e86beaffe7614/0)

www.zcova.com/360-video

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c3da98447e86beaffe7617_416c81018d162894?comments=1)

**Source URL:** [https://zcova-uat.com/customer-care](https://zcova-uat.com/customer-care)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c3da98447e86beaffe7617_416c81018d162894)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1188 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c3da98447e86beaffe7617_416c81018d162894) - This issue was marked as resolved in Marker.io.
