### ISSUE TITLE
Update billing address

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#130]
[![Screenshot_2022-07-08_04-10-45.png](https://mrkr.io/s/62c7ae457295a3a8297e2e03/2)](https://mrkr.io/s/62c7ae457295a3a8297e2e03/0)

- Address 2 SHOULD NOT be required. Change this

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7ae457295a3a8297e2e06_f9e685316e80a84a?comments=1)

**Source URL:** [https://zcova-uat.com/user/my-details](https://zcova-uat.com/user/my-details)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7ae457295a3a8297e2e06_f9e685316e80a84a)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.4.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1745 x 959</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7ae457295a3a8297e2e06_f9e685316e80a84a) - This issue was marked as resolved in Marker.io.
