### ISSUE TITLE
Cart check out Contact

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#131]
[![Screenshot_2022-07-08_04-12-27.png](https://mrkr.io/s/62c7aeabe806e5a94a4295f3/2)](https://mrkr.io/s/62c7aeabe806e5a94a4295f3/0)

- Change ZCOVA contact to +603 6156 1888

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7aeabe806e5a94a4295f6_e6577d1739017bfd?comments=1)

**Source URL:** [https://zcova-uat.com/checkout](https://zcova-uat.com/checkout)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7aeabe806e5a94a4295f6_e6577d1739017bfd)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.4.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1745 x 959</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7aeabe806e5a94a4295f6_e6577d1739017bfd) - This issue was marked as resolved in Marker.io.
