### ISSUE TITLE
Bracelet product page

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#132]
[![Screenshot_2022-07-08_05-31-27.png](https://mrkr.io/s/62c7c12f447e86beaf0a0e5e/2)](https://mrkr.io/s/62c7c12f447e86beaf0a0e5e/0)

Description, and other columns for bracelet like diamond ctw and diamond range are missing

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada?comments=1)

**Source URL:** [https://zcova-uat.com/bracelets/selected-bracelet/1](https://zcova-uat.com/bracelets/selected-bracelet/1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1246 x 722</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada) - **Isabel (isabel@zcova.com)** commented via Marker.io:

> The missing columns happening for other product categories as well. They're all showing Width only.

[Reply here](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada)

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
This issue is not fixed.

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada) - This issue was marked as resolved in Marker.io.

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
https://zcova-uat.com/bracelets/selected-bracelet/1
Empty fields should be hidden as requested. This differs based on the product. If the product does not have diamonds, then the diamond CTW should be hidden.

**Comment by isabelzcova** [comment]
https://zcova-uat.com/bracelets/selected-bracelet/2
Empty fields should be hidden. For this product, the field for 'Word' is missing. As stated in the bulk upload Excel, make Hidden if No, provide a field for Short decription if Yes

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada) - This issue was marked as resolved in Marker.io.

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
https://zcova-uat.com/bracelets/selected-bracelet/2
<img width="959" alt="arabic" src="https://user-images.githubusercontent.com/108924987/180117603-e393b549-765d-45a8-b498-00720eef711a.png">
I saw the text box for Short description earlier but the product Description was missing. I added in the product description but now the text box is missing.

Short description: << Can you change this to 'Word'

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada) - This issue was marked as resolved in Marker.io.

**Comment by isabelzcova** [comment]
Change this 'short description' to 'word' in cart and anywhere else it is appearing as well
<img width="621" alt="bracelet" src="https://user-images.githubusercontent.com/108924987/180342848-c8beabe3-8353-411f-9c44-5da0361cf6c8.png">

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada) - This issue was marked as open in Marker.io.

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c12f447e86beaf0a0e61_f196913baaf7fada) - This issue was marked as resolved in Marker.io.
