### ISSUE TITLE
Check out Diamond details

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#133]
[![Screenshot_2022-07-08_05-45-58.png](https://mrkr.io/s/62c7c496f17e4939cfdf7214/2)](https://mrkr.io/s/62c7c496f17e4939cfdf7214/0)

- Colour missing, please check the issue here

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7c496f17e4939cfdf7217_8a9f93bdd0961cd9?comments=1)

**Source URL:** [https://zcova-uat.com/cart](https://zcova-uat.com/cart)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7c496f17e4939cfdf7217_8a9f93bdd0961cd9)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.4.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1745 x 959</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c496f17e4939cfdf7217_8a9f93bdd0961cd9) - This issue was marked as resolved in Marker.io.
