### ISSUE TITLE
Sign up checkbox

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#134]
[![Screenshot_2022-07-08_06-05-03.png](https://mrkr.io/s/62c7c90ff17e4939cfdf7a68/2)](https://mrkr.io/s/62c7c90ff17e4939cfdf7a68/0)

It is unclear that this is actually a checkbox and needs to be ticked.. Privacy policy and T&C should be linked tot he pages

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7c90ff17e4939cfdf7a6b_b2c4bedb7f3aedbe?comments=1)

**Source URL:** [https://zcova-uat.com/earrings/selected-earring/1](https://zcova-uat.com/earrings/selected-earring/1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7c90ff17e4939cfdf7a6b_b2c4bedb7f3aedbe)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1246 x 722</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c90ff17e4939cfdf7a6b_b2c4bedb7f3aedbe) - This issue was marked as resolved in Marker.io.
