### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#135]
[![Screenshot_2022-07-08_06-06-43.png](https://mrkr.io/s/62c7c973f940e0011c555afd/2)](https://mrkr.io/s/62c7c973f940e0011c555afd/0)

If I click on 'register' without checking the checkbox, this pops up but the blue box on top of 'Please read the privacy.....' should not look like that

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7c973f940e0011c555b00_34b338cc6d7a1c4c?comments=1)

**Source URL:** [https://zcova-uat.com/earrings/selected-earring/1](https://zcova-uat.com/earrings/selected-earring/1)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7c973f940e0011c555b00_34b338cc6d7a1c4c)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1246 x 722</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c973f940e0011c555b00_34b338cc6d7a1c4c) - **Isabel (isabel@zcova.com)** commented via Marker.io:

> Tried to click on the blue box because it has an 'x' and nothing happens

[Reply here](https://app.marker.io/i/62c7c973f940e0011c555b00_34b338cc6d7a1c4c)

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c973f940e0011c555b00_34b338cc6d7a1c4c) - **Isabel (isabel@zcova.com)** commented via Marker.io:

> Upon successful signup, pop up message "You will be redirected to your account page in 3 seconds"
> 
> but sends me to homepage instead

[Reply here](https://app.marker.io/i/62c7c973f940e0011c555b00_34b338cc6d7a1c4c)

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c973f940e0011c555b00_34b338cc6d7a1c4c) - **Isabel (isabel@zcova.com)** commented via Marker.io:

> Upon successful signup, user would assume that they are already logged in but they're not. You need to login with your details again

[Reply here](https://app.marker.io/i/62c7c973f940e0011c555b00_34b338cc6d7a1c4c)

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7c973f940e0011c555b00_34b338cc6d7a1c4c) - This issue was marked as resolved in Marker.io.
