### ISSUE TITLE
Profile hide Refer a friend

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#136]
[![Screenshot_2022-07-08_06-13-13.png](https://mrkr.io/s/62c7caf9eaf0f4eddf1a8fa4/2)](https://mrkr.io/s/62c7caf9eaf0f4eddf1a8fa4/0)

Hide this feature for now

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7caf9eaf0f4eddf1a8fa7_43b0f46c4c19f540?comments=1)

**Source URL:** [https://zcova-uat.com/user/my-account](https://zcova-uat.com/user/my-account)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7caf9eaf0f4eddf1a8fa7_43b0f46c4c19f540)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1246 x 722</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7caf9eaf0f4eddf1a8fa7_43b0f46c4c19f540) - This issue was marked as resolved in Marker.io.
