### ISSUE TITLE
Profile my details

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#138]
[![Screenshot_2022-07-08_06-31-31.png](https://mrkr.io/s/62c7cf43f17e4939cfdf88d7/2)](https://mrkr.io/s/62c7cf43f17e4939cfdf88d7/0)

Red: not indicated that this is contact number

Yellow: This is for Billing Address only. Add in one more section for Shipping Address.

Green: Only Malaysian states available here. If you're not going to change the states based on country, remove this dropdown and change to text box.

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7cf43f17e4939cfdf88da_90d13fbb77146249?comments=1)

**Source URL:** [https://zcova-uat.com/user/my-details](https://zcova-uat.com/user/my-details)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7cf43f17e4939cfdf88da_90d13fbb77146249)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7cf43f17e4939cfdf88da_90d13fbb77146249) - This issue was marked as resolved in Marker.io.
