### ISSUE TITLE
-

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#139]
[![Screenshot_2022-07-08_06-34-45.png](https://mrkr.io/s/62c7d005eaf0f4eddf1a9bcf/2)](https://mrkr.io/s/62c7d005eaf0f4eddf1a9bcf/0)

The four coloumn , My Details , My orders , Wishlist and refer a friend , does not click to anything 

---

**Reported by:** ziyin (ziyin@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7d005eaf0f4eddf1a9bd2_5ed36234c2a7ab44?comments=1)

**Source URL:** [https://zcova-uat.com/user/my-account](https://zcova-uat.com/user/my-account)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7d005eaf0f4eddf1a9bd2_5ed36234c2a7ab44)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1729 x 887</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7d005eaf0f4eddf1a9bd2_5ed36234c2a7ab44) - This issue was marked as resolved in Marker.io.
