### ISSUE TITLE
default price showing

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#14]
[![Screenshot_2022-06-01_13-06-06.png](https://mrkr.io/s/6297643e51889e546ae79c5a/2)](https://mrkr.io/s/6297643e51889e546ae79c5a/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/settings/selected-setting/2](https://zcova-uat.com/settings/selected-setting/2)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6297643e51889e546ae79c62_88a08bf5dcc6c384)

**Console:** [ℹ️  2 info 📃  3 logs ](https://app.marker.io/i/6297643e51889e546ae79c62_88a08bf5dcc6c384?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1144</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6297643e51889e546ae79c62_88a08bf5dcc6c384) - This issue was marked as resolved in Marker.io.
