### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#140]
[![Screenshot_2022-07-08_07-13-07.png](https://mrkr.io/s/62c7d903447e86beaf0a43da/2)](https://mrkr.io/s/62c7d903447e86beaf0a43da/0)

Tried clicking on the green parts then it gave an error page. When I pressed 'back', my order details are gone (red). and the diamond details have become gemstone (purple)

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7d903447e86beaf0a43dd_686f0c888009f44a?comments=1)

**Source URL:** [https://zcova-uat.com/complete-ring](https://zcova-uat.com/complete-ring)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7d903447e86beaf0a43dd_686f0c888009f44a)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1459 x 867</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by logicwise** [comment]
Unable to reproduce the bug. Can you try again and confirm its still there

**Comment by logicwisesoftware** [comment]
Just tested today again, unable to reproduce the bug. if this sill an issue can re-open this ticket.
