### ISSUE TITLE
Step 1 2 3

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#141]
[![Screenshot_2022-07-08_07-17-23.png](https://mrkr.io/s/62c7da031643fb2ce07dc784/2)](https://mrkr.io/s/62c7da031643fb2ce07dc784/0)

The whole box should be clickable to return to that step. Right now can only click on 'Diamond'. Maybe add in 'change' beside 'Remove' too.

Remove the ribbon in red box

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7da031643fb2ce07dc787_7715a2efbb7679ab?comments=1)

**Source URL:** [https://zcova-uat.com/complete-ring?start=diamond&start=diamond](https://zcova-uat.com/complete-ring?start=diamond&start=diamond)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7da031643fb2ce07dc787_7715a2efbb7679ab)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1459 x 867</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7da031643fb2ce07dc787_7715a2efbb7679ab) - This issue was marked as resolved in Marker.io.
