### ISSUE TITLE
Start with a gemstone

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#143]
[![Screenshot_2022-07-08_07-33-57.png](https://mrkr.io/s/62c7dde51f50aae86f8d35b3/2)](https://mrkr.io/s/62c7dde51f50aae86f8d35b3/0)

Got here by clicking on 'start with a gemstone' in menu. Swap the 1 and 2

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7dde51f50aae86f8d35b6_52e97084ddb7a4ee?comments=1)

**Source URL:** [https://zcova-uat.com/gemstones?start=gemstone](https://zcova-uat.com/gemstones?start=gemstone)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7dde51f50aae86f8d35b6_52e97084ddb7a4ee)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1459 x 867</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7dde51f50aae86f8d35b6_52e97084ddb7a4ee) - This issue was marked as resolved in Marker.io.
