### ISSUE TITLE
Step 1 2 3 gemstone

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#144]
[![Screenshot_2022-07-08_07-36-24.png](https://mrkr.io/s/62c7de781643fb2ce07dd348/2)](https://mrkr.io/s/62c7de781643fb2ce07dd348/0)

How to replicate this problem: Select a gemstone. Remove the gemstone from step 1. Select 'start with a setting' in menu.

Problem: unable to select diamond in step 1 now despite pressing refresh.

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7de781643fb2ce07dd34b_a540ebe3d3191e20?comments=1)

**Source URL:** [https://zcova-uat.com/gemstones?start=gemstone](https://zcova-uat.com/gemstones?start=gemstone)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7de781643fb2ce07dd34b_a540ebe3d3191e20)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1459 x 867</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7de781643fb2ce07dd34b_a540ebe3d3191e20) - This issue was marked as resolved in Marker.io.
