### ISSUE TITLE
Fluorescence

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#145]
[![Screenshot_2022-07-08_07-39-37.png](https://mrkr.io/s/62c7df39680df53e37370fb3/2)](https://mrkr.io/s/62c7df39680df53e37370fb3/0)

Fluorescence or fluor, not flour

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7df39680df53e37370fb6_5858b47440b4a51f?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds?start=diamond](https://zcova-uat.com/diamonds?start=diamond)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7df39680df53e37370fb6_5858b47440b4a51f)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1459 x 867</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7df39680df53e37370fb6_5858b47440b4a51f) - This issue was marked as resolved in Marker.io.
