### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#146]
![complete ring](https://user-images.githubusercontent.com/108924987/177948531-343100cd-ca27-4577-86ee-66bfef127ec4.jpg)

put the ring details together, diamond details together. 1 'change' button for each. add in total price with add to cart below

**Comment by salimi-my** [comment]
Fixed

**Comment by isabelzcova** [comment]
Not done

**Comment by salimi-my** [comment]
Fixed
