### ISSUE TITLE
Gemstone treatment

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#147]
[![Screenshot_2022-07-08_08-25-42.png](https://mrkr.io/s/62c7ea060f746e3dcbc2dfa1/2)](https://mrkr.io/s/62c7ea060f746e3dcbc2dfa1/0)

filter for Untreated / Treated not working

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62c7ea060f746e3dcbc2dfa4_e9eaa2a462085aa9?comments=1)

**Source URL:** [https://zcova-uat.com/gemstones?start=gemstone](https://zcova-uat.com/gemstones?start=gemstone)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62c7ea060f746e3dcbc2dfa4_e9eaa2a462085aa9)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1367 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62c7ea060f746e3dcbc2dfa4_e9eaa2a462085aa9) - This issue was marked as resolved in Marker.io.
