### ISSUE TITLE
Diamonds - no lumos

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#149]
[![Screenshot_2022-07-12_02-26-25.png](https://mrkr.io/s/62ccdbd1f940e0011c5f6466/2)](https://mrkr.io/s/62ccdbd1f940e0011c5f6466/0)

How to recreate the problem: Press any shape that is not round, then press 'lumos by ZCOVA'. Filter will change to round but there are no diamonds

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ccdbd1f940e0011c5f6469_11138ca9ddf1adfe?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds?start=diamond](https://zcova-uat.com/diamonds?start=diamond)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ccdbd1f940e0011c5f6469_11138ca9ddf1adfe)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ccdbd1f940e0011c5f6469_11138ca9ddf1adfe) - This issue was marked as resolved in Marker.io.
