### ISSUE TITLE
Diamonds - unable to clear shape filter

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#151]
[![Screenshot_2022-07-12_02-34-55.png](https://mrkr.io/s/62ccddcf447e86beaf142c71/2)](https://mrkr.io/s/62ccddcf447e86beaf142c71/0)

After selecting a shape, I'm unable to view all shapes

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ccddcf447e86beaf142c74_1e192513ff18ec12?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds](https://zcova-uat.com/diamonds)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ccddcf447e86beaf142c74_1e192513ff18ec12)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ccddcf447e86beaf142c74_1e192513ff18ec12) - This issue was marked as resolved in Marker.io.
