### ISSUE TITLE
Diamonds - from lumos to all

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#152]
[![Screenshot_2022-07-13_02-42-05.png](https://mrkr.io/s/62ce30fd0f746e3dcbd0d8dd/2)](https://mrkr.io/s/62ce30fd0f746e3dcbd0d8dd/0)

To recreate: Click on LUMOS, unselect round then it will unselect LUMOS and revert to 'All Diamonds'. However, the diamond listing is not showing all diamonds

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce30fd0f746e3dcbd0d8e0_8faa2fa01a76f6ca?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds?start=diamond](https://zcova-uat.com/diamonds?start=diamond)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce30fd0f746e3dcbd0d8e0_8faa2fa01a76f6ca)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1053 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce30fd0f746e3dcbd0d8e0_8faa2fa01a76f6ca) - This issue was marked as resolved in Marker.io.
