### ISSUE TITLE
Checkout - promo code

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#153]
[![Screenshot_2022-07-13_02-47-52.png](https://mrkr.io/s/62ce3258680df53e374520ab/2)](https://mrkr.io/s/62ce3258680df53e374520ab/0)

-Missing error message when keying in invalid promo code.

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce3258680df53e374520ae_b8cabdde25021915?comments=1)

**Source URL:** [https://zcova-uat.com/cart](https://zcova-uat.com/cart)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce3258680df53e374520ae_b8cabdde25021915)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce3258680df53e374520ae_b8cabdde25021915) - This issue was marked as resolved in Marker.io.
