### ISSUE TITLE
Order details - change number

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#154]
[![Screenshot_2022-07-13_02-57-18.png](https://mrkr.io/s/62ce348e1643fb2ce08be8ea/2)](https://mrkr.io/s/62ce348e1643fb2ce08be8ea/0)

+603 6156 1888

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce348e1643fb2ce08be8ee_7f8ab9c6bfb301bf?comments=1)

**Source URL:** [https://zcova-uat.com/user/order-details/10005](https://zcova-uat.com/user/order-details/10005)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce348e1643fb2ce08be8ee_7f8ab9c6bfb301bf)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce348e1643fb2ce08be8ee_7f8ab9c6bfb301bf) - This issue was marked as resolved in Marker.io.
