### ISSUE TITLE
Backend order - wrong currency

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#155]
[![Screenshot_2022-07-13_03-19-22.png](https://mrkr.io/s/62ce39bae806e5a94a511784/2)](https://mrkr.io/s/62ce39bae806e5a94a511784/0)

I made this order in USD but it's in RM here

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce39bae806e5a94a511787_6b53987908e171c8?comments=1)

**Source URL:** [https://zcova-uat.com/admin/order/listing-pending](https://zcova-uat.com/admin/order/listing-pending)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce39bae806e5a94a511787_6b53987908e171c8)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280 x 643</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce39bae806e5a94a511787_6b53987908e171c8) - This issue was marked as resolved in Marker.io.
