### ISSUE TITLE
Order - missing items

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#156]
[![Screenshot_2022-07-13_03-23-32.png](https://mrkr.io/s/62ce3ab40f746e3dcbd0ec28/2)](https://mrkr.io/s/62ce3ab40f746e3dcbd0ec28/0)

I checked out 3 items but only 2 are appearing. ORDER ID: 39120010005

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce3ab40f746e3dcbd0ec2b_91b9fab5e7580493?comments=1)

**Source URL:** [https://zcova-uat.com/user/order-details/10005](https://zcova-uat.com/user/order-details/10005)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce3ab40f746e3dcbd0ec2b_91b9fab5e7580493)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce3ab40f746e3dcbd0ec2b_91b9fab5e7580493) - This issue was marked as resolved in Marker.io.
