### ISSUE TITLE
Chekcout - billing details

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#158]
[![Screenshot_2022-07-13_03-27-46.png](https://mrkr.io/s/62ce3bb2308d0ed3685dfa13/2)](https://mrkr.io/s/62ce3bb2308d0ed3685dfa13/0)

Country should be required. If only Malaysian States are available, change to text box

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce3bb2308d0ed3685dfa16_7187102ecf7821d1?comments=1)

**Source URL:** [https://zcova-uat.com/checkout](https://zcova-uat.com/checkout)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce3bb2308d0ed3685dfa16_7187102ecf7821d1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1600 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce3bb2308d0ed3685dfa16_7187102ecf7821d1) - This issue was marked as resolved in Marker.io.
