### ISSUE TITLE
Backend order - missing product & engraving

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#159]
[![Screenshot_2022-07-13_03-31-39.png](https://mrkr.io/s/62ce3c9b0f746e3dcbd0f051/2)](https://mrkr.io/s/62ce3c9b0f746e3dcbd0f051/0)

ORDER ID: 2200010006
1st product was a wedding ring but it's not registered on customer side. Still appears in backend but price is 0.

For the Tulip Twisted ring, my engraving message has disappeared.

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce3c9b0f746e3dcbd0f054_0055184c68123ac5?comments=1)

**Source URL:** [https://zcova-uat.com/user/order-details/10006](https://zcova-uat.com/user/order-details/10006)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce3c9b0f746e3dcbd0f054_0055184c68123ac5)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1600 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce3c9b0f746e3dcbd0f054_0055184c68123ac5) - This issue was marked as resolved in Marker.io.

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce3c9b0f746e3dcbd0f054_0055184c68123ac5) - This issue was marked as open in Marker.io.

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce3c9b0f746e3dcbd0f054_0055184c68123ac5) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
ORDER ID: 2200010001
the 'wedding ring' missing name and photo.
<img width="768" alt="1" src="https://user-images.githubusercontent.com/108924987/179163861-718c4194-3e97-47a6-9284-180701aed66e.png">

**Comment by salimi-my** [comment]
Fixed
