### ISSUE TITLE
Backend orders - contact missing

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#160]
[![Screenshot_2022-07-13_03-34-48.png](https://mrkr.io/s/62ce3d58f940e0011c63c4b2/2)](https://mrkr.io/s/62ce3d58f940e0011c63c4b2/0)

Already keyed in number but it's not recorded here

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce3d58f940e0011c63c4b5_b031fabfd08c7ae6?comments=1)

**Source URL:** [https://zcova-uat.com/admin/order/listing-pending](https://zcova-uat.com/admin/order/listing-pending)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce3d58f940e0011c63c4b5_b031fabfd08c7ae6)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1600 x 804</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce3d58f940e0011c63c4b5_b031fabfd08c7ae6) - This issue was marked as resolved in Marker.io.
