### ISSUE TITLE
Backend order - Custom not appearing

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#162]
[![Screenshot_2022-07-13_04-29-28.png](https://mrkr.io/s/62ce4a280f746e3dcbd10add/2)](https://mrkr.io/s/62ce4a280f746e3dcbd10add/0)

Added a custom item into this order via backend but the custom item is not appearing in customer front end Order

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce4a280f746e3dcbd10ae0_6094fea6bd9632ea?comments=1)

**Source URL:** [https://zcova-uat.com/admin/order/edit-order/10006](https://zcova-uat.com/admin/order/edit-order/10006)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce4a280f746e3dcbd10ae0_6094fea6bd9632ea)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1600 x 804</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by isabelzcova** [comment]
order number 39120010006

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce4a280f746e3dcbd10ae0_6094fea6bd9632ea) - This issue was marked as resolved in Marker.io.

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce4a280f746e3dcbd10ae0_6094fea6bd9632ea) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
Still unable to view custom item in order

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce4a280f746e3dcbd10ae0_6094fea6bd9632ea) - This issue was marked as resolved in Marker.io.
