### ISSUE TITLE
Backend order - order number missing?

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#163]
[![Screenshot_2022-07-13_04-30-53.png](https://mrkr.io/s/62ce4a7deaf0f4eddf290ea9/2)](https://mrkr.io/s/62ce4a7deaf0f4eddf290ea9/0)

This is order number 39120010006

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce4a7deaf0f4eddf290eac_fa1f6383dc999203?comments=1)

**Source URL:** [https://zcova-uat.com/admin/order/edit-order/10006](https://zcova-uat.com/admin/order/edit-order/10006)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce4a7deaf0f4eddf290eac_fa1f6383dc999203)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1600 x 804</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce4a7deaf0f4eddf290eac_fa1f6383dc999203) - This issue was marked as resolved in Marker.io.
