### ISSUE TITLE
Backend order - Order Status

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#164]
[![Screenshot_2022-07-13_04-32-52.png](https://mrkr.io/s/62ce4af4447e86beaf189fda/2)](https://mrkr.io/s/62ce4af4447e86beaf189fda/0)

Changed order status to 'production'. Not reflecting in front end customer side. Also missing 'Diamond Secured' step

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce4af4447e86beaf189fdd_19092c1263474ea3?comments=1)

**Source URL:** [https://zcova-uat.com/admin/order/edit-order/10006](https://zcova-uat.com/admin/order/edit-order/10006)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce4af4447e86beaf189fdd_19092c1263474ea3)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1600 x 804</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce4af4447e86beaf189fdd_19092c1263474ea3) - This issue was marked as resolved in Marker.io.

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce4af4447e86beaf189fdd_19092c1263474ea3) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
Unable to set order status to 'Diamond Secured' in backend as salesperson

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce4af4447e86beaf189fdd_19092c1263474ea3) - This issue was marked as resolved in Marker.io.
