### ISSUE TITLE
Order - custom items not appearing

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#165]
[![Screenshot_2022-07-13_06-23-49.png](https://mrkr.io/s/62ce64f5dc2ef4a67770a0ec/2)](https://mrkr.io/s/62ce64f5dc2ef4a67770a0ec/0)

ORDER ID: 39120010007
Custom order made entirely from backend. No items appearing in front end.

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce64f5dc2ef4a67770a0ef_934516e953f75b7c?comments=1)

**Source URL:** [https://zcova-uat.com/user/order-details/10007](https://zcova-uat.com/user/order-details/10007)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce64f5dc2ef4a67770a0ef_934516e953f75b7c)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce64f5dc2ef4a67770a0ef_934516e953f75b7c) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
Only 1 custom item appearing now but there are 2 in backend

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce64f5dc2ef4a67770a0ef_934516e953f75b7c) - This issue was marked as resolved in Marker.io.
