### ISSUE TITLE
Checkout - showroom address

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#166]
[![Screenshot_2022-07-13_06-41-27.png](https://mrkr.io/s/62ce69171643fb2ce08c5df0/2)](https://mrkr.io/s/62ce69171643fb2ce08c5df0/0)

F-02-02, Block F, Komersial SouthKey Mosaic, Persiaran Southkey 1, Kota Southkey 80150, Johor

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce69171643fb2ce08c5df3_40df4b1b24c396bd?comments=1)

**Source URL:** [https://zcova-uat.com/checkout](https://zcova-uat.com/checkout)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce69171643fb2ce08c5df3_40df4b1b24c396bd)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1239 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce69171643fb2ce08c5df3_40df4b1b24c396bd) - This issue was marked as resolved in Marker.io.
