### ISSUE TITLE
Homepage banner

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#167]
[![Screenshot_2022-07-13_06-49-37.png](https://mrkr.io/s/62ce6b011f50aae86f9bcce4/2)](https://mrkr.io/s/62ce6b011f50aae86f9bcce4/0)

- add one more banner photo in front
- add the text

Desktop Image: https://drive.google.com/open?id=1zvV8kSPbJ8wpHNBp_Sa8UrywsYb7NZHJ&authuser=eewern%40zcova.com&usp=drive_fs

Mobile Image: https://drive.google.com/open?id=1zuJvoiPdFssV5Y3BHccwD5yCPASe_DNT&authuser=eewern%40zcova.com&usp=drive_fs

Title: Confidence In Every Sparkle
Body: Pre-launch of Ch'ya by ZCOVA lab-grown diamonds
Button: Find Out More (link to: https://blog.zcova.com/2022/06/01/chya-lab-diamond/)

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62ce6b011f50aae86f9bcce7_a552c5f63ff7ef7f?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62ce6b011f50aae86f9bcce7_a552c5f63ff7ef7f)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.4.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1703 x 959</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixec

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce6b011f50aae86f9bcce7_a552c5f63ff7ef7f) - This issue was marked as resolved in Marker.io.

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce6b011f50aae86f9bcce7_a552c5f63ff7ef7f) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
Please move to first image

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62ce6b011f50aae86f9bcce7_a552c5f63ff7ef7f) - This issue was marked as resolved in Marker.io.
