### ISSUE TITLE
Profile my details - address

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#168]
[![Screenshot_2022-07-15_06-11-33.png](https://mrkr.io/s/62d10515f17e4939cff3c31a/2)](https://mrkr.io/s/62d10515f17e4939cff3c31a/0)

If you submit the form but missed out a field, everything you entered in the form will disappear and customers have to fill in again. It is possible to retain the info?

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d10515f17e4939cff3c31d_0ba80feba934f219?comments=1)

**Source URL:** [https://zcova-uat.com/user/my-details](https://zcova-uat.com/user/my-details)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d10515f17e4939cff3c31d_0ba80feba934f219)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1305 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by isabelzcova** [comment]
Address not getting saved when I press 'update my address'

**Comment by isabelzcova** [comment]
Contact number in first box not getting updated too.

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d10515f17e4939cff3c31d_0ba80feba934f219) - This issue was marked as resolved in Marker.io.
