### ISSUE TITLE
Lab Grown Diamonds - filter

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#169]
[![Screenshot_2022-07-15_07-55-49.png](https://mrkr.io/s/62d11d851643fb2ce0920294/2)](https://mrkr.io/s/62d11d851643fb2ce0920294/0)

shape, cut, polish, symmetry filter not working

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d11d851643fb2ce0920297_3df329b57ea218ea?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds?start=diamond&lab=yes](https://zcova-uat.com/diamonds?start=diamond&lab=yes)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d11d851643fb2ce0920297_3df329b57ea218ea)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2088 x 1300</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed
