### ISSUE TITLE
Lab grown diamond - wrong price

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#170]
[![Screenshot_2022-07-15_08-00-07.png](https://mrkr.io/s/62d11e87dc2ef4a677765180/2)](https://mrkr.io/s/62d11e87dc2ef4a677765180/0)

To recreate problem: Add Lab diamond to cart. Go to cart. Click on the diamond info (as per screenshot)

Correct price: RM 1,215
Displayed price: RM 631.80

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d11e87dc2ef4a677765183_87a42324e93ada57?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds/selected-diamond/533200032?cartID=11&cartType=single](https://zcova-uat.com/diamonds/selected-diamond/533200032?cartID=11&cartType=single)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d11e87dc2ef4a677765183_87a42324e93ada57)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1566 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d11e87dc2ef4a677765183_87a42324e93ada57) - This issue was marked as resolved in Marker.io.
