### ISSUE TITLE
Lab grown - wrong shape description

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#171]
[![Screenshot_2022-07-15_08-03-14.png](https://mrkr.io/s/62d11f42447e86beaf1e8649/2)](https://mrkr.io/s/62d11f42447e86beaf1e8649/0)

These are not round shapes

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d11f42447e86beaf1e864c_b118cfd2a328ae0f?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds?lab=yes](https://zcova-uat.com/diamonds?lab=yes)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d11f42447e86beaf1e864c_b118cfd2a328ae0f)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2088 x 1300</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by affendyiskandar** [comment]
it turns out, the data and image from supplier is given as such. need to ask the supplier (Parallel LGD) to correct this

**Comment by logicwisesoftware** [comment]
Seems ok now

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d11f42447e86beaf1e864c_b118cfd2a328ae0f) - This issue was marked as resolved in Marker.io.
