### ISSUE TITLE
cart - price reverting to 14K

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#172]
[![Screenshot_2022-07-15_09-24-05.png](https://mrkr.io/s/62d13235447e86beaf1ea78a/2)](https://mrkr.io/s/62d13235447e86beaf1ea78a/0)

Reference: 14K is RM 2999, 18K is RM 3699

To recreate problem: Add any gold jewellery (earring, necklace, ring - NOT diamond) to cart by selecting 18K. Click on the Earring in cart. Notice earring is now priced RM2999 even though 18K is selected. Click Update Cart. Price is now RM2999 

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d13235447e86beaf1ea78d_7761d3f89c580312?comments=1)

**Source URL:** [https://zcova-uat.com/cart](https://zcova-uat.com/cart)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d13235447e86beaf1ea78d_7761d3f89c580312)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1566 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d13235447e86beaf1ea78d_7761d3f89c580312) - This issue was marked as resolved in Marker.io.
