### ISSUE TITLE
Remove number of diamonds

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#173]
[![Screenshot_2022-07-18_05-58-46.png](https://mrkr.io/s/62d4f696f17e4939cff8bb9d/2)](https://mrkr.io/s/62d4f696f17e4939cff8bb9d/0)

Remove this number on mined diamond, lab diamond and gemstone pages.

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d4f696f17e4939cff8bba0_383d34f4a4dc5abc?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds?start=diamond&lab=yes](https://zcova-uat.com/diamonds?start=diamond&lab=yes)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d4f696f17e4939cff8bba0_383d34f4a4dc5abc)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1044 x 650</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d4f696f17e4939cff8bba0_383d34f4a4dc5abc) - This issue was marked as resolved in Marker.io.
