### ISSUE TITLE
Order - wrong gold

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#174]
[![Screenshot_2022-07-18_06-17-51.png](https://mrkr.io/s/62d4fb0f1643fb2ce096e20f/2)](https://mrkr.io/s/62d4fb0f1643fb2ce096e20f/0)

I ordered rose gold but white gold photo appearing

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d4fb0f1643fb2ce096e212_5622e0e6aa1721d2?comments=1)

**Source URL:** [https://zcova-uat.com/cart](https://zcova-uat.com/cart)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d4fb0f1643fb2ce096e212_5622e0e6aa1721d2)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1160 x 722</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d4fb0f1643fb2ce096e212_5622e0e6aa1721d2) - This issue was marked as resolved in Marker.io.
