### ISSUE TITLE
Order - wrong cert for lab

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#175]
[![Screenshot_2022-07-18_06-43-00.png](https://mrkr.io/s/62d500f4f17e4939cff8cbbb/2)](https://mrkr.io/s/62d500f4f17e4939cff8cbbb/0)

At Cart and After checkout. This is a lab diamond so the cert should be IGI not GIA

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d500f4f17e4939cff8cbbe_d762483e435f5eff?comments=1)

**Source URL:** [https://zcova-uat.com/user/order-details/10004](https://zcova-uat.com/user/order-details/10004)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d500f4f17e4939cff8cbbe_d762483e435f5eff)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1160 x 722</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d500f4f17e4939cff8cbbe_d762483e435f5eff) - This issue was marked as resolved in Marker.io.
