### ISSUE TITLE
Order - missing type of gold

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#176]
[![Screenshot_2022-07-18_06-57-25.png](https://mrkr.io/s/62d50455308d0ed36868e94c/2)](https://mrkr.io/s/62d50455308d0ed36868e94c/0)

When adding jewellery (wedding ring, earring, necklace, bracelet, birthstone) to cart, the Metal (yellow, rose, white, platinum) is missing

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d50455308d0ed36868e94f_bf68d85cc75409bc?comments=1)

**Source URL:** [https://zcova-uat.com/cart](https://zcova-uat.com/cart)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d50455308d0ed36868e94f_bf68d85cc75409bc)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1305 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d50455308d0ed36868e94f_bf68d85cc75409bc) - This issue was marked as resolved in Marker.io.

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d50455308d0ed36868e94f_bf68d85cc75409bc) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
At the same place. For necklace, bracelet and birthstone, missing 'size'

**Comment by salimi-my** [comment]
Fixed
