### ISSUE TITLE
Diamond - Matched products

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#178]
[![Screenshot_2022-07-18_07-08-11.png](https://mrkr.io/s/62d506db680df53e37503228/2)](https://mrkr.io/s/62d506db680df53e37503228/0)

What is this supposed to be?

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d506db680df53e3750322b_c4e538758ee5fec8?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds/selected-diamond/7438049307?price_input=1070.14&cert_input=7438049307&diamond_image=https%3A%2F%2Fphoto.diamondasset.in%3A8080%2FimagesM%2F7438049307.jpg&currency_input=MYR&cart_id=&diamond_start=no&lab_grown=no](https://zcova-uat.com/diamonds/selected-diamond/7438049307?price_input=1070.14&cert_input=7438049307&diamond_image=https%3A%2F%2Fphoto.diamondasset.in%3A8080%2FimagesM%2F7438049307.jpg&currency_input=MYR&cart_id=&diamond_start=no&lab_grown=no)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d506db680df53e3750322b_c4e538758ee5fec8)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1160 x 722</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d506db680df53e3750322b_c4e538758ee5fec8) - This issue was marked as resolved in Marker.io.
