### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#179]
[![Screenshot_2022-07-19_02-15-46.png](https://mrkr.io/s/62d613d2f940e0011c70ef70/2)](https://mrkr.io/s/62d613d2f940e0011c70ef70/0)

Make it more obvious when a filter is selected. Will we have a 'clear filter'?

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d613d2f940e0011c70ef73_f1a4d759a38206c4?comments=1)

**Source URL:** [https://zcova-uat.com/wedding-rings?gender=women&style=Classic+Wedding+Rings](https://zcova-uat.com/wedding-rings?gender=women&style=Classic+Wedding+Rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d613d2f940e0011c70ef73_f1a4d759a38206c4)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1392 x 867</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d613d2f940e0011c70ef73_f1a4d759a38206c4) - This issue was marked as resolved in Marker.io.
