### ISSUE TITLE
Order - Gemstone info

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#181]
[![Screenshot_2022-07-19_03-03-45.png](https://mrkr.io/s/62d61f11e806e5a94a5e5e2a/2)](https://mrkr.io/s/62d61f11e806e5a94a5e5e2a/0)

Add in ICL number, intensity, clarity, measurement and treatment

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d61f11e806e5a94a5e5e2d_85a3a6f617047ac5?comments=1)

**Source URL:** [https://zcova-uat.com/cart](https://zcova-uat.com/cart)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d61f11e806e5a94a5e5e2d_85a3a6f617047ac5)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1410 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d61f11e806e5a94a5e5e2d_85a3a6f617047ac5) - This issue was marked as resolved in Marker.io.
