### ISSUE TITLE
Homepage - Mailchimp

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#182]
[![Screenshot_2022-07-19_04-09-21.png](https://mrkr.io/s/62d62e710f746e3dcbde427d/2)](https://mrkr.io/s/62d62e710f746e3dcbde427d/0)

<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif;  width:600px;}
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://zcova.us16.list-manage.com/subscribe/post?u=2d5da798cc91566a3f3611dde&amp;id=0f1fb4756f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2></h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div hidden="true"><input type="hidden" name="tags" value="3477254"></div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_2d5da798cc91566a3f3611dde_0f1fb4756f" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[1]='FULLNAME';ftypes[1]='text';fnames[0]='EMAIL';ftypes[0]='email';fnames[2]='MMERGE2';ftypes[2]='number';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d62e710f746e3dcbde4280_bdf8f80e5501e491?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d62e710f746e3dcbde4280_bdf8f80e5501e491)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1410 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d62e710f746e3dcbde4280_bdf8f80e5501e491) - This issue was marked as resolved in Marker.io.
