### ISSUE TITLE
Featured Products

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#183]
[![Screenshot_2022-07-20_08-23-42.png](https://mrkr.io/s/62d7bb8e7295a3a8299d2545/2)](https://mrkr.io/s/62d7bb8e7295a3a8299d2545/0)

Unable to add new ring to signature engagement ring. 'Select' Button cannot be pressed

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d7bb8e7295a3a8299d2548_d40808a6eaac9b87?comments=1)

**Source URL:** [https://zcova-uat.com/admin/featured-product/listing](https://zcova-uat.com/admin/featured-product/listing)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d7bb8e7295a3a8299d2548_d40808a6eaac9b87)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1419 x 741</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d7bb8e7295a3a8299d2548_d40808a6eaac9b87) - This issue was marked as resolved in Marker.io.
