### ISSUE TITLE
Step 3 Gemstone ICL none

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#184]
[![Screenshot_2022-07-21_02-16-41.png](https://mrkr.io/s/62d8b7097295a3a829a00c4d/2)](https://mrkr.io/s/62d8b7097295a3a829a00c4d/0)

Not sure why there's an ICL: None here

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d8b7097295a3a829a00c50_04b3d6dfac715013?comments=1)

**Source URL:** [https://zcova-uat.com/complete-ring?start=gemstone](https://zcova-uat.com/complete-ring?start=gemstone)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d8b7097295a3a829a00c50_04b3d6dfac715013)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1410 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d8b7097295a3a829a00c50_04b3d6dfac715013) - This issue was marked as resolved in Marker.io.
