### ISSUE TITLE
Step 1 wrong gemstone

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#185]
[![Screenshot_2022-07-21_07-52-18.png](https://mrkr.io/s/62d905b2eaf0f4eddf3cba8c/2)](https://mrkr.io/s/62d905b2eaf0f4eddf3cba8c/0)

Clicked on the square to 'view' but a different gemstone appeared

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d905b2eaf0f4eddf3cba8f_02ce59c7216d666e?comments=1)

**Source URL:** [https://zcova-uat.com/gemstones/selected-gemstone/4783?cartID=78&cartType=gemset&start=gemstone&start=gemstone](https://zcova-uat.com/gemstones/selected-gemstone/4783?cartID=78&cartType=gemset&start=gemstone&start=gemstone)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d905b2eaf0f4eddf3cba8f_02ce59c7216d666e)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1410 x 812</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d905b2eaf0f4eddf3cba8f_02ce59c7216d666e) - This issue was marked as resolved in Marker.io.
