### ISSUE TITLE
Size cannot change

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#186]
[![Screenshot_2022-07-26_04-22-21.png](https://mrkr.io/s/62df6bfddbbc4453a22f5128/2)](https://mrkr.io/s/62df6bfddbbc4453a22f5128/0)

choose size 21 but it show size 6.

---

**Reported by:** wendy leong (wendy.leong520@gmail.com) - [Contact via Marker.io](https://app.marker.io/i/62df6bfddbbc4453a22f512b_c8b86391359ff0a2?comments=1)

**Source URL:** [https://zcova-uat.com/complete-ring](https://zcova-uat.com/complete-ring)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62df6bfddbbc4453a22f512b_c8b86391359ff0a2)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Windows 10.0.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 969</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62df6bfddbbc4453a22f512b_c8b86391359ff0a2) - This issue was marked as resolved in Marker.io.
