### ISSUE TITLE
Mined Diamonds / LUMOS by ZCOVA / Lab Diamonds

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#187]
can we change this part here? Mined Diamonds / LUMOS by ZCOVA / Lab Diamonds

Pressing on Lab Diamonds should lead to /lab-diamond page. It is not a filter
![0a42d0da-2376-4ff4-b153-d9e84a8e44af](https://user-images.githubusercontent.com/108924987/184566422-55049acb-6538-48b4-96bc-48cad03ff009.jpg)

**Comment by salimi-my** [comment]
Fixed

**Comment by isabelzcova** [comment]
First tab 'All Diamonds' should be 'Mined Diamonds'
2nd is LUMOS by ZCOVA not Lumos by ZCOVA

**Comment by salimi-my** [comment]
Fixed
