### ISSUE TITLE
Change promotions

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#192]
https://zcova.com/promotion

Visual: https://drive.google.com/file/d/1kqVuE_Fki2t8OKvThpP089rYcvr8KPAx/view?usp=sharing
0.4CT DIAMOND RING FOR RM 5,999 PROMOTION IN MALAYSIA
You can now enjoy a beautiful 0.4ct Round Brilliant cut diamond ring that fits within your budget with ZCOVA’s latest promotion! 

Choose your preferred choice of 14k White / Rose / Yellow Gold. You can also take advantage of ZCOVA's 0% Interest Rate Payment Plan for up to 12 months. Speak to our jewellery experts today!

**Terms & Conditions Apply

Visual: https://drive.google.com/file/d/1kq7WkAvMswexthYu2u-4Y49Vo40kwE52/view?usp=sharing
0.5CT DIAMOND RING FOR RM 9,299 PROMOTION IN MALAYSIA
Now is your chance to enjoy ZCOVA's latest promotion for 0.5ct Round Brilliant cut diamond ring for RM 9,299!

Choose your preferred choice of 14k White / Rose / Yellow Gold. You can also take advantage of ZCOVA's 0% Interest Rate Payment Plan for up to 12 months. Speak to our jewellery experts today!

**Terms & Conditions Apply

**Comment by salimi-my** [comment]
Fixed
