### ISSUE TITLE
Contact page - by appointment

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#193]
https://zcova.com/contact
Change this part:

![Screen-Shot-2022-09-12-at-4 09 53-PM](https://user-images.githubusercontent.com/108924987/189604585-dd3e6408-ddff-4c4d-9cd6-e3078a1fa071.jpg)

Our jewellery are made-to-order and each piece is customised just for you with a production lead time of 20 working days.

Get the 360-degree ZCOVA Experience when you visit our Galeria! Our friendly ZCOVA Curators will provide you with all the diamond & gemstone knowledge and services needed to create your dream fine jewellery piece.
*Consultations are by appointment only

**Comment by salimi-my** [comment]
Fixed
