### ISSUE TITLE
Dropdown menu - Ch'ya image

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#194]
Change this image in Diamond dropdown

![Screen-Shot-2022-09-12-at-5 03 27-PM](https://user-images.githubusercontent.com/108924987/189615205-52675516-c710-49ee-8d12-d6bd865fd494.jpg)

https://drive.google.com/file/d/1eZdpCzb93Y1PFqH7Va_a2PbI5k3nWwYx/view?usp=sharing

**Comment by salimi-my** [comment]
Fixed
