### ISSUE TITLE
StyleAR Code

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#195]
Please insert this code into our website to display StyleAR

         <script type="text/javascript" src="https://stylear.deepixel.xyz/stylear-zcova-all.js" id="stylear-script"></script>

**Comment by logicwisesoftware** [comment]
Code installed

<img width="972" alt="Screenshot 2022-09-26 at 7 26 29 PM" src="https://user-images.githubusercontent.com/106665593/192265299-f50b8798-03df-4d2a-9955-d4e8b69da427.png">
