### ISSUE TITLE
Contact page linking

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#196]
<img width="366" alt="Screen Shot 2022-10-03 at 10 10 06 AM" src="https://user-images.githubusercontent.com/108924987/193489628-bcea51bd-ef21-4aaf-8313-19b1c7b6ea6e.png">
Link the following
-Email us at service@zcova.com
-Call us at (+60)17 367 0666
-WhatsApp Us

For WhatsApp Us: https://web.whatsapp.com/send?phone=60173670666
Remove 'Send us a message'

**Comment by salimi-my** [comment]
Fixed
