### ISSUE TITLE
Gemstone Education Links

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#199]
<img width="823" alt="Screen Shot 2022-10-04 at 10 28 07 AM" src="https://user-images.githubusercontent.com/108924987/193721552-be3970a8-881c-4489-b446-ed32502018d8.png">
Need to change Birthstone links. Refer here:
https://docs.google.com/spreadsheets/d/1hY6Il9MNbykjeIEFHquxEilmHG9Q0t3VegmboWM1AXw/edit?usp=sharing

https://zcova.com/gemstone-education
Then on this page, change the link at this section
<img width="917" alt="Screen Shot 2022-10-04 at 10 27 44 AM" src="https://user-images.githubusercontent.com/108924987/193721680-064679ce-d1e5-48a0-8f8e-c6bb7b703798.png">

At the bottom of the page, there's a dropdown. The button 'All Birthstones', link supposed to be
https://zcova.com/birthstone
<img width="455" alt="Screen Shot 2022-10-04 at 10 26 17 AM" src="https://user-images.githubusercontent.com/108924987/193721357-2aef2c49-5060-403c-be7f-dfb57157b532.png">

**Comment by salimi-my** [comment]
Fixed
