### ISSUE TITLE
by default All Diamonds no selection. leave empty everything

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#2]
[![Screenshot_2022-06-01_12-21-16.png](https://mrkr.io/s/629759bcb893be6adb28ce5f/2)](https://mrkr.io/s/629759bcb893be6adb28ce5f/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/diamonds?start=diamond](https://zcova-uat.com/diamonds?start=diamond)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629759bcb893be6adb28ce68_30dd5d46b8dbc1ef)

**Console:** [ℹ️  2 info 📃  4 logs ](https://app.marker.io/i/629759bcb893be6adb28ce68_30dd5d46b8dbc1ef?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1099</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629759bcb893be6adb28ce68_30dd5d46b8dbc1ef) - This issue was marked as resolved in Marker.io.
