### ISSUE TITLE
add new btn to download invoices in bulk

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#20]
[![Screenshot_2022-06-01_14-45-46.png](https://mrkr.io/s/62977b9ac4004c50ab0c2928/2)](https://mrkr.io/s/62977b9ac4004c50ab0c2928/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/admin/order/listing-paid](https://zcova-uat.com/admin/order/listing-paid)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62977b9ac4004c50ab0c2930_1f143919cc76e23c)

**Console:** [ℹ️  2 info 📃  3 logs ](https://app.marker.io/i/62977b9ac4004c50ab0c2930_1f143919cc76e23c?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1144</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed
