### ISSUE TITLE
Sign up links with duplicate terms

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#200]
![Screen-Shot-2022-10-04-at-10 33 10-AM](https://user-images.githubusercontent.com/108924987/193722263-79a1153a-4f82-4408-863a-9bd5faa07e38.jpg)
At links like https://zcova.com/engagement-ring/vintage, if you click on profile and 'Sign Up', the 'Privacy Policy' and 'Terms & Condition' link is wrong.

change href="privacy-policy"
to href="/privacy-policy"

**Comment by salimi-my** [comment]
Fixed
