### ISSUE TITLE
Custom Engagement Ring Landing Page

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#203]
Need a new page. Need advice on how the upload photos section will work.
Design refer to: https://drive.google.com/file/d/1wXX-5bEvKkTzEAmCb7HX_5Yw3raM99ZL/view?usp=sharing
URL: www.zcova.com/custom

**Banner Section**
Photo: https://drive.google.com/file/d/1xMZ0eilx5VfyxxGYcL3GvS4D6imTNHKW/view?usp=sharing
Customised Engagement Rings
Design your engagement ring for free with our jewellery designers! Custom-made rings come with 3D renders and 3D prints to try on.
[Speak to Us](https://zcova.com/contact)

**Steps section**
Custom Ring Design Process

Photo: https://drive.google.com/file/d/1xWKFMUbM8jpdWuHHWBRDEwsZnIcp684x/view?usp=sharing
1
Conceptualise Ideas with Curators

Photo: https://drive.google.com/file/d/1xgcAuqUB0cNHmI3zs_dQlgFZkt8bQqmd/view?usp=sharing
2
Receive 3D Render to View Design

Photo: https://drive.google.com/file/d/1x6CoUKiuLcZ8el9CAJL_Eq4s7x-E8xzl/view?usp=sharing
3
Receive 3D Print to Try On

Photo: https://drive.google.com/file/d/1x6JVmVLm5-kxuXLt8U8vWm8o0RYDvivg/view?usp=sharing
4
Your Ring is Complete!

**Upload section**
Get Started With Your Design
Send us photos or sketches of designs you like.
[Upload Now]

**Testimonial section**
REMOVE THIS

**banner section**
REMOVE THIS

**Top Custom Design section**
REMOVE THIS

**photo section**
Customised Rings We've Designed for Customers
Photo: https://drive.google.com/drive/folders/1yuyTUGpfUW1C1UyvEf2QIt24MfcdKWgT?usp=sharing

We are passionate about the quality of our jewellery. With over 40 years of experience, our jewellery craftsmen dedicate themselves to perfecting their jewellery crafting skills. Each unique piece is created by order with exceptional finishing, which is the hallmark of our brand.

[View More Designs](https://www.pinterest.com/zcovajewel/)

**Comment by logicwisesoftware** [comment]
is there any form needed to fill by the customer when the uploaded the photo?

**Comment by isabelzcova** [comment]
Updated, URL should be www.zcova.com/custom

**Comment by salimi-my** [comment]
Custom Engagement Ring landing page already committed through URL [https://zcova.com/custom](https://zcova.com/custom). Please do check.

**Comment by isabelzcova** [comment]
Can you replace the links here as well?

**Dropdown menu**
>Engagement Ring
>>CUSTOMISE YOUR ENGAGEMENT RING
>>Truly Yours by ZCOVA

>Wedding Rings
>>CUSTOMISE YOUR WEDDING RING
>>Truly Yours by ZCOVA

>Diamond
>>CUSTOMISE YOUR DIAMOND JEWELLERY
>>Truly Yours by ZCOVA

>Gemstone
>>CUSTOMISE YOUR GEMSTONE JEWELLERY
>>Truly Yours by ZCOVA

>Fine Jewellery
>>CUSTOMISE YOUR JEWELLERY
>>Truly Yours by ZCOVA

**Other pages**
https://zcova.com/engagement-ring-education
>Customize Your Dream Engagement Ring section

https://zcova.com/wedding-ring-education
>Customise Your Wedding Rings section

https://zcova.com/fine-jewellery-education
>Jewellery Piece That's Uniquely Yours section

**Comment by salimi-my** [comment]
Fixed
