### ISSUE TITLE
BM Engagement Ring Education

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#205]
URL: https://zcova.com/engagement-ring-education-bm

**Banner 1**
Cincin Tunang dan Nikah
Dapatkan cincin kahwin idaman anda di ZCOVA!
[Lihat Koleksi Cincin]

**Banner 2**
Cincin Kahwin Tempahan Khas
Pilih mana-mana bentuk cincin emas yang diinginkan dan pasangkan dengan berlian pilihan anda.
[Pilih Berlian] [Pilih Cincin]

**Carousel 1**
Cincin Kahwin ZCOVA Signature

**Banner 3**
LUMOS by ZCOVA
Berlian LUMOS by ZCOVA kami dijamin cantik dan bersinar dengan dua sijil dari GIA dan GemEx.
[Lihat Berlian LUMOS]

**Carousel 2**
Cincin Kahwin Popular

**2 Column**
Photo: https://drive.google.com/file/d/1zal2I7bMYjBu9iyXa52L1HDCE7bSNHAG/view?usp=sharing
Cincin Tunang Perempuan (https://zcova.com/wedding-ring/women)

Photo: https://drive.google.com/file/d/1zaAss6lAfi0E3-y3eCw0rF8ud7PqXev4/view?usp=sharing
Cincin Kahwin Lelaki (https://zcova.com/wedding-ring/men)

**Carousel 3**
Jenis Cincin Nikah Kahwin

**Diamond Shape**
Pilih Bentuk Berlian

**Banner 4**
Cincin Kahwin Custom
Ingin memiliki cincin tunang atau nikah yang unik? Kami menyediakan servis gambar render 3D dan cincin cetak 3D untuk mencuba reka bentuk anda!
[Hubungi Kami]

**Blog section**
Proses Membeli Cincin Nikah
Bentuk Berlian Mana yang Terbaik?
Servis Propose With ZCOVA

**Comment by logicwisesoftware** [comment]
how do user choose between en and bm? is there a button at the top of landing to select the language?

**Comment by isabelzcova** [comment]
Cannot choose. This will only serve as a landing page for our ads at the moment

**Comment by salimi-my** [comment]
Fixed
