### ISSUE TITLE
Price match guarantee button

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#209]
https://zcova.com/price-match-guarantee
At the bottom of this page, add a button
Button text: View Terms & Conditions
Button link: https://zcova.com/terms-and-conditions anchor 'Price Match'

**Comment by salimi-my** [comment]
Fixed

**Comment by isabelzcova** [comment]
I don't see this change?

**Comment by salimi-my** [comment]
SSL certificate problem prevented the live update. It is fixed now. Can check again.
