### ISSUE TITLE
Change H1

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#210]
Replace the current H1 with these:

https://zcova.com/
*Change this H2 to H1
Customised Engagement Rings, Wedding Rings & Jewellery
![5635de13-50c4-4cb5-b6d5-f445052db3fd](https://user-images.githubusercontent.com/108924987/200762784-e4c3e51c-d1c2-4ecb-a539-3fc2081007df.jpg)

https://zcova.com/wedding-ring-education
Customised Gold & Diamond Wedding Rings

https://zcova.com/engagement-ring-education
Handcrafted Diamond Engagement Rings

https://zcova.com/mined-diamond-education
Mined Diamonds With Dual Certification

https://zcova.com/gemstone-education
Customised Gemstone Jewellery 

https://zcova.com/fine-jewellery-education
Customised Diamond & Gemstone Fine Jewellery

**Comment by salimi-my** [comment]
Fixed

**Comment by isabelzcova** [comment]
First one on homepage is not done

**Comment by salimi-my** [comment]
SSL certificate problem prevented the live update. It is fixed now. Can check again.

**Comment by isabelzcova** [comment]
<img width="823" alt="Screenshot 2022-11-10 at 10 51 28 AM" src="https://user-images.githubusercontent.com/108924987/200988896-729f9aed-1c03-4d80-af28-e358cc2d3cac.png">

**Comment by salimi-my** [comment]
Fixed
