### ISSUE TITLE
Add in Consultation in pages

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#213]
In ALL product pages (engagement ring, wedding ring, earring, necklace, bracelet)
In ALL stone pages (mined diamond, LUMOS, lab grown, gemstone)

Remove 'Description', 'Additional Information', 'your order', 'shop with confidence', 'exclusive offer' at the bottom.
Add in 'Need Help Choosing the Right One?' like this. Please use standardised font type and size (whatever you're using now) as the attached image is just a reference.
![Artboard 3](https://user-images.githubusercontent.com/108924987/202063786-9caf9cf5-0796-4721-a6e9-317e1573da9f.png)

![Artboard 4](https://user-images.githubusercontent.com/108924987/202063606-de405b29-aef2-4f32-b020-cf390a1e4fb7.png)

Need Help Choosing the Right One?
Enjoy our signature 1-on-1 personal consultation! The Diamond & Gemstone Buying Experience that is Rated 5 Stars by 900+ online reviews. Speak to our Curators online or visit a Galeria!

1-on-1 Diamond Education
Learn about diamonds in a fun and relaxed way. Get expert diamond recommendations for your requirements and price range.

Get Her Dream Ring
We’ll recommend the perfect ring and estimate your partner's size. Not sure which ring to get? Ask about our Propose with ZCOVA Service!

Offline or Virtual Consultations
Can’t visit our physical Galeria? Speak to our Curators from anywhere in the world via video call. The same service at your convenience.

Button: GET EXPERT ADVICE (https://zcova.com/contact)

**Comment by salimi-my** [comment]
Fixed
