### ISSUE TITLE
Add in Consultation in pop-up

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#214]
Popup delay: 10 seconds
*Note to developer: font type, size of font + design Is just reference. Please adjust accordingly.

![Artboard 5](https://user-images.githubusercontent.com/108924987/202067774-d592f2d6-c5d3-4c09-9c04-2b234cf44be4.jpg)

Background colour: #ededed
Image: https://drive.google.com/file/d/1-lPv1_Hq9lSH2JlAEyxLwsXZLjKz9qYi/view?usp=sharing

Need Help Choosing
the Right One?
Enjoy our signature 1-on-1 personal consultation! The Diamond & Gemstone Buying Experience that is Rated 5 Stars by 900+ online reviews. Speak to our Curators online or visit a Galeria!

Button: GET EXPERT ADVICE (https://zcova.com/contact)
NO THANKS (close pop-up)

**Comment by salimi-my** [comment]
Fixed

**Comment by isabelzcova** [comment]
Can you make it so that the customer only sees the pop-up once per session? If not it will appear at every single page they browse.

**Comment by salimi-my** [comment]
Yes I already did that. Did it pop up again after closing the modal?

**Comment by isabelzcova** [comment]
Yes, once you open another page it pops up again. I think this is only happening at pages which open in new tab (all our product buttons open in new tab)

**Comment by salimi-my** [comment]
Fixed

**Comment by salimi-my** [comment]
Fixed
