### ISSUE TITLE
Contact form Thank you page / pop up

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#215]
We are trying to track contact form sends in our campaign conversions.

Can you create either a 'thank you page' with a unique URL or a pop-up so we can track how many people submitted the form?

**Comment by salimi-my** [comment]
Yes we can. But first can you explain in details how do you want to do this? Do you mean we create our own tracker or use 3rd party tracker that we need to send response to after form submitted?

**Comment by isabelzcova** [comment]
When customer submits form on contact page, it will lead them to a thank you page (https://zcova.com/contact-thank-you)

Text: Thank you for your message. Our Curators will get back to you as soon as possible.
Button: Back To Home (https://zcova.com/)

My team will track the number of Page Views on this Thank You page.

**Comment by salimi-my** [comment]
Fixed
