### ISSUE TITLE
Homepage Change statistics 

### ISSUE THREAD

**Issue by beatricezcova** [logicwisesoftware/zcova#219]
Can help to change these statistic numbers? 

USD 6.9mil saved to **USD 9mil**

7000+ happy customers to **8701** happy customers

700+ Reviews to **967** Reviews 

![IMG_D2F6FABD641F-1](https://user-images.githubusercontent.com/120149385/206613187-35bca0c2-5f97-42e8-9ac7-32ee6ca91529.jpeg)

**Comment by salimi-my** [comment]
Fixed
