### ISSUE TITLE
Update promo on website https://zcova.com/promotion

### ISSUE THREAD

**Issue by beatricezcova** [logicwisesoftware/zcova#220]
Hi, please help to add in a new promo for the website. 

Title: **Wedding Rings Promotion Malaysia: RM 500 Off A Pair Of Wedding Rings**

Description: **Enjoy RM500 discount when you purchase a pair of wedding rings starting from 13th December 2022.  
Choose any designs from our website or customize your very own design for FREE! Click below to begin now!

**Terms & Conditions Apply**

CTA Button: Click here for more details 
Here is the URL: https://blog.zcova.com/2022/12/13/wedding-rings-rm500/?utm_source=website&utm_medium=page&utm_campaign=wr500webpromo

**Comment by salimi-my** [comment]
Added

**Comment by isabelzcova** [comment]
Title is wrong

**Comment by salimi-my** [comment]
Updated
