### ISSUE TITLE
Website - Engagement Ring Tab button

### ISSUE THREAD

**Issue by beatricezcova** [logicwisesoftware/zcova#221]
Hi, please help to remove duplication of description on "Start with a Ring Setting" and "Start with Gemstones". 

Start with Ring Setting page.
<img width="1041" alt="Screenshot 2022-12-14 at 9 29 13 AM" src="https://user-images.githubusercontent.com/120149385/207486971-767e71f2-a1b4-4a65-b4f9-87f2546a13a5.png">

Start with Gemstones page.
<img width="1042" alt="Screenshot 2022-12-14 at 9 29 59 AM" src="https://user-images.githubusercontent.com/120149385/207487025-b5ebf753-c7cc-493a-ab85-969325249012.png">

**Comment by salimi-my** [comment]
Fixed
