### ISSUE TITLE
Update promo on website https://zcova.com/promotion

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#222]
Hi, we have a new promo that needs to be added to the website please.

Title: **Diamond Ring Promotion Malaysia: 0.5CT GIA & GemEx Dual-Cert**

Description: Now is your chance to enjoy ZCOVA's latest promotion for 0.5ct diamond ring for RM 8,399!

Choose any designs from our website or customize your very own design for FREE! Click below to begin now!

**Terms & Conditions Apply**

CTA Button: Click here for more details

Here is the URL: https://blog.zcova.com/2019/09/02/zcova-0-5ct-engagement-ring-the-popular-choice/

**Comment by salimi-my** [comment]
Added

**Comment by isabelzcova** [comment]
Hi wrong URL. Here is the new one: https://blog.zcova.com/2019/09/02/zcova-0-5ct-engagement-ring-the-popular-choice/05promoblog

Remove this promo: 0.5CT DIAMOND RING FOR RM 9,299 PROMOTION IN MALAYSIA

Rearrange the order of the promotion that appears on the Promotion page from **top to bottom**:
1. 0.4CT DIAMOND RING FOR RM 5,999 PROMOTION IN MALAYSIA
2. DIAMOND RING PROMOTION MALAYSIA: 0.5CT GIA & GEMEX DUAL-CERT
3. RM 1,000 OFF A PAIR OF WEDDING BANDS
4. WEDDING RINGS PROMOTION MALAYSIA: RM 500 OFF A PAIR OF WEDDING RINGS
5. RM 500 OFF GEMSTONE PROMOTION
6. FREE 18K GOLD JEWELLERY SETTING UP TO RM 1,750 PROMOTION
7. 10% OFF CH’YA LAB GROWN DIAMOND

**Comment by isabelzcova** [comment]
.

**Comment by isabelzcova** [comment]
reopening this

**Comment by isabelzcova** [comment]
.

**Comment by salimi-my** [comment]
Updated
