### ISSUE TITLE
Update the new sitelink

### ISSUE THREAD

**Issue by beatricezcova** [logicwisesoftware/zcova#223]
Hi, please help to change all the old URLs to the new sitelinks. 
Refer to this https://docs.google.com/spreadsheets/d/1hY6Il9MNbykjeIEFHquxEilmHG9Q0t3VegmboWM1AXw/edit#gid=1851700628

for example, all these button haven't change.
 
<img width="1243" alt="Screenshot 2022-12-16 at 2 57 11 PM" src="https://user-images.githubusercontent.com/120149385/208040916-f2e08dd6-053e-49e7-b6c7-c184fc612b93.png">

**Comment by salimi-my** [comment]
Updated

**Comment by isabelzcova** [comment]
hi, this is still not done. please check again.

**Comment by salimi-my** [comment]
Hi @isabelzcova, can you please point out, explain and guide me specifically in details which parts or sections needs to be updated. Thanks.

**Comment by isabelzcova** [comment]
hi, when clicking on each of the buttons. eg. Signature Engagement Ring.. Bestseller Engagement Ring.. the sitelinks should change accordingly but remains the same. You may refer to the video below. 

https://user-images.githubusercontent.com/108924987/224591083-02e257ba-e5a1-4304-91ac-962ae16f020e.mov

same goes for wedding ring page

https://user-images.githubusercontent.com/108924987/224595279-c377f347-f5b7-42f5-8f9f-e848a518ad75.mov

Please do for Diamond, Gemstone and Fine Jewellery too.

Thank you.
