### ISSUE TITLE
Backend - merge Headings and Metadata

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#225]
merge Headings and Metadata into same page so we can edit both at the same time.

And make Headings editable for all pages. Now we can only edit 10 pages.

**Comment by salimi-my** [comment]
> 

We can merge Heading & Metadata into same page. But first can you clarify what do you mean by make Heading editable for all pages?

![heading](https://user-images.githubusercontent.com/55532224/209047068-42082661-2f7b-4c2b-9753-506a19e3d3d4.png)

Heading is for editing text as image above which is diamond listing page. If you need all pages, which part of text should be editable?

**Comment by isabelzcova** [comment]
I need editable headings on these other pages as well
https://zcova.com/lumos-diamond
https://zcova.com/engagement-ring/solitaire
https://zcova.com/engagement-ring/halo
https://zcova.com/engagement-ring/pave
https://zcova.com/wedding-ring/women

and all the other pages that have their own URL

**Comment by salimi-my** [comment]
Updated

**Comment by salimi-my** [comment]
![image](https://user-images.githubusercontent.com/55532224/210029481-7e9d4ea5-0b5c-433c-a6df-7f4a57204012.png)
There is no need for switch on. Pages which has heading shows "Yes" on "Has Heading" column.

![has-heading](https://user-images.githubusercontent.com/55532224/210029767-6da5310f-d5d2-41ee-91a6-1919a7171171.png)
Pages that has heading can edited through page heading textarea as above image.

**Comment by isabelzcova** [comment]
As mentioned, I need editable headings on all the other pages that have their own URL

**Comment by salimi-my** [comment]
[URL Relink Edited.xlsx](https://github.com/logicwisesoftware/zcova/files/10335007/URL.Relink.Edited.xlsx)
![image](https://user-images.githubusercontent.com/55532224/210319988-8313306c-4fdf-4376-810d-f9d870772495.png)
I checked the sitemap. Sub pages & main product pages which should be in Header + Metadata list already there. You can check the excel file. I already added new column and write DONE on each link which already in Header + Metadata list. Please point out on which links you want to add to the list.

**Comment by isabelzcova** [comment]
Should be all done for now. I will update if any links missing
