### ISSUE TITLE
Product subpages issues

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#228]
There are no products in some of the pages. I did not check all, just randomly checked

Example:
https://zcova.com/engagement-ring/white-gold/
https://zcova.com/wedding-ring/women/white-gold/
https://zcova.com/gemstone/fancy-sapphire/

**404**
https://zcova.com/wedding-ring/women/platinum/

**Comment by salimi-my** [comment]
Fixed
