### ISSUE TITLE
Homepage and Landing Pages Copywriting Changes

### ISSUE THREAD

**Issue by beatricezcova** [logicwisesoftware/zcova#229]
Hi, can help to implement changes to the Homepage. The changes are in red. 

Refer: [Website Layering Homepage.docx](https://github.com/logicwisesoftware/zcova/files/10358032/Website.Layering.Homepage.docx)

**Comment by salimi-my** [comment]
Updated

**Comment by isabelzcova** [comment]
hi, please make changes to these landing pages. See changes in red. Link as below:

1. Mined Diamond landing page
[Mined Diamond Education layering.docx](https://github.com/logicwisesoftware/zcova/files/10541687/Mined.Diamond.Education.layering.docx)
2. Wedding Ring Education landing page
[Wedding Ring Education layering.docx](https://github.com/logicwisesoftware/zcova/files/10541688/Wedding.Ring.Education.layering.docx)
3. Engagement Rings landing page
[Engagement Rings layerings.docx](https://github.com/logicwisesoftware/zcova/files/10541689/Engagement.Rings.layerings.docx)
4. Fine Jewellery landing page
[Fine Jewellery layering.docx](https://github.com/logicwisesoftware/zcova/files/10541795/Fine.Jewellery.layering.docx)
5. Gemstones Education landing page
[Gemstones Education layering.docx](https://github.com/logicwisesoftware/zcova/files/10541873/Gemstones.Education.layering.docx)
6. Mined Diamond landing page
[Mined Diamond layering.docx](https://github.com/logicwisesoftware/zcova/files/10541895/Mined.Diamond.layering.docx)
7. Lab Diamond landing page
[Lab diamond layering.docx](https://github.com/logicwisesoftware/zcova/files/10542129/Lab.diamond.layering.docx)
8. Wedding rings landing page
[Wedding ring layering.docx](https://github.com/logicwisesoftware/zcova/files/10542178/Wedding.ring.layering.docx)
9. lumos diamond landing page
[Lumos diamond layering.docx](https://github.com/logicwisesoftware/zcova/files/10542209/Lumos.diamond.layering.docx)
10. Gemstones layering
[Gemstones layering.docx](https://github.com/logicwisesoftware/zcova/files/10542247/Gemstones.layering.docx)

**Comment by salimi-my** [comment]
Updated
