### ISSUE TITLE
Homepage change video

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#230]
<img width="1192" alt="Screenshot 2023-01-09 at 2 33 25 PM" src="https://user-images.githubusercontent.com/108924987/211252067-597f591b-e146-4f63-ae0b-17f9c02ef636.png">
We would like to change this video on homepage. The current video is not playing on mobile as well. How do we solve this?

New video
https://drive.google.com/file/d/1Rokglw0jOHQOBE0-VMi8WLmPvqjdN8pj/view?usp=sharing

**Comment by salimi-my** [comment]
Updated
