### ISSUE TITLE
Change link of the button

### ISSUE THREAD

**Issue by beatricezcova** [logicwisesoftware/zcova#231]
Hi, I want every link to change everytime I click the button. 

Please refer to this link (under Sitemap tab): https://docs.google.com/spreadsheets/d/1hY6Il9MNbykjeIEFHquxEilmHG9Q0t3VegmboWM1AXw/edit#gid=630369869

eg. for the below image to change the URL from https://zcova.com/engagement-ring?start=setting to https://zcova.com/engagement-ring
<img width="1277" alt="Screenshot 2023-01-10 at 10 56 25 AM" src="https://user-images.githubusercontent.com/120149385/211451607-afe551a1-7ee7-46dc-9b8e-66d407a1c7c4.png">

**Comment by salimi-my** [comment]
Hi, can can you please clarify which button needs to be updated?

**Comment by beatricezcova** [comment]
Hi, for all the buttons. Please refer to the link.

**Comment by salimi-my** [comment]
Updated
