### ISSUE TITLE
Change images of Homepage

### ISSUE THREAD

**Issue by beatricezcova** [logicwisesoftware/zcova#232]
Hi, can change 1st and 2nd image of the Homepage for this section. 

<img width="1277" alt="Screenshot 2023-01-11 at 2 25 09 PM" src="https://user-images.githubusercontent.com/120149385/212016712-6997d316-0f80-4327-a37d-beced6058ef4.png">

For **Shop Gemstones earrings**, change to this image as below:

![Picture Layout Hompage 2-18](https://user-images.githubusercontent.com/120149385/212017547-9ed008b0-9895-4fe2-80fc-62910db78678.jpg)

For **Shop Birthstones**, change to this image as below:

![Picture Layout Hompage 2 birthstone-19](https://user-images.githubusercontent.com/120149385/212018445-3eaee9a6-30ed-4931-93f2-91bb5b70680c.jpg)

**Comment by salimi-my** [comment]
Updated
