### ISSUE TITLE
Font change to white

### ISSUE THREAD

**Issue by beatricezcova** [logicwisesoftware/zcova#233]
Hi please change this highlighted font to white as cannot see. And remove link attached to it. 

![font1](https://user-images.githubusercontent.com/120149385/212793794-e886d25f-d6fe-488b-b8ca-383c4e157a6b.png)

Here is the link: https://zcova.com/about

**Comment by salimi-my** [comment]
Fixed

**Comment by beatricezcova** [comment]
Please remove this link attached to it too. 

![font2](https://user-images.githubusercontent.com/120149385/212798569-03810a25-a177-4bd1-91f5-b736ff3709df.png)

Link is the same.

**Comment by salimi-my** [comment]
Fixed
