### ISSUE TITLE
Product meta and headings

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#234]
In a product page like this
https://zcova.com/chloe

<img width="1245" alt="Screenshot 2023-01-17 at 3 21 38 PM" src="https://user-images.githubusercontent.com/108924987/212835509-de19de74-d4d9-4428-89dc-92e11fc051be.png">
We have provided the meta title and description in bulk excel but it's not applying.

<img width="1241" alt="Screenshot 2023-01-17 at 3 21 45 PM" src="https://user-images.githubusercontent.com/108924987/212835639-b430c31b-cc50-430c-b00f-ee7ce5555747.png">
'Need help choosing the right one' should not be H1 nor H2.
'Chloe Ribbon Wedding Ring' should be the H1.

**Comment by salimi-my** [comment]
Updated
