### ISSUE TITLE
New Ch'ya Landing page

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#238]
Can you create a new page?

Please refer here for images and content
https://docs.google.com/document/d/1i1XCKENjeXdrkbyqsMMG9wE8s-V9waKX1Z3gDcbh6RE/edit?usp=sharing

**Comment by salimi-my** [comment]
Created

**Comment by isabelzcova** [comment]
Design your Lab-grown Diamond Ring
background image is missing

Last button 'Customise your Lab-grown Jewellery' link is wrong

**Comment by salimi-my** [comment]
Fixed

**Comment by isabelzcova** [comment]
Shop by Lab-grown Diamond Shape section, the diamonds should link to lab grown shapes not mined.

**Comment by salimi-my** [comment]
Fixed
