### ISSUE TITLE
Change Website Menu Tab

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#239]
hi, please make changes to the website's homepage tabs menu. please see below for the brief: 

https://docs.google.com/document/d/1eeoQ9ZMyoBW6gik4LgGZhvCTCRe0fzOqqA8FQejW2C4/edit?usp=sharing     

thanks!

**Comment by salimi-my** [comment]
@isabelzcova I cannot access the document. Please make it public. Thanks.

**Comment by isabelzcova** [comment]
done. you may access it now

**Comment by salimi-my** [comment]
![image](https://user-images.githubusercontent.com/55532224/229415331-e710a53d-09ee-4cd9-816b-a0e40cc655f4.png)
Hi @isabelzcova. Could you please share the original image of ‘Truly Yours by ZCOVA’ & ‘Propose with ZCOVA’? The image should be transparent/white background.

**Comment by salimi-my** [comment]
![image](https://user-images.githubusercontent.com/55532224/229416170-76330d5c-885d-4cd2-b3a0-691ac69fc536.png)

The https://drive.google.com/file/d/1ZWunGwaVdfLeTweCtmZ_8t58fjHn1HYS/view?usp=sharing link of ‘Shop Birthstone Jewellery’ image cannot be accessed.

**Comment by isabelzcova** [comment]
Truly Yours logo: https://drive.google.com/file/d/1yGYBMaTdJ3BmwXjejMAgF6CQpbA3d8QK/view?usp=sharing

Propose logo: https://drive.google.com/file/d/1yZvz2IKlPCGvuCh2tlqR-8v1TuHfWhKK/view?usp=sharing

**Comment by isabelzcova** [comment]
Birthstone image:
https://drive.google.com/file/d/1_8R6RGTM9btcXv4VYWtgrXdmj9zRHBXs/view?usp=sharing

**Comment by isabelzcova** [comment]
For gemstone menu under Shop by Type,
[Gemstone Ring] (https://zcova.com/engagement-ring)
[Gemstone Bracelet] (https://zcova.com/bracelet)

For Fine Jewellery Menu, can you link the header for each category?
-SHOP RINGS (https://zcova.com/wedding-ring)
-SHOP EARRINGS (https://zcova.com/earring)
-SHOP NECKLACES (https://zcova.com/necklace)
-SHOP BRACELETS (https://zcova.com/bracelet)

**Comment by isabelzcova** [comment]
Diamond menu images
https://drive.google.com/file/d/1_7ZhyV2ZXfR88j2yitx60-HgGIn8QYXt/view?usp=sharing
https://drive.google.com/file/d/1_90r5H1aDCVyO92fE5gO7olaJX9YIwAz/view?usp=sharing
https://drive.google.com/file/d/1_8SAJd4XfXrUDhZ43zy2QKhU3-PlXbLM/view?usp=sharing

**Comment by salimi-my** [comment]
Completed
