### ISSUE TITLE
Wedding Ring Page - Broken Links

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#240]
URL: https://zcova.com/wedding-ring-education

**Section: Popular Wedding Rings**
Please remove Floral Eternity Wedding Ring as it is a broken link.

**Section: Shop By Style**
Matte: Replace link with https://zcova.com/wedding-ring/men/matte
Textured: Replace link with https://zcova.com/wedding-ring/men/textured

**Comment by salimi-my** [comment]
Fixed
