### ISSUE TITLE
New 916 page

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#242]
This will be an ecomm page

URL: https://zcova.com/916-gold
*no gold filter, no category filter for now

H1: 916 Gold Jewellery - The Perfect Gift for Anyone
Description: If you're looking for a classic and timeless gift that will last a lifetime, look no further! With a beautiful golden shine, ZCOVA's 916 Collection makes the perfect present for birthdays, anniversaries, graduations, Valentine's and other special occasions. Shop our beautiful collection of 916 (22K) yellow gold jewellery including rings, necklaces and bracelets.

**Comment by isabelzcova** [comment]
Products will follow columns in '916' tab
https://docs.google.com/spreadsheets/d/1-rm-truG-dTBsekbHR3MzAl7Ol4exRs9ktrb0mb2JDU/edit?usp=sharing

**Comment by isabelzcova** [comment]
Sample page layout:
![916 layout](https://user-images.githubusercontent.com/108924987/227075512-8973699b-e81b-4c35-a1c8-955791ce2547.jpg)
banner image file: https://drive.google.com/file/d/1eBhl-2dn7LA1sPy1bjTjJZQ7aeTFXf55/view?usp=sharing

Menu:
Add this image and text into Fine Jewellery menu
![916 menu](https://user-images.githubusercontent.com/108924987/226852819-467dd5d4-f19f-4c4d-affe-7a7ee5cbaf16.jpg)
text: SHOP 916 GOLD JEWELLERY
image file: https://drive.google.com/file/d/1eBhl-2dn7LA1sPy1bjTjJZQ7aeTFXf55/view?usp=sharing

**Comment by salimi-my** [comment]
Updated.

URL:
https://zcova.com/custom-jewellery
https://zcova.com/admin/custom-jewellery/listing
