### ISSUE TITLE
Fix Spelling Error

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#243]
URL: https://zcova.com/sapphire-thea-earrings

Fix spelling for occasion and centre:

This four-leaf clover earring has four marquise cut blue sapphire gemstone in the *centre*, giving it a sweet and lovely look. Suitable for any **occasion**!

**Comment by logicwisesoftware** [comment]
You may edit this at the CMS. Attached screenshot where its located.
<img width="1099" alt="Screenshot 2023-03-24 at 2 43 51 PM" src="https://user-images.githubusercontent.com/106665593/227445888-89ae9daa-c807-4e1d-8943-fdee221bd1d6.png">

**Comment by jeannizcova** [comment]
Awesome! Thanks.
