### ISSUE TITLE
Layering - https://zcova.com/engagement-ring-education

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#244]
Hi, please help to implement the changes according to the below document: 
https://docs.google.com/document/d/1yzxhaWdhIIcxZayHsqpA1fTFs2O8wNM3/edit?usp=sharing&ouid=104528691284021764093&rtpof=true&sd=true

Let me know if you need any clarification. Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Hi,

Missing H5 for Diamond Engagement Ring By Style section:
![image](https://user-images.githubusercontent.com/128021131/232378997-c24dbe70-6e0a-44dc-adf6-089d559389be.png)

Can we standardise these two to sentence case?
How do I buy diamond rings from ZCOVA?
How do I check ring size?

![image](https://user-images.githubusercontent.com/128021131/232380065-5cf04ec7-5762-4f86-ac23-a2975fc9367a.png)

Thanks!

**Comment by jeannizcova** [comment]
Hi, any updates?

**Comment by salimi-my** [comment]
Updated
