### ISSUE TITLE
Layering - https://zcova.com/bracelet

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#245]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/1AVHXwWcsKF0lIoPeV9btqTTh1uJaqnG_JsStnOm3S70/edit?usp=sharing

Let me know if you need any clarification. Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Hi, can you help to change 18k to 18K in the description below:

Explore these bracelets in many styles and type of gold, including delicate diamond chain bracelets, diamond tennis bracelets, **18k** yellow gold bracelets, **18k** white gold bracelets, **18k** rose gold bracelets, gold charm bracelets, tourmaline bracelets, amethyst bracelets, ruby bracelets, blue sapphire bracelets, emerald bracelets, gemstone bracelets, aquamarine bracelets, and more.

Thanks!

**Comment by salimi-my** [comment]
Updated
