### ISSUE TITLE
Layering - https://zcova.com/birthstone

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#246]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/1G40ZFmZfmUop2Y_VpnB49J0rpdVslHH-8evealsbEWE/edit?usp=sharing

Let me know if you need any clarification. Thanks!

**Comment by salimi-my** [comment]
Cannot access document

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Hi,

For the description, replace last line with "Shop birthstone fine jewellery online at ZCOVA for all your fine jewellery needs."

Thanks!

**Comment by salimi-my** [comment]
Updated
