### ISSUE TITLE
Layering - https://zcova.com/necklace

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#247]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/1f6RNawbRn-_rZ5jhYdoe1Ze36TGy93lkcT0ekK9fyC4/edit?usp=sharing

Let me know if you need any clarification. Thanks!

**Comment by salimi-my** [comment]
Cannot access document

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Hi,

For Question: What should I look for when buying a diamond pendant?
- Link "Book an appointment" to https://zcova.com/contact
- And change the word "budget" to price range.

Thanks!

**Comment by salimi-my** [comment]
Updated
