### ISSUE TITLE
Layering - https://zcova.com/earring

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#248]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/13r3P4AriNMJhukmr49T0UzA6twnKoZbJkXiyeNBEb_8/edit?usp=sharing

Let me know if you need any clarification. Thanks!

**Comment by salimi-my** [comment]
Cannot access document

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Hi, you missed out updating the description.

![image](https://user-images.githubusercontent.com/128021131/232361556-ef757941-5a1d-4c62-87c4-cb275f83962f.png)

Please replace entire text to the below:
ZCOVA offers an extensive range of beautiful & delicate gold earrings and diamond earrings. Browse various types of earrings from diamond stud earrings, diamond drop earrings, diamond hoop earrings, diamond dangle earrings, diamond cluster earrings to red ruby earrings, blue sapphire earrings, green emerald earrings, gemstone earrings, pearl earrings and more!

No matter if you’re looking for earrings for women or earrings for men, ZCOVA caters for all genders and ages. Shop our latest and most popular earrings in 18K yellow gold, 18K rose gold or 18K white gold. If you’re looking for a one-of-a-kind jewellery piece, design them with our Free Customization Service with ZCOVA’s in-house jewellery designer.

Whether you're looking for a special gift or just want to treat yourself to something new, our wide selection of earrings are sure to impress. Browse our website and discover the perfect pair of earrings that fits your style and price range, for any kind of occasion such as fancy dinner parties, date nights and everyday wear options.

Shop earrings online at ZCOVA today.

**Comment by salimi-my** [comment]
Updated
