### ISSUE TITLE
Layering - https://zcova.com/fine-jewellery

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#249]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/1Oo79_6WUBDGje0URKlvbxKWAVDXZYYElgkZp4aAcZ7g/edit?usp=sharing

Let me know if you need any clarification. Thanks!

**Comment by salimi-my** [comment]
Cannot access document

**Comment by jeannizcova** [comment]
Sorry, I have allowed access for all. You may try now.

**Comment by salimi-my** [comment]
Updated
