### ISSUE TITLE
add item in order items

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#25]
[![Screenshot_2022-06-01_14-56-56.png](https://mrkr.io/s/62977e3832391fa7cca11d0f/2)](https://mrkr.io/s/62977e3832391fa7cca11d0f/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/admin/order/create-order/10006](https://zcova-uat.com/admin/order/create-order/10006)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62977e3832391fa7cca11d19_67d8d8eb670bbefc)

**Console:** [ℹ️  2 info 📃  5 logs ](https://app.marker.io/i/62977e3832391fa7cca11d19_67d8d8eb670bbefc?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1144</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62977e3832391fa7cca11d19_67d8d8eb670bbefc) - This issue was marked as resolved in Marker.io.
