### ISSUE TITLE
Layering - https://zcova.com/sapphire

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#252]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/17CRiQEvuAdQQGRa_7dL0tAgrSFINkNFKwWBlvc4mQs0/edit?usp=sharing

Let me know if you need any clarification. Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
For Sapphire Jewellery designs section, you replaced the wrong paragraph. It should be in the below order:

**SAPPHIRE JEWELLERY DESIGNS**
Celebrate your relationship with your special someone or reward yourself with unique custom sapphire jewellery.

![image](https://user-images.githubusercontent.com/128021131/235580859-22e27aa1-135e-43f5-b268-48f68270c95c.png)

All gemstones from[ ZCOVA’s Asia’s Biggest Virtual Gemstone Inventory](https://zcova.com/gemstone?start=gemstone) are[ ICL certified](https://blog.zcova.com/2020/12/24/icl-cert/). For more information regarding gemstones, feel free to ask our Gemologist to answer your questions!

_____________________________

Thanks!
