### ISSUE TITLE
Layering - https://zcova.com/custom

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#253]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/1xKM6nAfW9yvlryWr_3_kght75b-OB6KBsAJN4ZIwOYc/edit?usp=sharing

Let me know if you need any clarification. Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Hi, can you help to change the H1 for this page to the below:

Custom Rings for Every Occasion

Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Hi,
![image](https://github.com/logicwisesoftware/zcova/assets/128021131/77871513-1b11-4c8e-b7de-6fdd5ec83061)
For above copy, please change "Design Your Engagement Ring for Free with our Jewellery Designers" to "Custom Rings for Every Occasion" (make this H1, there should only be ONE H1 on every page)


![image](https://github.com/logicwisesoftware/zcova/assets/128021131/213501f8-3d5d-4683-8c5a-b36a46e2bf76)

The picture above shows the current headlines
1. Replace H1 with "Custom Rings for Every Occasion"
2. H2: Custom Ring Design Process
3. Remove 1, 2, 3, 4 from H1

Let me know if you need further clarification on this.

Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Looks good now thanks!
