### ISSUE TITLE
Layering - https://zcova.com/ruby

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#254]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/1zmyjy70vT_fB5pt5iz0vQHWUE3AkNdxZcmRZ9PBRnyY/edit?usp=sharing

Let me know if you need any clarification. Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Missing line in the Ruby jewellery designs sections before the images:
"Accessorise your outfits with style or bring more passion into your relationship with our custom ruby jewellery."

![image](https://user-images.githubusercontent.com/128021131/235579678-9cc122c5-05a9-4c89-846b-d611b9298ab6.png)

Thanks!

**Comment by salimi-my** [comment]
Fixed

**Comment by jeannizcova** [comment]
Hi,

Can you help me ensure that the H1, meta title and meta description is set as per below? When I inspect the page, none are found.

Meta Title: Introduction to Ruby Gemstones | ZCOVA
Meta Description: Discover the fascinating differences between rubies & explore the world of ruby gemstone jewellery. Learn about their unique qualities & how to choose them now!
H1: Discover the Sparkle of Ruby Gemstones

**Comment by jeannizcova** [comment]
Hi, please check if the below has been implemented:

Meta Title: Introduction to Ruby Gemstones | ZCOVA
Meta Description: Discover the fascinating differences between rubies & explore the world of ruby gemstone jewellery. Learn about their unique qualities & how to choose them now!
H1: Discover the Sparkle of Ruby Gemstones

**Comment by salimi-my** [comment]
![image](https://github.com/logicwisesoftware/zcova/assets/55532224/2bc08347-5103-4f29-bf25-2ead50c0ede8)

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/e5681f88-093a-46b9-b624-9b6b11891b0a)

> Hi, please check if the below has been implemented:
> 
> Meta Title: Introduction to Ruby Gemstones | ZCOVA Meta Description: Discover the fascinating differences between rubies & explore the world of ruby gemstone jewellery. Learn about their unique qualities & how to choose them now! H1: Discover the Sparkle of Ruby Gemstones

I checked. All above been implemented.
