### ISSUE TITLE
Layering - https://zcova.com/engagement-ring/pave

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#257]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/1ECnHO4ftJNXW2qy-uzArKoBWAv44ArYoOasq-2YVoaU/edit?usp=sharing

Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Hi,

![image](https://github.com/logicwisesoftware/zcova/assets/128021131/58b08ff0-cf3a-468c-aec4-4958a42e0279)
For this section, the title should be: Elegant Pavé Setting Rings

"ZCOVA offers a collection of stunning Pavé Setting Engagement Rings." is the first sentence of the body copy.

Thanks!

**Comment by salimi-my** [comment]
Fixed
