### ISSUE TITLE
Layering - https://zcova.com/lab-diamond-education

### ISSUE THREAD

**Issue by jeannizcova** [logicwisesoftware/zcova#258]
Hi, please help to implement the changes according to the below document:

https://docs.google.com/document/d/1NL7pxQUsZ4Yr6lsvhFDIywB6VuLRCywq7Id_1a7oU4A/edit?usp=sharing

Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by jeannizcova** [comment]
Hi,

![image](https://github.com/logicwisesoftware/zcova/assets/128021131/727f7932-7a1f-426a-9033-9fd8ad07b352)

Shape and Setting should be in the answer for "How do I choose the right lab-grown diamond with the right setting?"

Thanks!

**Comment by salimi-my** [comment]
Fixed
