### ISSUE TITLE
Change contact number

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#259]
https://zcova.com/contact
Change phone number to 
+60 17-686 6693

**Comment by salimi-my** [comment]
Updated

**Comment by isabelzcova** [comment]
Can you change it to +6017-367 0666 ?

**Comment by salimi-my** [comment]
Updated

**Comment by isabelzcova** [comment]
The link is still 'tel:60176866693'

**Comment by salimi-my** [comment]
Fixed
