### ISSUE TITLE
Tennis Bracelet category

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#267]
Originally the menu had a 'Tennis Bracelet' button but it was hidden. Can you add it back in on both dropdown menu and on https://zcova.com/bracelet
<img width="969" alt="tennis bracelet" src="https://github.com/logicwisesoftware/zcova/assets/108924987/20901ae3-ed52-4c35-8f61-888280c095f1">

URL: www.zcova.com/bracelet/tennis

Category in Bulk Upload Sheet: Tennis Bracelet

These 3 products should show up:
<img width="797" alt="Screenshot 2023-06-12 at 2 15 59 PM" src="https://github.com/logicwisesoftware/zcova/assets/108924987/48599539-5d67-441f-9c6f-5eba2866d92b">

**Comment by salimi-my** [comment]
Updated
