### ISSUE TITLE
add discount code field

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#27]
[![Screenshot_2022-06-01_15-00-30.png](https://mrkr.io/s/62977f0d518e98007d9c05e8/2)](https://mrkr.io/s/62977f0d518e98007d9c05e8/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/admin/order/create-order/10006](https://zcova-uat.com/admin/order/create-order/10006)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62977f0e518e98007d9c05f4_248634568a3c4603)

**Console:** [ℹ️  2 info 📃  7 logs ](https://app.marker.io/i/62977f0e518e98007d9c05f4_248634568a3c4603?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1144</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62977f0e518e98007d9c05f4_248634568a3c4603) - This issue was marked as resolved in Marker.io.
