### ISSUE TITLE
New Ring Page

### ISSUE THREAD

**Issue by Sze-Li** [logicwisesoftware/zcova#270]
1. Create a new Ring page, no category, just live it first.

"Shop Rings" change to "Shop All Rings". Link the new Ring page under this button. 

2. Remove 'Cluster Earrings'  button.

Reference:
<img width="836" alt="Screenshot 2023-06-22 at 11 23 20 AM" src="https://github.com/logicwisesoftware/zcova/assets/137369802/984d5518-0772-42a9-a834-02368d43e514">

**Comment by salimi-my** [comment]
Updated

**Comment by isabelzcova** [comment]
The ring page is supposed to be e-commerce page like Wedding Ring, Earring etc.

**Comment by salimi-my** [comment]
Updated
