### ISSUE TITLE
New homepage banner

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#272]
Place at the first position

Image: https://drive.google.com/file/d/15g20dsiRC6-NAk2Gj2LTkPCKKWJPhWso/view?usp=sharing
ZCOVA Ipoh Galeria is opening on 7th July 2023!

Limited gifts with purchase (Pearl Necklace or 3CT Citrine Necklace worth RM1,100), RM 250 cash rebate, RM 1000 off Wedding Rings and more!

[Find Out More](https://blog.zcova.com/zcova-ipoh/)

**Comment by salimi-my** [comment]
Updated
