### ISSUE TITLE
Change dual-cert

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#273]
https://zcova.com/dual-cert

Change the content of this page accordingly:
https://docs.google.com/document/d/1m0AyZWikdmpUpiRWHGeEPGVoEh11PYrz5gyCz62TE8Q/edit?usp=sharing

Visuals can be downloaded from here:
https://drive.google.com/drive/folders/1WDQ_6Xil7Azyh0qSYDj-rrmmuhnt_ET8?usp=sharing

**Comment by salimi-my** [comment]
Cannot access Google Drive link

**Comment by isabelzcova** [comment]
Access has been opened Sent from my iPhoneOn 10 Jul 2023, at 10:47 AM, Mohamad Salimi ***@***.***> wrote:﻿
Cannot access Google Drive link

**Comment by salimi-my** [comment]
Updated
