### ISSUE TITLE
Change GemEx to Sarine

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#274]
https://zcova.com/mined-diamond-education
<img width="1077" alt="Screenshot 2023-07-13 at 3 04 19 PM" src="https://github.com/logicwisesoftware/zcova/assets/108924987/7fbe8be4-5615-4ad5-9cc9-54d05582ac95">
-LUMOS by ZCOVA guarantees the brilliance of your diamond with Dual Certification from GIA & Sarine. With a guarantee of ‘Ultimate’ grade for Light Performance, you can be confident with your ZCOVA purchase.
-Meta description:
Shop earth mined diamonds that have Dual Certification from GIA & Sarine at ZCOVA. Real diamonds in any shape, carat, cut, color and clarity that best suits you.

https://zcova.com/engagement-ring-education
<img width="1060" alt="Screenshot 2023-07-13 at 4 01 10 PM" src="https://github.com/logicwisesoftware/zcova/assets/108924987/55232620-8e20-495f-b9c4-cea89e7cccb6">
Guaranteed exceptional quality and brilliance using GIA & Sarine certificates for your engagement ring.

https://zcova.com/faq
Replace the whole 'LUMOS by ZCOVA' section with this content:
https://docs.google.com/document/d/1w03U38MZf5tJlD91CqVk9E9luLmEXeVqNPri6RdrMLI/edit?usp=sharing

https://zcova.com/promise
Replace this old image with
![3](https://github.com/logicwisesoftware/zcova/assets/108924987/87897dce-1c4e-4a03-b395-6f82e445879b)
this: 
![Dual Certifications (GIA   Sarine) for LUMOS diamond](https://github.com/logicwisesoftware/zcova/assets/108924987/45991125-baf0-48b4-9f80-6346e92b906a)
link: https://drive.google.com/file/d/1WJL7oeEKWlOWASfjyBucHhtxLdsUloHr/view?usp=sharing
Description:
Why have one when you can have two certificates to ensure you’re getting the best diamond?

ZCOVA offers Dual Certificates (GIA & Sarine) in order to guarantee the diamonds’ exceptional quality and superior brilliance!

**Comment by salimi-my** [comment]
Updated

**Comment by isabelzcova** [comment]
https://zcova.com/mined-diamond-education
Images on the page seem to have issues after the edit

**Comment by salimi-my** [comment]
Fiexed
