### ISSUE TITLE
Remove 360 icon if no video

### ISSUE THREAD

**Issue by isabelzcova** [logicwisesoftware/zcova#275]
On all product pages.
<img width="267" alt="Screenshot 2023-07-26 at 4 55 54 PM" src="https://github.com/logicwisesoftware/zcova/assets/108924987/c312b40f-652a-47be-b388-c15ddc94a125">
<img width="754" alt="Screenshot 2023-07-26 at 4 56 06 PM" src="https://github.com/logicwisesoftware/zcova/assets/108924987/afed961a-bcbd-44e0-8e7f-758b855b9f15">

**Comment by salimi-my** [comment]
Updated
