### ISSUE TITLE
Change 'GemEx' to 'Sarine'

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#276]
Hi team,

For webpage: https://zcova.com/mined-diamond?start=diamond
Please change the word 'GemEx' to 'Sarine' (see attachment below)

![Screenshot 2023-08-21 at 9 27 22 AM](https://github.com/logicwisesoftware/zcova/assets/142577916/9d72fe6e-8d94-49e7-8e36-efe1f263e432)

Thanks

**Comment by salimi-my** [comment]
Updated
