### ISSUE TITLE
[URGENT] Facebook Messenger Plug-in

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#277]
Hi team,

The Facebook Messenger Plug-in keeps popping out on and off, this seems to only happen for certain screen resolution. 
Please fix this as soon as possible, thanks

Screen recording for your reference:
https://drive.google.com/file/d/1LW99Xn2MbDHzI7MPV6BVcCIChbOTZ_UC/view?usp=sharing

**Comment by logicwisesoftware** [comment]
Fixed. Kindly reopen this ticket if the problem persisted.

**Comment by Shellytsy** [comment]
Thank you :)
