### ISSUE TITLE
Mined Diamond Page Copy Update

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#278]
Hi team

Please update the page copy as below:

**H1**
Shop GIA-certified Mined Diamonds

**Body**
Offering brilliance and dazzle, ZCOVA’s GIA-certified natural mined diamonds accentuate the beauty of jewellery, immaculately crafted in any shape, carat, cut and clarity that you desire. 

You can purchase mined diamonds as loose diamonds or set in diamond rings and jewellery. Be it solitaire, pave, halo or vintage styled engagement ring. You can also choose the quality of natural diamond that suits your taste and price range. Speak to our Curators for free expert recommendations on the best mined diamond engagement ring now!

page [link](https://zcova.com/mined-diamond?start=diamond)
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/d6db239f-9039-4e9e-a378-e203a6a49521)

Thank you

**Comment by salimi-my** [comment]
Updated.

FYI these kind pages which has heading can be updated at **Pages** > **Metadata**.

Search for the page URL and click edit button.
![image](https://github.com/logicwisesoftware/zcova/assets/55532224/dc184329-7119-4a7c-9dd8-3ff8a8555b2f)

Then edit the text on the page heading section
![image](https://github.com/logicwisesoftware/zcova/assets/55532224/0d5d0da1-bc33-4d31-9795-508455328c8e)

**Comment by Shellytsy** [comment]
I see, thanks for sharing Salimi
