### ISSUE TITLE
Mined Diamond & LUMOS by ZCOVA Page Links

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#279]
Hi team

We found that the Mined Diamond and LUMOS by ZCOVA buttons are not linked correctly. 

Problem: when we are at Mined Diamond page: https://zcova.com/mined-diamond?start=diamond and click on LUMOS by ZCOVA button, it stays in Mined diamond page. Vice versa when we are at LUMOS by ZCOVA page: https://zcova.com/lumos-diamond?start=diamond

LUMOS by ZCOVA wrong link
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/5b560cfd-d0b8-4699-86f9-993ecd4f2df3)

Mined Diamond wrong link
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/354e07d8-ad55-4d49-b294-cd33c6d42d9b)

Please fix this as soon as possible, thank you

**Comment by salimi-my** [comment]
Updated.
