### ISSUE TITLE
Mobile UI Responsiveness

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#280]
Hi team

We found out that the UI of these pages are not resized properly in mobile resolution. 
Please suggest ways to ensure legibility.

Pages:
https://zcova.com/engagement-ring-education
https://zcova.com/wedding-ring-education

Issues:
- Dark text on dark background
- Text block width not fit to page

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/c0473e6d-ba2f-4dc9-80f4-02e4792f114d)

Thank you

**Comment by salimi-my** [comment]
Updated.

![zcova com_wedding-ring-education(iPhone 14 Pro)](https://github.com/logicwisesoftware/zcova/assets/55532224/f937a1c1-0c6d-4478-8574-472324237107)
![zcova com_engagement-ring-education(iPhone 14 Pro)](https://github.com/logicwisesoftware/zcova/assets/55532224/b602a28b-0752-44fa-a126-6ec37dd14440)
![zcova com_(iPhone 14 Pro)](https://github.com/logicwisesoftware/zcova/assets/55532224/114d5874-4d72-43d4-ad02-e21f3f72de4c)
![zcova com_engagement-ring-education(iPhone 14 Pro) (1)](https://github.com/logicwisesoftware/zcova/assets/55532224/b9aa57d0-346b-4775-8291-ec815cf1baea)
