### ISSUE TITLE
Add ZCOVA Ipoh Galeria Details

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#281]
Hi team

Please add ZCOVA Ipoh Galeria information (below Penang) on [contact page](https://zcova.com/contact)

H3: ZCOVA Ipoh
link: https://goo.gl/maps/Me8FnFZe2EefXVH37

Body:
F-3A, First Floor, Travelodge Ipoh, Jalan Raja Dihilir, 30350 Ipoh, Perak

TEL: (+60) 52411565

Thumbnail will be updated by end of the day, thank you very much

**Comment by Shellytsy** [comment]
Hi team please find the thumbnail via this link
https://drive.google.com/file/d/1jFldXkmOuBUaqCTLEJt_SoMzKpiZAjHi/view?usp=sharing

**Comment by salimi-my** [comment]
Updated.
