### ISSUE TITLE
Contact Page Buttons

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#283]
Hi team

Please take note of the updates required for [contact page](https://zcova.com/contact)

1. Contact info: Icon & text
- align horizontally

2. Whatsapp Us button
- make it as button (class: com_btn)
- remove whatsapp icon
- bg colour: #06475b
- hover animation follow "send message" button (white bg, blue outline)
- text: Talk to Curator

Do let us know if you need more clarification, thank you

**Comment by logicwisesoftware** [comment]
Hi,

Would you be able to take a screenshot and scribble the expected changes on it. We are worried we might misinterpreted wrongly by just reading it here.

Thanks.

**Comment by salimi-my** [comment]
Updated

**Comment by Shellytsy** [comment]
hi team thanks for the button update

the alignment hasn't been updated ya

current:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/4c4814cc-9c15-47e4-92f2-81e655469abc)

to be updated:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/9117e436-76a7-4528-a6e0-98b1f3de04d2)

please alignt the text to the icon horizontally to the center

thank you!

**Comment by salimi-my** [comment]
Updated.
