### ISSUE TITLE
Button Style

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#284]
Hi team

Please update all the button styles with the following details, including "send message" button in [contact page](https://zcova.com/contact)"

- background: #06475B
- text colour: white
- font-size: 20px
- border-radius: 6px
- line-height: 35px
- padding: 4px 20px

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/871d3a41-b3a8-4eec-96bc-e8bfcd399c59)

hover
- background: white
- border: 1px #06475B
- text colour: #06475B
- border-radius: 6px

![Screenshot 2023-08-30 at 2 41 26 PM](https://github.com/logicwisesoftware/zcova/assets/142577916/0d066fb5-3ff7-4610-838d-7d969040adb7)

**Comment by salimi-my** [comment]
Updated. Please clear browser caches to see updated stylings.

**Comment by Shellytsy** [comment]
Hi, the button colours are not changed yet

Should be #06475B ya

wrong button bg colour:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/e074dff1-2732-4509-8cdf-f8be0f848020)

**Comment by logicwisesoftware** [comment]
Ok the background color is now updated. Kindly clear the browser cache to see new effect.

<img width="789" alt="Screenshot 2023-09-05 at 4 54 17 PM" src="https://github.com/logicwisesoftware/zcova/assets/106665593/c2680cd1-6931-461d-8eb7-7fb3f46fded7">

**Comment by salimi-my** [comment]
Button hover stylings updated.

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/9313b8d9-9f45-4259-af8e-a313fbbdfd45)

**Comment by Shellytsy** [comment]
Hi thanks for the update, the buttons at the slides are still the wrong colour ya
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/e2e0adea-5434-49f3-93aa-95f03821e2f7)

**Comment by Shellytsy** [comment]
Hi team, reminder to update the button style ya, thanks

**Comment by salimi-my** [comment]
Updated.
