### ISSUE TITLE
About Page - Our Location update

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#285]
Hi Team

Please check this update for Our Location section on [about page](https://zcova.com/about)

1. add Ipoh ([image link](https://drive.google.com/open?id=1jFldXkmOuBUaqCTLEJt_SoMzKpiZAjHi&usp=drive_fs))
2. follow this sequence: Kota Damansara > Johor > Penang > Ipoh 
3. link Google location to each galerias 
Kota Damansara: https://goo.gl/maps/Uob9m44zjuiEdBCG6
Johor: https://goo.gl/maps/TYHTQkwaqbG7eruq7
Penang: https://goo.gl/maps/dnKxpprM8vj19nQg9
Ipoh: https://goo.gl/maps/Me8FnFZe2EefXVH37

Current:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/120ec6fd-b06b-4236-8328-972081310aa7)

To be updated:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/5f87cfbb-e83a-4fd8-b8e6-96382f14d24d)

Thank you!

cc @giselle724

**Comment by salimi-my** [comment]
Updated.
