### ISSUE TITLE
Contact Page - Galeria Links Update

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#286]
Hi Team 

Please update the links for each galerias in [contact page](https://zcova.com/contact)
Kota Damansara: https://goo.gl/maps/Uob9m44zjuiEdBCG6
Johor: https://goo.gl/maps/TYHTQkwaqbG7eruq7
Penang: https://goo.gl/maps/dnKxpprM8vj19nQg9

Thank you!

cc @giselle724

**Comment by salimi-my** [comment]
Updated.
