### ISSUE TITLE
Footer Logo Update

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#287]
Hi team

Please update the GemEx logo in the footer with Sarine logo, thank you!

Sarine logo file [link](https://drive.google.com/file/d/1RZ36a46vqQ1fS34AtMX7dsm_EEp_42C6/view?usp=sharing)

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/514ed452-3488-4bcd-ad5c-e1b1af16736f)
change to:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/f7534100-2581-4765-82a1-cc3a72eb9762)

cc @giselle724

**Comment by salimi-my** [comment]
Updated.
