### ISSUE TITLE
[urgent] Contact Us Buttons Link

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#288]
Hi team

please check the 'email' and 'call us' buttons in [contact page](https://zcova.com/contact) are not linked and clickable right now

could you update this as soon as possible please, thank you

**Comment by salimi-my** [comment]
Updated.

**Comment by Shellytsy** [comment]
hi team

currently the purple area also clickable, can you make it only clickable for the icon and text please, thank you
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/68c9f657-43c4-4889-8c66-5eb7be55fe5d)

**Comment by salimi-my** [comment]
Fixed.
