### ISSUE TITLE
Add Whatsapp icon under Messenger icon

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#289]
Hi,
Could we add whatsapp icon under our messenger icon please? When customer click on the whatsapp icon, it will lead them to whatsapp chat.

<img width="174" alt="Screenshot 2023-09-12 at 5 02 07 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/79b3cce3-e028-4f58-b658-68f55f3ddc29">

Whatsapp number: +60 17-367 0666

**Comment by logicwisesoftware** [comment]
Updated
