### ISSUE TITLE
ordering arrangement

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#29]
[![Screenshot_2022-06-01_15-03-55.png](https://mrkr.io/s/62977fdbf3030f2a4b7df18d/2)](https://mrkr.io/s/62977fdbf3030f2a4b7df18d/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/admin/jewellery/listing](https://zcova-uat.com/admin/jewellery/listing)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62977fdbf3030f2a4b7df194_8b23b572fcc0ce26)

**Console:** [ℹ️  2 info 📃  2 logs ](https://app.marker.io/i/62977fdbf3030f2a4b7df194_8b23b572fcc0ce26?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1144</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62977fdbf3030f2a4b7df194_8b23b572fcc0ce26) - This issue was marked as resolved in Marker.io.
