### ISSUE TITLE
Ring 360 Preview Window Title

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#290]
Hi team 

Please update this preview window title to "View Ring" instead of "View Diamond"
Applicable for both [engagement rings](https://zcova.com/engagement-ring?start=setting) and [wedding rings](https://zcova.com/wedding-ring)

Thank you!

cc @giselle724 

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/5c1042d0-b815-44a6-a6f4-148dd01fb2a1)
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/bec50713-a9a6-4c76-ac7a-2c01cc7872d4)

**Comment by salimi-my** [comment]
Fixed for all products.
