### ISSUE TITLE
Fine Jewellery Product Duplicates

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#291]
Hi team

The products on [fine jewellery](https://zcova.com/fine-jewellery) page is duplicated, please help fix this issue ASAP, thank you

cc @giselle724 

<img width="1426" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/142577916/c6fc785a-a65e-46a5-9dfb-09da37e28d9e">

**Comment by salimi-my** [comment]
Same product imported into 2 type of jewellery.

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/fe046756-eafd-4604-bea8-38710ad611f1)

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/133bb547-6032-46b9-86e5-601110c3d2b3)

**Comment by Shellytsy** [comment]
could you please suggest a solution to solve this issue? :)

**Comment by salimi-my** [comment]
Fixed.

**Comment by Shellytsy** [comment]
Hi morning there are still duplicates here
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/fdbac3df-a937-4247-9d83-e21fed07ae83)

**Comment by salimi-my** [comment]
Sorry. Updated but forgot to commit. Can check again.

**Comment by Shellytsy** [comment]
okay it's updated now, thanks 👍🏻
