### ISSUE TITLE
Princess Diamond Shape Preset

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#292]
Hi team

Please update the [princess diamond page](https://zcova.com/mined-diamond/princess) to the right preset filter, thank you
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/dc0a2e94-cbf7-4bc5-823a-6e11caac92be)

current page linking screen recording:
https://drive.google.com/open?id=1PPdWAkYOTkHazggiZTTXZdqFq9afUpSF&usp=drive_fs

cc @giselle724

**Comment by salimi-my** [comment]
Fixed for both mined & lab diamond.
