### ISSUE TITLE
Wedding Ring Pages URL Consolidation

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#293]
Hi team

Could we consolidate the following URLs please, this is to enhance our SEO performance
Please update this by **Monday, 18 Sept 2023**, thank you

1. white gold wedding ring
consolidate:
https://zcova.com/wedding-ring/women/white-gold
https://zcova.com/wedding-ring/men/white-gold
to:
https://zcova.com/wedding-ring/white-gold

2. yellow gold wedding ring
consolidate:
https://zcova.com/wedding-ring/men/yellow-gold
https://zcova.com/wedding-ring/women/yellow-gold
to:
https://zcova.com/wedding-ring/yellow-gold

3. rose gold wedding ring
consolidate:
https://zcova.com/wedding-ring/men/rose-gold
https://zcova.com/wedding-ring/women/rose-gold
to:
https://zcova.com/wedding-ring/rose-gold

4. platinum wedding ring
consolidate:
https://zcova.com/wedding-ring/women/platinum
https://zcova.com/wedding-ring/men/platinum
to:
https://zcova.com/wedding-ring/platinum

5. diamond wedding ring
consolidate:
https://zcova.com/wedding-ring/women/diamond
https://zcova.com/wedding-ring/men/diamond
to:
https://zcova.com/wedding-ring/diamond

with that, please update the links to the navigation menu
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/9781bf2f-550d-46ba-af36-d09ddc8c4bf9)

example result:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/57cc2e6f-362a-4ded-b85d-88e9062ea000)

cc @giselle724

**Comment by salimi-my** [comment]
![image](https://github.com/logicwisesoftware/zcova/assets/55532224/e974b060-d60b-4dd8-b239-241584b82a7b)

Do you want to permanently remove the first 2 URLs or redirect the 2 URLs to [https://zcova.com/wedding-ring/white-gold](https://zcova.com/wedding-ring/white-gold)

**Comment by Shellytsy** [comment]
Hi let's redirect first, but don't remove the URLs with men and women tags 
thanks!

**Comment by salimi-my** [comment]
Updated.
