### ISSUE TITLE
Content Layerings - Wedding Rings

### ISSUE THREAD

**Issue by Sze-Li** [logicwisesoftware/zcova#294]
Hi team, kindly update the content layerings accordingly for each of the pages: 
https://drive.google.com/drive/folders/1-08qId0w6zMBPjirk-wymPFsJRfjZl4j?usp=sharing

We need this implemented by **21 Sept 2023, Thursday**. 

Thank you!

**Comment by salimi-my** [comment]
Updated.

**Comment by Sze-Li** [comment]
Hi Salimi, apologies a few more amendments on these pages:

https://zcova.com/wedding-ring/eternity
*include the full stop after the words 'for your selection'
![Screenshot 2023-09-20 at 11 09 19 AM](https://github.com/logicwisesoftware/zcova/assets/137369802/a733c760-c399-4f7c-85c7-2aaa0eb20206)

https://zcova.com/wedding-ring/men
*bands that best suit
![Screenshot 2023-09-20 at 11 19 39 AM](https://github.com/logicwisesoftware/zcova/assets/137369802/61ff1983-4264-4052-97d6-40596cd1b9dc)

https://zcova.com/wedding-ring/men
*remove 'Nothing beats seeing a ring on your hand.'
![Screenshot 2023-09-20 at 11 37 32 AM](https://github.com/logicwisesoftware/zcova/assets/137369802/c97117ae-4a99-4912-a524-c8b72cc45fe0)

*remove 'who'
![Screenshot 2023-09-20 at 11 39 22 AM](https://github.com/logicwisesoftware/zcova/assets/137369802/fac1e3ba-65ba-4bb7-bb2a-08360c0be0d2)

https://zcova.com/wedding-ring/platinum
remove "With intricate detailing, such as sparkling diamonds,' replace with *Our platinum wedding ring selections are not only a symbol of commitment but also a testament to timeless style.
![Screenshot 2023-09-20 at 11 41 30 AM](https://github.com/logicwisesoftware/zcova/assets/137369802/3d8d932c-0fb3-459f-a68b-a39cd71c7a77)

https://zcova.com/wedding-ring/rose-gold
change 'men's yellow gold wedding rings' to *men's rose gold wedding rings
![Screenshot 2023-09-20 at 12 16 07 PM](https://github.com/logicwisesoftware/zcova/assets/137369802/eaccf373-7759-4ae7-b357-cf3e3d06c851)

https://zcova.com/wedding-ring/white-gold
remove the highlighted sentence from the paragraph and add on number 9: "How can I keep my white gold...."
![Screenshot 2023-09-20 at 5 31 48 PM](https://github.com/logicwisesoftware/zcova/assets/137369802/301e6f4e-7dfd-4166-bd94-bfe7d6d5c9b6)

**Comment by salimi-my** [comment]
Please reopen closed issue if there are amendments to prevent overlooked.

**Comment by salimi-my** [comment]
> Hi Salimi, apologies a few more amendments on these pages:
> 
> https://zcova.com/wedding-ring/eternity *include the full stop after the words 'for your selection' ![Screenshot 2023-09-20 at 11 09 19 AM](https://user-images.githubusercontent.com/137369802/269148215-a733c760-c399-4f7c-85c7-2aaa0eb20206.png)
> 
> https://zcova.com/wedding-ring/men *bands that best suit ![Screenshot 2023-09-20 at 11 19 39 AM](https://user-images.githubusercontent.com/137369802/269149222-61ff1983-4264-4052-97d6-40596cd1b9dc.png)
> 
> https://zcova.com/wedding-ring/men *remove 'Nothing beats seeing a ring on your hand.' ![Screenshot 2023-09-20 at 11 37 32 AM](https://user-images.githubusercontent.com/137369802/269151663-c97117ae-4a99-4912-a524-c8b72cc45fe0.png)
> 
> *remove 'who' ![Screenshot 2023-09-20 at 11 39 22 AM](https://user-images.githubusercontent.com/137369802/269151857-fac1e3ba-65ba-4bb7-bb2a-08360c0be0d2.png)
> 
> https://zcova.com/wedding-ring/platinum remove "With intricate detailing, such as sparkling diamonds,' replace with *Our platinum wedding ring selections are not only a symbol of commitment but also a testament to timeless style. ![Screenshot 2023-09-20 at 11 41 30 AM](https://user-images.githubusercontent.com/137369802/269152264-3d8d932c-0fb3-459f-a68b-a39cd71c7a77.png)
> 
> https://zcova.com/wedding-ring/rose-gold change 'men's yellow gold wedding rings' to *men's rose gold wedding rings ![Screenshot 2023-09-20 at 12 16 07 PM](https://user-images.githubusercontent.com/137369802/269157371-eaccf373-7759-4ae7-b357-cf3e3d06c851.png)
> 
> https://zcova.com/wedding-ring/white-gold remove the highlighted sentence from the paragraph and add on number 9: "How can I keep my white gold...." ![Screenshot 2023-09-20 at 5 31 48 PM](https://user-images.githubusercontent.com/137369802/269237601-301e6f4e-7dfd-4166-bd94-bfe7d6d5c9b6.png)

Updated.

**Comment by Sze-Li** [comment]
Thanks Salimi, there wasn't a 'reopen' button available, usually there is.
But thanks for the quick amendments! Appreciate it.

--

Warmest regards,



*Sze Li,*
*Senior Digital Marketing Executive*

ZCOVA Sdn Bhd (Co no: 1145999-M)
No. 5, Lorong Teknologi B
Nouvelle Industrial Park
Taman Sains Selangor 1
PJU 5, Kota Damansara
47810 Petaling Jaya, Selangor Darul Ehsan

General: 03-6156 1888
Finance: 03-6150 8100
Mobile: 019-3718491
Website: www.zcova.com
