### ISSUE TITLE
Content Layerings - Diamond/Engagement Rings

### ISSUE THREAD

**Issue by Sze-Li** [logicwisesoftware/zcova#295]
Hi team, kindly update the content layerings accordingly for each of the pages: 
https://drive.google.com/drive/folders/1eIBlKv6wv06i9xdaSH5gyW0tAlLHYGbo?usp=sharing

We need this implemented by **21 Sept 2023, Thursday**. 

Thank you!

**Comment by salimi-my** [comment]
Updated.
