### ISSUE TITLE
Slow Messenger Pop Up on Mobile

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#296]
Hi team

The messenger plugin appears very slow on mobile, it takes at least 10s to show up. Could you help optimise to make it appear as soon as possible please? Thanks

Screen recording for your reference: [link](https://drive.google.com/open?id=1QVCVUeiWS_KgAcOxpvAdx-3Ht8blby72&usp=drive_fs)

**Comment by logicwisesoftware** [comment]
Unfortunately the loading time is controlled by FB since the plugin is loaded directly from them

For now we have synchronised the loading time of other chats (whatsapp) image to appear same time as messenger so that they will look much alike
