### ISSUE TITLE
Mobile Button Text Alignment

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#297]
Hi team

Please update the button style on mobile to make it align with the center, thanks

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/0aabeceb-73c5-4ba6-bca2-1df0125dd180)

**Comment by salimi-my** [comment]
Hi @Shellytsy.

How or what kind of dimension you test to get that first image?

This is the image result I get for the button on Mobile Large view.

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/cffbecdf-8bb0-404c-9699-946ab6217c31)

**Comment by Shellytsy** [comment]
Hi Salimi, the first image is a screenshot on iPhone 12 pro max

**Comment by salimi-my** [comment]
Can we do like this?

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/819bbad1-1caf-47e8-b378-0cfb3712f392)

Or this?
![image](https://github.com/logicwisesoftware/zcova/assets/55532224/2dd729c0-771e-41b4-9256-26b308df243e)

**Comment by Shellytsy** [comment]
Hi Salimi

Please go for this, thank you :)
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/f569abb1-144f-4688-b8f7-8d74265be124)

**Comment by salimi-my** [comment]
Updated. Please clear browser caches.
