### ISSUE TITLE
Admin Upload Product Features

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#299]
Hi team 

Would like to request these **3 features** for product upload/edit page

**1. Duplicate Products**
- to be able to duplicate an existing product 
- can then edit the details from there
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/a765d80b-ed4a-4561-8da9-b27744437111)

**2. "Add All" function** 
- for Metal & Size Variants
- to add all the selections with one click
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/662bc568-95aa-4490-a2de-820d94cb7aea)

**3. Drag to rearrange image sequence**
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/109fdd7c-0ee3-4876-8de6-8d4ee4b647d6)

Do let me know if you need further clarification. Thank you!

cc @giselle724

**Comment by logicwisesoftware** [comment]
Drag rearrangement will affect the front end display?

**Comment by Shellytsy** [comment]
yes

**Comment by salimi-my** [comment]
Updated.

**Comment by Shellytsy** [comment]
Thank you guys!
