### ISSUE TITLE
lumos setting below

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#3]
[![Screenshot_2022-06-01_12-23-03.png](https://mrkr.io/s/62975a27f027f7dffe8a74fe/2)](https://mrkr.io/s/62975a27f027f7dffe8a74fe/0)

TB% ( Table percentage )
54% - 59%

TD% ( Total Depth percentage )
60% - 62.2%

CA ( Crown Angle )
33.5 - 35

PA ( Pavilion Angle )
40.6 - 40.8

Shape only round

Cut/Polish/Sym = excellent

all the above fixed cannot be changed. the rest ok to change.

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/diamonds?start=diamond](https://zcova-uat.com/diamonds?start=diamond)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62975a27f027f7dffe8a7509_070677d6dda46d8f)

**Console:** [ℹ️  2 info 📃  6 logs ](https://app.marker.io/i/62975a27f027f7dffe8a7509_070677d6dda46d8f?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1099</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62975a27f027f7dffe8a7509_070677d6dda46d8f) - This issue was marked as resolved in Marker.io.
