### ISSUE TITLE
Homepage top bar

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#30]
[![Screenshot_2022-06-03_06-41-56.png](https://mrkr.io/s/6299ad34f3030f2a4b835938/2)](https://mrkr.io/s/6299ad34f3030f2a4b835938/0)

Lifetime Warranty - https://www.zcova.com/warranty

Dual Certificates - https://www.zcova.com/lumos-by-zcova-diamonds

Free Global Shipping - 
https://www.zcova.com/shipping

Price Match Guarantee - 
https://www.zcova.com/price-match-guarantee

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/6299ad34f3030f2a4b83593c_b3f7f8e425b5d1cd?comments=1)

**Source URL:** [https://zcova-uat.com/#](https://zcova-uat.com/#)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6299ad34f3030f2a4b83593c_b3f7f8e425b5d1cd)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/6299ad34f3030f2a4b83593c_b3f7f8e425b5d1cd?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6299ad34f3030f2a4b83593c_b3f7f8e425b5d1cd) - This issue was marked as resolved in Marker.io.
