### ISSUE TITLE
ADD PROMOTION PAGE

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#300]
**Navigation bar**
1. REMOVE 'Home' from navigation bar. ZCOVA logo should land on homepage.
2. ADD "Promotion" in navigation bar, after "Education".

**Homepage banner**
1. Upload LUMOS promo banner as the first banner in homepage.
File: https://drive.google.com/drive/folders/1uXHn_YxOpVbnkMtRwSAOFvM27oJ9zW-O?usp=sharing 

**Promotion page**
1. Overall promotion page > RM350 off LUMOS promo page > RM500 off wedding band promo page
File: https://docs.google.com/document/d/1d6HG_58Iq4hCvHJ0FFSMtUw5R6Vr-omegXdahxGhpSU/edit

**Hard deadline:
12 Oct- LIVE DATE**

**Comment by salimi-my** [comment]
- Create 3 new separate promotion pages?
- Are these new promotion pages unrelated to promotion page? ([https://zcova.com/promotion](https://zcova.com/promotion))
- All previous promotion landing pages are using zcova blog. Not using that anymore?
- Are header and footer remain the same as the one we are using for current zcova website?
- Need original images sources
- Need the URL slug for all three pages

**Comment by giselle724** [comment]
**Create 3 new separate promotion pages?**
- Can use this existing promo page for thumbnail: https://zcova.com/promotion. Don't need to have "PROMOTION" in the navigation bar then since we have https://zcova.com/promotion
- Only need to create 1 new standalone promo page for RM350 off LUMOS promo.
(We want to keep the user within the website ecosystem rather than leading them out. This is our plan moving forward.)
Updated mock: https://docs.google.com/document/d/1d6HG_58Iq4hCvHJ0FFSMtUw5R6Vr-omegXdahxGhpSU/edit 

**Are these new promotion pages unrelated to promotion page? (https://zcova.com/promotion)**
- It's related. Let's use that. 

**All previous promotion landing pages are using zcova blog. Not using that anymore?**
- We want to keep the user within the website ecosystem rather than leading them out. This is our plan moving forward. Hence the standalone promo page.

**Are header and footer remain the same as the one we are using for current zcova website?**
- Yes

**Need original images sources**
New standalone page banner: https://drive.google.com/file/d/1wp526m3brxhfZnYr8VnL4y52_rsZk7os/view?usp=drive_link 
Homepage banner: https://drive.google.com/drive/folders/1uXHn_YxOpVbnkMtRwSAOFvM27oJ9zW-O?usp=sharing

**Need the URL slug for all three pages**
- Only need 1 URL slug for the LUMOS promo page: https://zcova.com/promotion/lumos-oct-discounts

**Comment by salimi-my** [comment]
Update. Metadata can updated on [http://localhost/zcova/admin/metadata/edit/144](http://localhost/zcova/admin/metadata/edit/144)
