### ISSUE TITLE
Messenger Plug-in Bug

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#303]
Hi team

The messenger pop up bug is back. Kindly check and fix this as soon as possible please. Thanks

video for your ref:
https://drive.google.com/open?id=1WUh-SN3S6zhPuPg2afff3r-ee9gFlPGL&usp=drive_fs

**Comment by logicwisesoftware** [comment]
Tested here, unable to reproduce the bug. Can you try to open with private/incognito and see if the problem persisted. 

If the problem doesnt appear in private browser, therefore you might need to force clear cache and history of the browser that is experiencing the issue. It might have been that the browser didnt get the updated code from fb server.

**Comment by Shellytsy** [comment]
Okay solved after clearing cache, thanks
