### ISSUE TITLE
Contact Page Update

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#305]
Hi team

Please apply these updates for the contact page

1. remove email line
2. update call and whatsapp button (please refer to the images below)
3. add a heading for email form: Send us a message and our curator will reach out to you soon.

Outcome reference:
(desktop)
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/d2bcf3f5-3a7d-46c8-99a8-c0807a5acbc6)

(mobile)
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/fcdde04c-6d3e-4871-aa55-6af414af1af3)

Do let me know if there's any question, thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by Shellytsy** [comment]
Hi team,

A few things to fix

1. galeria photos are not showing
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/9fa40aa1-eebb-499a-8fc1-239e6ddcc716)

2. flip the "call us" icon vertically (as the photo attached previously), and make it slightly smaller to match Whatsapp icon size

3. make "call us" and "whatsapp us" button width the same for **mobile**

Let me know if clarifications are needed, thanks!

**Comment by salimi-my** [comment]
Fixed
