### ISSUE TITLE
Designer Picks Update

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#306]
Hi team

Please apply these updates for our new Designer Picks launch by 25 Oct 2023 (Wed)

1. **homepage banner**
visual [link](https://drive.google.com/file/d/1b7GcbcrU9D2lw_QNhLkjLCm53suByEH-/view?usp=sharing)

- set as 2nd slides (after LUMOS promo)
- copies as follow:

**H2:** 
Design Your Love, 
Your Way

**P:** 
Explore Designer Picks for 
Your Unique Engagement Ring

**CTA:** 
Browse Rings
(link: https://zcova.com/engagement-ring?start=setting) designer picks filter selected

homepage banner outcome:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/2d0b5bf9-292d-4441-9899-2a3ca5192fb0)

2. **engagement ring page filter**
- merge "Signature Engagement Rings" & "Bestseller Engagement Rings" as **"Bestseller Engagement Rings"**
- add a new filter **"Designer Picks"** (use the same icon as bestseller filter, 3rd filter option)
- ring settings for Designer Picks: (follow sequence)
[Tia](https://zcova.com/tia)
[Taylor](https://zcova.com/taylor)
[Spring](https://zcova.com/spring)
[Eleanor](https://zcova.com/three-micropave-4)
[Tulip Twisted Pave 6 Prongs](https://zcova.com/tulip-twisted-pave-6)
[Blair](https://zcova.com/micro-pave-4-prong) 
[Luna Halo](https://zcova.com/luna-halo)
[Tall Tulip Cathedral 4 Prongs](https://zcova.com/tall-tulip-cathedral-4)

Please let me know if you need further clarification, thank you :)

**Comment by Shellytsy** [comment]
Hi, note: new icons for bestseller and designer picks filter will be provided when ready. For the time being, please go ahead and use the current icon. Thanks!

**Comment by salimi-my** [comment]
1. Kindly provide the image file with the same dimensions and aspect ratio as the example images available via this [Google Drive link](https://drive.google.com/drive/folders/1F_wG4OxmcMcc7VfxfuqIzVFK9TFfcZxg?usp=sharing).

2. The GIF image you provided possesses a substantial file size of 29.1MB. My attempts to compress it resulted in only a modest reduction to 22.9MB. This is a concern, as it may significantly impede the loading speed of the landing page.

3. Could you please offer more clarity regarding the new engagement ring filter? Are we looking to seamlessly incorporate it into the existing ring categories filter, or should we create an entirely new filter section? It would be immensely helpful if you could provide visual examples illustrating the placement of this new filter within the interface.

**Comment by Shellytsy** [comment]
Hi Salimi

**Banner**
We found it hard to make gif file size small, can we use mp4 instead? You can find the video link [here](https://drive.google.com/file/d/1dPEjD1qvicAT75GTbXmZS0vq9zBy8mqb/view?usp=sharing)

For the desktop and mobile sizes, we can use the same video. For the text, please put on a solid colour block (#032632). Hope it's better for responsiveness. So the outcome will be like this:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/96e8a1ba-cb78-4c27-b823-b9107b26c7bd)

**Filter**
Here's the before and after for your reference

([Engagement Ring Page](https://zcova.com/engagement-ring?start=setting))

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/5776a9e0-9109-45bb-9b29-0821e26ad391)

icon file [link](https://drive.google.com/open?id=1o_nNkGfZxFNCr9zt5D6epx6rnAE9Bnsw&usp=drive_fs)

(Navigation Menu Dropdown)

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/e5fa7293-82bf-4e57-ba2c-781b32c3d17b)

Hope it's clear, do let me know if you need further clarification. Thanks!

**Comment by salimi-my** [comment]
Updated

**Comment by Shellytsy** [comment]
Hi Salimi, thanks for the speedy update.
There's missing buttons in the dropdown menu, please add in Bestsellers and Designer Picks, thanks!

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/b7f21dcb-cf67-4a12-869b-577c687f4704)

**Comment by Shellytsy** [comment]
Hi Salimi

Kindly replace the desktop banner with [this video](https://drive.google.com/file/d/1dWaX398qjJA57sRcALPpAblUOE0mJLwg/view?usp=sharing) instead, thanks a lot

**Comment by salimi-my** [comment]
Updated.

**Comment by Shellytsy** [comment]
Thank you Salimi, a few more details to update

1. Please apply the hover animation (reverse colour as other buttons)
hover: 
bg: #06475B
outline: #EBE8E6 

Sample hover:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/5da1a497-83e7-4cb5-b034-73a1acca8b47)

2. Is it possible to make the video play on mobile?
3. For mobile, please change the bg colour to #032632 as well, add more space above the headline for mobile, and break the body sentence as shown below

Explore Designer Picks for < br >
Your Unique Engagement Ring

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/3f1109cc-78a0-4bac-9163-02e39edc03c8)

**Comment by salimi-my** [comment]
Updated.
