### ISSUE TITLE
Remove pricing on StyleAR

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#307]
We would like to remove product pricing under Style AR.
![Uploading Screenshot 2023-11-06 at 2.17.06 PM.png…]()

**Comment by salimi-my** [comment]
Please fix the attached screenshot image.

**Comment by giselle724** [comment]
<img width="405" alt="Screenshot 2023-11-06 at 2 17 06 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/56428c78-301c-4e96-a21a-0b57d30e8732">

**Comment by salimi-my** [comment]
Updated.
