### ISSUE TITLE
Changes to Contact Us page

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#308]
We have 3 changes required for Contact Us page. Please refer to link below for detailed explanation:
https://docs.google.com/presentation/d/1n15Bzo_CeTMYTUiiFK_Ig9ELMMDwEQDXsyZHHpTh1VQ/edit#slide=id.g2988feed1f1_0_60

**Comment by salimi-my** [comment]
1. Do you intend to hide the WhatsApp button exclusively on the contact page, or should this modification be applied universally across all pages?

2. In the context of replacing the "SUBJECT" input field with an "I AM INTERESTED IN" input field, would it be more appropriate to employ a checkbox type, enabling multiple options selection, or a radio type, allowing for the selection of a single option?

**Comment by giselle724** [comment]
1. Could we replace the Whatsapp floating button with enquiry form button? Across all pages.
Enquiry form icon could be as follow:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/2ca52b0a-db86-4594-ad61-1d6a9f9431bf)

3. Yup checkbox type for multiple options selection.

**Comment by salimi-my** [comment]
1. Certainly, we can replace the WhatsApp button with an inquiry form button. But what is the link or where does the user go when they click it?

2. By replacing the "SUBJECT" field input with a checkbox labeled "I AM INTERESTED IN" with multiple options selection enabled, should I update the email subject that will be sent to ZCOVA will be in format outline as example below?

**"Contact Form - Engagement ring, Customization, Gemstones"**

**Comment by giselle724** [comment]
1. The inquire floating button can lead to the main Contact us page (where the inquire form is)

2. Yes that's good.

**Comment by salimi-my** [comment]
Updated.

**Comment by giselle724** [comment]
Some bugs:
1. When "country" is selected, an error msg pops out, and there's no drop down for "states"
2. Underneath the "inquiry" floating button, there's a black arrow icon.

<img width="1468" alt="Screenshot 2023-11-14 at 1 26 47 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/e8d1a9c4-07a8-496c-b120-af1217caeb90">

**Comment by salimi-my** [comment]
Fixed.

**Comment by giselle724** [comment]
Sorry last one. Can change "weekend"  to "Sunday" under Johor, Penang and Ipoh.
