### ISSUE TITLE
Product First Image as Thumbnail

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#309]
Hi team

Can we please make it default that the product thumbnail is the first image?
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/eae3cbf8-1d33-49c8-b044-cadbb3a226c4)

currently it's random
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/95e04747-0194-442c-9ef6-9eacd59dced2)

applicable for all products ya, thank you

**Comment by salimi-my** [comment]
Updated.
