### ISSUE TITLE
Navigation Bar need to change

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#31]
[![Screenshot_2022-06-07_07-01-31.png](https://mrkr.io/s/629ef7cb0458e0eedc092d19/2)](https://mrkr.io/s/629ef7cb0458e0eedc092d19/0)

- Wedding bands -> Wedding Rings
- Fine Jewelleries -> Fine Jewellery
- Appointment border radius -> 10px

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629ef7cb0458e0eedc092d1d_884140f3a1438c43?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629ef7cb0458e0eedc092d1d_884140f3a1438c43)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/629ef7cb0458e0eedc092d1d_884140f3a1438c43?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629ef7cb0458e0eedc092d1d_884140f3a1438c43) - This issue was marked as resolved in Marker.io.
