### ISSUE TITLE
Homepage banner (remove some banners)

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#310]
Please remove the below banners from the homepage:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/d36448f9-cb61-47d4-bcd2-c529501f1c6c)

![image](https://github.com/logicwisesoftware/zcova/assets/144078599/e62e2882-9cbd-4c6d-b6a1-92513eaac1b1)

![image](https://github.com/logicwisesoftware/zcova/assets/144078599/91041d3c-0ffa-4d43-9f07-39a0b7363199)

![image](https://github.com/logicwisesoftware/zcova/assets/144078599/f800dd49-2a46-4334-9db3-a6effd98baae)

![image](https://github.com/logicwisesoftware/zcova/assets/144078599/7ed87437-06d2-4d57-aa3a-0c30564ff7e1)

![image](https://github.com/logicwisesoftware/zcova/assets/144078599/2902bef1-574a-4ce0-a94e-b6cf1041ad40)

![image](https://github.com/logicwisesoftware/zcova/assets/144078599/b35b60fc-a3e0-47e0-ac46-e676d2ba38e2)

**Comment by salimi-my** [comment]
Removed.
