### ISSUE TITLE
LUMOS Page Revamp

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#311]
Hi team

Please update our [LUMOS landing page](https://zcova.com/dual-cert) according to the design attached below:

Desktop layout mock [link](https://drive.google.com/file/d/13CAS1jL2ddtg7MH0mW4u6CcQMprYPQB6/view?usp=sharing)
Mobile layout mock [link](https://drive.google.com/open?id=10r5a1z0SxhOq7Ti4XRVBM8zM-llObZFn&usp=drive_fs)

You can find the visual assets in this [folder](https://drive.google.com/drive/folders/10jv-P-nFsHS9Z_vVpf6w0dqhAwh-FazH?usp=sharing) 
and the content with button links in this [doc](https://docs.google.com/document/d/1VymgqCSs67H95iCaVLv5j6oaT5Mcw5lNVUBBttIni1g/edit?usp=sharing)

For FAQ section, please follow the current design.

Let me know if you need more clarification, thank you.

**Comment by salimi-my** [comment]
1. Would you kindly fix the GIA Report link? It appears to be directing to an incorrect page.
2. Are you sure you want to use all the 4 videos in the '4 Light Measurements' section? The combined file size for these videos is approximately 18MB, potentially causing a slowdown in page loading.

**Comment by Shellytsy** [comment]
Hi morning Salimi, 

1. Oops sorry the link is updated
2. Let us try to reduce the video size more and get back to you

Thank you

**Comment by Shellytsy** [comment]
Hi Salimi

Please embed this Youtube video for the 4 Light Measurements instead
https://www.youtube.com/watch?v=K3pWzToCrBY

Thank you

**Comment by salimi-my** [comment]
Hi Shelly,

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/37675dbd-e109-432d-be27-a263ecc39d64)
Can you confirm is this should be a select button, collapse or accordion?

Regarding the video, you can try to convert & compress them to .webm format. Theoretically, webm format should be higher in quality with lower file size than mp4.

**Comment by Shellytsy** [comment]
the initial stage for this button should only the "view sample reports"
when it's clicked, both reports button will dropdown (in blue bg)
it will turn beige bg when hovered
hope it's clear :)

For the video, I think we can embed using youtube link :)

**Comment by Shellytsy** [comment]
Hi team I'll be away from 16-17 Nov, if there's anything please ping @giselle724 
Will be back 20 Nov.
Thank you everyone!

**Comment by Shellytsy** [comment]
Hi team

The page is looking great!
A few small things:
1. these 2 button links are wrong should be these:
[About GIA](https://www.gia.edu/gia-about)                                                               
[About Sarine](https://blog.zcova.com/2023/07/07/sarine-light-performance-report/?utm_source=website&utm_medium=page&utm_campaign=dualcert)

2. 4 Light Measurements video width needs to be smaller, around 80% screen width
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/1a5c92d2-feca-4b65-bb37-6d98bb4a7990)

3. please update the desktop header image with [this](https://drive.google.com/open?id=1CY5uBd9GA0sf8rtSdL_-mSfZGxjCQ0r4&usp=drive_fs)

Thank you

**Comment by salimi-my** [comment]
Updated.

**Comment by Shellytsy** [comment]
Hi Salimi

Is it possible to make the 4 Light Measurements video autoplay and looped?

**Comment by Shellytsy** [comment]
Hi Salimi,

thanks for the update, it's fine :)

Can we make the video below it autoplay and looped as well? Thank you!
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/6ceafc6e-7067-4467-ac6d-caed3c7294f7)

**Comment by salimi-my** [comment]
Updated. Please close the issue if there are no more ammendments

**Comment by Shellytsy** [comment]
Thank you, that's all for now :)
