### ISSUE TITLE
Upload new promo banner and lead to new promo page

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#312]
Banner: https://drive.google.com/drive/folders/1yxhRXXValFCpmMMxuWX29027NygX6ETt?usp=drive_link

Promo landing page (NEW): Standalone (URL: 25OFF_CHYA PROMO)
https://docs.google.com/document/d/1B6tgTOCu3rKM-zvMSjLekGluZdZn_1Z8EswznSZmsDs/edit

**Comment by giselle724** [comment]
Hi any update on this?

**Comment by salimi-my** [comment]
Updated.

**Comment by giselle724** [comment]
Could you upload the banner in homepage banner also?
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/91ed0d05-2404-4094-88a0-b603740834aa)

**Comment by salimi-my** [comment]
With no text and button?

**Comment by giselle724** [comment]
Can follow the layout exactly like the visual:

CHYA logo: https://drive.google.com/file/d/1yvKwMCur-e9oHk-lZNfjiaV53wjpy5Fw/view?usp=drive_link

Text:
25% OFF
Any Ch'ya Lab Diamond

*T&Cs apply. Limited time only

Button: Find out more (Landing page: https://zcova.com/promotion/25-off-chya-promo)

**Comment by salimi-my** [comment]
Could you kindly send me this image without "25% OFF Any Ch'ya Lab Diamond" text but with "Ch'ya by ZCOVA" included.

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/c53f78b9-f86b-4831-a780-aebca88e6b34)

**Comment by giselle724** [comment]
Sure. There you go:
https://drive.google.com/file/d/1z5zDPgrQ_v-dE-5w6HUVgIIPoeFcqh32/view?usp=sharing

**Comment by salimi-my** [comment]
Updated.

**Comment by giselle724** [comment]
Hi sorry minor changes on the landing page.
For this page (https://zcova.com/promotion/25-off-chya-promo), the Talk to Curator button, can we change to the below please?

Button- Shop Ch'ya Diamonds (URL: https://zcova.com/lab-diamond-education)

**Comment by giselle724** [comment]
Hi any update on this?

**Comment by salimi-my** [comment]
Hi @giselle724. The page has been updated. I am sorry for the late update as I may had overlooked this issue because it was closed.

On another note. Please reopen closed issue if there are any ammendments. Could you please confirm whether you have the capability to reopen closed issues? If, for any reason, this functionality is not available, we may need to reassess the permissions of your account.
