### ISSUE TITLE
URGENT: CHANGE OPERATING HOURS

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#313]
Could we change operating hours for JB, Penang and Ipoh to below please:
Monday to Sunday: 930am-6:30pm

**Comment by logicwisesoftware** [comment]
Updated.

<img width="991" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/6550d78b-5469-43ce-8d9c-170cfbea4d08">
