### ISSUE TITLE
New homepage banner and T&Cs page

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#314]
Live on 1 Dec

1. Add new homepage banner: https://drive.google.com/drive/folders/1DyDi01ndEb4b_OTT9RECjcilDWjlv5I1?usp=sharing
Homepage banner land on below T&C page.

2. T&C landing page: https://drive.google.com/drive/folders/1DxGwi5BiSUR6INIu0XWnanY4xOcGnxdN?usp=sharing
Copy and layout: https://docs.google.com/document/d/1zvwFmVItJny79KzrBR16PRiQ0p7alhy5Hx2ejrTsaNU/edit 
URL: Dec_CM_Exclusive_Giveaway

**Comment by salimi-my** [comment]
Updated. Landing page: [https://zcova.com/promotion/dec-cm-exclusive-giveaway](https://zcova.com/promotion/dec-cm-exclusive-giveaway)

**Comment by salimi-my** [comment]
Updated.
