### ISSUE TITLE
New Homepage Banner

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#316]
Hi team

Please add this banner to homepage as the third banner, and link the button to [fine jewellery page](https://zcova.com/fine-jewellery-education)

Copy:
With gifts that bond, we not only share presents but express appreciation and create lasting memories.

Please find the banner and logo via [this link](https://drive.google.com/drive/folders/1zkrZEECmuPH7F1W-L2RoLRM2PZ_AQ8-k?usp=drive_link)

Desktop layout:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/9f68527d-5451-4488-9306-2d1feda412d9)

Mobile layout:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/67bab063-aff2-4216-bab4-e50eb9a85d27)

Thank you

**Comment by salimi-my** [comment]
Updated,

**Comment by Shellytsy** [comment]
Hi Salimi, thanks for the update, please arrange this as the third banner, after "december giveaway" and "rm350 off" ones. Thanks
