### ISSUE TITLE
Update Dec Giveaway landing page

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#317]
Update T&C item 1 and 2. https://zcova.com/promotion/dec-cm-exclusive-giveaway
<img width="941" alt="Screenshot 2023-12-05 at 3 35 21 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/d8f8a2cd-e47c-4854-993c-25cd3e230f88">

1. Customers who purchase on any diamond (Lab Grown or Natural) at ZCOVA will qualify for this giveaway.
2. This giveaway can be used with any ongoing promotions.

**Comment by logicwisesoftware** [comment]
Updated.

<img width="974" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/6fc7a697-9311-4fe9-b153-3cc4fa2d4a02">
