### ISSUE TITLE
Add NEW PROMO homepage banner and landing page

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#318]
1. Add new promo homepage
https://drive.google.com/drive/folders/1friFCYt5nYEKmeqSfT6DSVS9oA_vjoel
- To include logo and promo copy based on reference given.
- To include FIND OUT MORE button. -> land on below T&Cs page

2. Create a T&Cs landing page
https://docs.google.com/document/d/1B6tgTOCu3rKM-zvMSjLekGluZdZn_1Z8EswznSZmsDs/edit
URL: Dec2023_12%_Promo

**Comment by salimi-my** [comment]
Updated.
