### ISSUE TITLE
Update favicon and include in root

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#319]
Hi team

Kindly please update our website favicon with [this](https://drive.google.com/file/d/1VPcSW_V58bs1IeaQKNRncum5IOQouPlV/view?usp=sharing)

And to include it in the root of the site. As we are facing the problem of favicon not showing in search results, see attached:
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/bb5ed74b-0815-4726-8b10-60a7d4513672)
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/854da8bc-01a7-4875-9f8c-c585d74d8ee8)

**Comment by logicwisesoftware** [comment]
Favicon added.

<img width="82" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/b641c26a-96ae-4892-a764-cfe291758359">

**Comment by Shellytsy** [comment]
Hi morning, the favicon does not show in google result still. Could you help sort this out please? Thank you
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/7991a995-539c-4d5e-ae05-f75bde2b63b0)

**Comment by salimi-my** [comment]
Hi. Unfortunately, we have no control over this. We just need to wait for Google to fully recrawl the website for changes and reevaluate the icon.

**Comment by Shellytsy** [comment]
Okay, thanks for the info.
