### ISSUE TITLE
Homepage banner is distorted

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#32]
[![Screenshot_2022-06-07_07-18-12.png](https://mrkr.io/s/629efbb4890e47855e26f9b4/2)](https://mrkr.io/s/629efbb4890e47855e26f9b4/0)

- Banner maintain ratio regardless of screen size
- Title, description & button occupy max 40% of banner width, always align left
- Button spacing
- Dots to switch between banners

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629efbb4890e47855e26f9ba_611bf3f3f8e0f904?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629efbb4890e47855e26f9ba_611bf3f3f8e0f904)

**Console:** [⚠️  2 warnings ℹ️  1 info ](https://app.marker.io/i/629efbb4890e47855e26f9ba_611bf3f3f8e0f904?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629efbb4890e47855e26f9ba_611bf3f3f8e0f904) - This issue was marked as resolved in Marker.io.
