### ISSUE TITLE
Homepage Revamp

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#320]
Hi team,

Kindly refer the homepage revamp brief deck via [this link](https://docs.google.com/presentation/d/11WHP6IGKPm0NUP9vnGS7RyC2Ok8PddtpQM2nLhvLakg/edit?usp=sharing)

*Our team is still compiling the visual asset, will update under the comment once ready.

Do share the prototype with us when it's ready before it's launched. Thank you.

**Comment by Shellytsy** [comment]
Hi team, can we get an estimated date to see the prototype? :)

**Comment by salimi-my** [comment]
The landing page is estimated to be completed and available for review on 29 Dec, 2023. The landing page is anticipated to be completed within the expected timeframe but the search function maybe takes longer time.

**Comment by Shellytsy** [comment]
Alright, thanks for the update 👍🏻 Do let us know if you have any questions

**Comment by logicwisesoftware** [comment]
Hi, the revamped landing page just got updated here https://zcova.com/new-landing/

There are still a few items is not completed yet and still ongoing. Shall update again next week.

p/s Zi Yin had told us to focus on the international website for its impending launch 1st week of January. Hence, this update might get delayed, letting you know.

**Comment by Shellytsy** [comment]
Hi team, happy new year!
Thanks for the update, we do see some problems need to be fixed. But let us know once the page is completed and we shall comment, thank you.

**Comment by Shellytsy** [comment]
Hi morning team, do give us an update when the revamp is complete ya. Thanks

**Comment by salimi-my** [comment]
Layout & design for desktop & mobile already completed except the search functionality.

**Comment by Shellytsy** [comment]
Hi Salimi, we have compiled our comments on the visual in [this deck slide 12](https://docs.google.com/presentation/d/11WHP6IGKPm0NUP9vnGS7RyC2Ok8PddtpQM2nLhvLakg/edit#slide=id.g2b29a8fe45b_0_0) onwards. 

Let us know if there's any clarification needed, thank you

**Comment by Shellytsy** [comment]
Hi morning team, can I check on the search function progress please?

**Comment by logicwisesoftware** [comment]
Hi, it is still being looked at. Shall update it here once ready.

**Comment by Shellytsy** [comment]
Alright, do update as soon as possible. Let us know if discussion is needed for the mechanism

**Comment by salimi-my** [comment]
The search function has been completed, and the design and layout have been revised and adjusted in accordance with your feedback. Prior to reviewing the page, please ensure to clear your browser caches. Thank you.

**Comment by Shellytsy** [comment]
Hi Salimi,

A few amendments needed:

1. Please make ZCOVA logo **centered to the full width** instead of even spacing to the left and right elements, it looks off center now
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/e11de4a2-0ee4-4f39-885a-768d5442c5bc)

2. Please update the google review section to the latest ver, the one in march promo landing page is correct

Old copy in new homepage
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/e96da0d6-1da4-4ae2-9459-a4a12f855265)

Latest copy in promo landing page
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/7eecb32f-dab9-4245-8ced-ac84968e9ad6)

3. There's sizing issue with section 5 designer picks engagement rings on mobile, recording video [link](https://drive.google.com/file/d/1zUe2jANHS2L9NnKIN3Gec6pJ7eMf8hOj/view?usp=sharing) for your ref

4. Reminder to update footer instagram link to https://www.instagram.com/zcova_my/

We shall update the banners for section 2 soon.

Thank you

**Comment by salimi-my** [comment]
The requested amendments for adjusting the center position of the ZCOVA logo, updating the reviews text content, resizing the ring image carousel, and updating the Instagram link have been successfully implemented.

**Comment by salimi-my** [comment]
The new landing page has been successfully deployed, marking this issue as completed. If any adjustments or amendments are necessary, please feel free to create a new issue.
