### ISSUE TITLE
Update alternative favicon sizes

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#321]
Hi team,

Please help add in favicon in 16x16 and 32x32 to our website. Files can be found via [this link](https://drive.google.com/drive/folders/1i4sB6o-FrqFjwssmLqq0r6knS-NIcy70?usp=sharing).

Thank you

**Comment by salimi-my** [comment]
Updated.

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/d244af59-4198-43fc-b299-ee889b0fcfa3)
![image](https://github.com/logicwisesoftware/zcova/assets/55532224/dc683721-cb05-4ca0-acb1-47571a7c7e49)
