### ISSUE TITLE
Remove banners from homepage

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#322]
Please remove the below banners from homepage:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/d8ecb71a-950f-48a9-ad40-b7c81551e4b3)
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/616e864d-034a-42a3-9c5a-3220d06cfb09)

**Comment by salimi-my** [comment]
Banner removed.
