### ISSUE TITLE
International site content update [URGENT]

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#323]
1. Remove the below section with MYR visual
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/a959ec1b-1468-4137-8c56-ec07780bd15c)

2. Update contact us page
Call us- Change phone number to 0450716066
Whatsapp us- Change to "Message us", Change phone number to 0450716066
Floating button- Remove Whatsapp floating button and change to Messenger button.
<img width="1433" alt="Screenshot 2024-01-08 at 10 16 48 AM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/30040dff-b739-4eb9-bed5-4a772080b201">

**Comment by giselle724** [comment]
sorry 1 more to update:

1. Remove all MY outlets. Add only Adelaide one.
ZCOVA Adelaide
Opening hours:
Monday- Closed
Tuesday- 11:30am - 8pm
Wednesday- 11:30am - 8pm
Thursday- 11:30am - 8pm
Friday- 9am - 5pm
Saturday- 9am - 6pm
Sunday- Closed
*Strictly by appointment basis only.

**Comment by logicwisesoftware** [comment]
Ok it's updated.

For messenger icon, we would need the access to FB account in order to activate the messenger function and place it on the page. See if you could possibly get the fb login information.

Do you have the Adelaide image to replace here?
![Uploading image.png…]()

**Comment by giselle724** [comment]
![IMG_9092](https://github.com/logicwisesoftware/zcova/assets/144078599/b7bdf991-8a46-4d41-8753-50d777fa69ac)
Please use this. Thanks.

**Comment by logicwisesoftware** [comment]
Updated.

![Uploading Screenshot 2024-01-08 at 2.31.18 PM.png…]()

**Comment by giselle724** [comment]
For the whatsapp floating button, please change phone number to 0450716066. For international site only.
