### ISSUE TITLE
White Gold Engagement Ring Missing Image

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#324]
Hi team

[Tesoro Mio Engagement Ring](https://zcova.com/tesoro-mio/?start=diamond) product images are not showing on [White Gold Engagement Ring](https://zcova.com/engagement-ring/white-gold) page, but no problem on [Engagement Ring](https://zcova.com/engagement-ring?start=setting) page. Please help fix this.

Same for both local and international sites. 
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/6c3004e4-d111-4e6f-a771-addd0ed48ef0)
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/8a2441c8-9c90-4354-9047-94d18cd59c0c)

Thanks!

**Comment by kimberlyljw** [comment]
Hi Team,

Noticed the same problem as above for some of the yellow gold listings as well as pictured below : 

![Screenshot 2024-01-09 at 10 41 14](https://github.com/logicwisesoftware/zcova/assets/156041223/80f93feb-92f0-4598-bc38-9cd72a746721)
![Screenshot 2024-01-09 at 10 43 35](https://github.com/logicwisesoftware/zcova/assets/156041223/db46cbef-ce95-4d9b-b333-6899ab3c90c9)

Kindly assist, thanks!

**Comment by salimi-my** [comment]
![image](https://github.com/logicwisesoftware/zcova/assets/55532224/503a31f7-f181-4968-af51-a6ea2c2ef29e)

![image](https://github.com/logicwisesoftware/zcova/assets/55532224/d859f893-f70d-4919-9ad6-c6f130958932)

There no selected default image of white gold, yellow gold & rose gold for Tesoro Mio Pave Engagement Ring & Classic 3-Stone Engagement Ring.

You can update them here: 

Tesoro Mio Pave Engagement Ring edit jewellery form
[https://zcova.com/admin/jewellery/engagement-ring/edit-jewellery/84](https://zcova.com/admin/jewellery/engagement-ring/edit-jewellery/84)

Classic 3-Stone Engagement Ring edit jewellery form
[https://zcova.com/admin/jewellery/engagement-ring/edit-jewellery/87](https://zcova.com/admin/jewellery/engagement-ring/edit-jewellery/87)
