### ISSUE TITLE
Wrong Display Image Hidden Halo Engagement Ring

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#325]
Hi Team, 

Noticed incorrect display images with the [Hidden Halo Engagement Ring](https://zcova.com/hidden-halo) listing as pictured below : 

1. When looking at [Rose Gold Engagement Ring](https://zcova.com/engagement-ring/rose-gold) page : 
<img width="1213" alt="Screenshot 2024-01-09 at 10 56 28" src="https://github.com/logicwisesoftware/zcova/assets/156041223/ead48b40-3c0a-4a57-9993-10200e049397">

2. When selecting either the 14k yellow gold or 18k yellow gold filters as pictured : 
<img width="1167" alt="Screenshot 2024-01-09 at 11 00 55" src="https://github.com/logicwisesoftware/zcova/assets/156041223/4cad79cc-e058-4398-b683-f33bf2ed0167">
<img width="1235" alt="Screenshot 2024-01-09 at 11 00 34" src="https://github.com/logicwisesoftware/zcova/assets/156041223/78a7b404-f422-44b3-ad05-87aeda9648f1">

Kindly assist to fix; thanks!

**Comment by salimi-my** [comment]
The default image for white gold, yellow gold & rose gold can be updated in the edit jewellery form on zcova admin.

Images for Hidden Halo Engagement Ring can be updated here: [https://zcova.com/admin/jewellery/engagement-ring/edit-jewellery/10](https://zcova.com/admin/jewellery/engagement-ring/edit-jewellery/10)

In reference to the screenshot below, the default image for Hidden Halo Engagement Ring are incorrectly selected in edit jewellery form.
![image](https://github.com/logicwisesoftware/zcova/assets/55532224/f8e501a0-eb5c-4792-959e-7fe5b11b8efd)
