### ISSUE TITLE
Update H1 for mentioned pages

### ISSUE THREAD

**Issue by aprilcheong123** [logicwisesoftware/zcova#326]
please update the H1 for these pages:
https://zcova.com/ - Custom Engagement rings, Wedding rings & Jewellery
https://zcova.com/custom - Custom Rings for Engagement & Wedding - Design Your Own
https://zcova.com/ruby - ICL Certified Ruby Gemstone Jewellery 
https://zcova.com/emerald - ICL Certified Emerald Gemstone Jewellery

**Comment by aprilcheong123** [comment]
and for this page as well:
https://zcova.com/engagement-ring-education-bm - Cincin Tunang, Nikah, Kahwin & Merisik

**Comment by salimi-my** [comment]
Updated.
