### ISSUE TITLE
International site- Update homepage promo banner

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#327]
Update the banner below in international side
Button- Chat with us > lead to whatsapp

Visual: https://drive.google.com/drive/folders/1d59Z1ahYidLi_GFpMLD626YfVfGLCQ0e

**Comment by salimi-my** [comment]
Hi @giselle724

Kindly provide more informations regarding this banner. Where does you need the button to be placed? Which one of the three images you provide is the desktop version and which one is mobile version? Do you also need for this promo to be added to page [https://zcova.com/international/promotion](https://zcova.com/international/promotion)? If so please provide the content copies too.

Please also provide the banner image without the text including all the assets (the zcova logo, the straight line with star on the right & the necklace) if relevant.

**Comment by giselle724** [comment]
Please find banner image without text with all assets: https://drive.google.com/drive/folders/1vpw2SedqGBvq02ul8IxL9ie308nSGzF1

There's a jpg you could refer on the text placement. For button to be placed as below: 
<img width="1506" alt="Screenshot 2024-01-10 at 4 08 25 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/e6349d8c-9ed3-471c-aebf-c0ad32d0d4da">
ow:

Button lead to messenger chat.

**Comment by salimi-my** [comment]
Updated.

**Comment by giselle724** [comment]
Hi, sorry could you help update the AUD to $ please?
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/b5fe9b0e-c80c-4ad6-b7ee-63294da06b9f)

Sample:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/36587c75-c566-477c-a609-39f212e9b612)

**Comment by salimi-my** [comment]
Updated.
