### ISSUE TITLE
Change IPOH operating hours

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#328]
Please change Ipoh operating hours to below:
Showroom Operating Hours:
Weekday: 9:30am-6:30pm (Monday closed)
Saturday: 9:30am-6:30pm
Sunday: 9:30am-6:30pm
*Strictly by appointment only

**Comment by logicwisesoftware** [comment]
Updated

<img width="954" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/0612e87a-08b0-401e-a577-d171b5249955">
