### ISSUE TITLE
International Site - Update Location Image

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#329]
Hi Team,

Kindly assist to update the location image for the International Site on the "Contact Us" page as pictured below : 

<img width="1161" alt="Screenshot 2024-01-09 at 16 25 12" src="https://github.com/logicwisesoftware/zcova/assets/156041223/a505edbe-b036-4714-a1b9-1afdf5254f00">

Contact Us page : https://zcova.com/international/contact

New Image link : https://drive.google.com/file/d/1u13sapX4lk7ff41HK0F6i_HSqh9ChGoc/view?usp=sharing

Thank you!

**Comment by logicwisesoftware** [comment]
Updated

<img width="772" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/68504f9b-1fa2-40cf-92ed-87c478d4e4a5">

**Comment by giselle724** [comment]
The location for Adelaide is not correct.
Can land ppl here: https://maps.app.goo.gl/9i3YeCtXKLKTiUgTA

**Comment by salimi-my** [comment]
Updated.
