### ISSUE TITLE
Customise Any Design video

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#33]
[![Screenshot_2022-06-07_07-32-52.png](https://mrkr.io/s/629eff244e4e9b11c98374cc/2)](https://mrkr.io/s/629eff244e4e9b11c98374cc/0)

- Add title
- Add video below title: https://drive.google.com/open?id=1nB5cMiwtgeN8jZToGokp2xBkdm9Ld2HW&authuser=eewern%40zcova.com&usp=drive_fs
- Add description below video
- Add 3 buttons below description:
1. Diamond (link to https://www.zcova.com/diamond);
2. Gemstone (link to https://www.zcova.com/gemstone);
3. Setting (link to https://www.zcova.com/engagement-ring)

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629eff244e4e9b11c98374d6_7bd62005bde49c89?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629eff244e4e9b11c98374d6_7bd62005bde49c89)

**Console:** [⚠️  6 warnings ℹ️  1 info ](https://app.marker.io/i/629eff244e4e9b11c98374d6_7bd62005bde49c89?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed
