### ISSUE TITLE
Content Layerings 

### ISSUE THREAD

**Issue by aprilcheong123** [logicwisesoftware/zcova#330]
Hi team, could you help implement these content on respective pages on the website 

https://drive.google.com/drive/folders/1rXk-hncft8gdLeFsH-vO96PV1Fvb89Q1?usp=sharing

Oct Batch
https://docs.google.com/document/d/1mCiSfH1slanC6dP58-OmO9wIxM1LCV3q2uvQZhLViuI/edit?usp=sharing
https://docs.google.com/document/d/1_5KLTsNbI9OZz3eb0rXYce-PSCnE3CAqgOp19i1k3Gc/edit?usp=sharing
https://docs.google.com/document/d/1BU1y9OpHXy75xLiNbRoP42MH3B__B6gZbH-NDQjFr7Q/edit?usp=sharing
https://docs.google.com/document/d/1ps3kOQS-Qsgen4zm_3oF4Oe0HMykvCogULOYvHcnwr4/edit?usp=sharing
https://docs.google.com/document/d/1SFn4UjlMrUkn1hRyTwbgHBDlm-yIDPl-ggTYxR2DS3s/edit?usp=sharing
https://docs.google.com/document/d/1TW76NdhaByY3TibfdK-dykKnp2OXboshTkvcixDE8rU/edit?usp=sharing

Thanks!

**Comment by salimi-my** [comment]
The content for all mentioned pages, excluding blog pages, has been updated.
