### ISSUE TITLE
Update Footer Instagram link

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#331]
Hi team

Please update the Instagram links in footer
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/b76e38d6-2d7e-4f83-8ec2-caf65a586fe4)

Local site (https://zcova.com/)
New Instagram link: https://www.instagram.com/zcova_my/

International site (https://zcova.com/international/)
New Instagram link: https://www.instagram.com/zcova_au/

cc @kimberlyljw

**Comment by salimi-my** [comment]
Updated.
