### ISSUE TITLE
Local site: CNY+Valentine homepage banner [LIVE by 15th Jan]

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#332]
Please update 2x banners below:
<img width="1508" alt="Screenshot 2024-01-11 at 4 33 47 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/fc554d41-c140-461c-ac11-b27e3c88dd47">

<img width="1503" alt="Screenshot 2024-01-11 at 4 35 42 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/79069ce7-319b-4c3c-9c98-cae01d1e9748">

Working file: https://drive.google.com/drive/folders/1vySDGBSs9pjYmpnZYAUK6TC868s35-Ja

CTA button > messenger

**Comment by salimi-my** [comment]
Google Drive access is denied. Please open access to public.
