### ISSUE TITLE
International Website - About Us Location Update 

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#334]
Hi Team,

Kindly update the "Our Location" section of the ["About Us" page](https://zcova.com/international/about) as pictured : 
![Screenshot 2024-01-15 at 12 10 55](https://github.com/logicwisesoftware/zcova/assets/156041223/f6599d13-c4dc-4c59-bc14-bff58e12bc97)

Replace the existing text with: 
We are always reachable online but to provide you with an extensive 360-degree ZCOVA Experience, we’ve extended our Galeria to Adelaide. Our friendly ZCOVA Curators will be there to provide you with a red carpet service while buying your ideal fine jewellery piece during your visit to our Galeria.

Remove all the existing location images & hyperlinks; replace with:
1. this image 
https://drive.google.com/file/d/1u13sapX4lk7ff41HK0F6i_HSqh9ChGoc/view
2. this hyperlink 
https://www.google.com/maps/place/ZCOVA+Adelaide/@-34.9172862,138.6231049,15z/data=!4m6!3m5!1s0x6ab0c9f226133c23:0x20e2de78125e13a9!8m2!3d-34.9172862!4d138.6231049!16s%2Fg%2F11vph179hd?entry=tts

Please centre the hyperlinked image. 

Thank you!

**Comment by salimi-my** [comment]
Updated.
