### ISSUE TITLE
MY Contact Details Update

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#337]
Hi team please update Ipoh details as follow ([contact page](https://zcova.com/contact))

F-3A, First Floor, Travelodge Ipoh, Jalan Raja Dihilir, 30350 Ipoh, Perak

TEL: (+60) 5241 1565

Showroom Operating Hours:
Weekday: 9:30am-6:30pm (Monday closed)
Saturday: 9:30am-5pm
Sunday: 9:30am-5pm
*Strictly by appointment only

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/4512c1f5-e683-435f-8818-47d063cff760)

**Comment by logicwisesoftware** [comment]
Updated.

<img width="980" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/333b7a89-c420-4e4a-8a9a-6f0a9c6d9cee">
