### ISSUE TITLE
Content Update - "About Us" page

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#338]
Hi Team,

Kindly assist to update this section of the "[About Us](https://zcova.com/about)" page as pictured below:

![image](https://github.com/logicwisesoftware/zcova/assets/156041223/094ace65-3218-4e95-8c86-0ad57a795d5b)

Changes needed: 

1. Replace the 0% icon to the Diamond icon attached here 
![About Us-04](https://github.com/logicwisesoftware/zcova/assets/156041223/87f64a95-678b-4800-90ed-ab4f6b27e5e6)

2. Replace the text "No-commission policy" to ">150, 000 Diamond Inventory"

3. Replace the text "We aim to deliver the best selection of certified diamonds & gemstones along with expert guidance and education by our In-House Gemologist. Our jewellery Curators work on a no-commissions policy, so there’s no pressure in making purchases." to "We aim to deliver the best selection of certified diamonds & gemstones along with expert guidance and education by our In-House Gemologist. Once you’ve decided on your forever piece, our Master Craftsmen pour their immense experience into every tiny detail."

Please apply the changes to both the Malaysia & International site.

Thank you!

**Comment by salimi-my** [comment]
Updated
