### ISSUE TITLE
Hide 916 Gold page

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#339]
Hi team 

Please hide this [916 Gold page](https://zcova.com/916-gold) from website
to remove the link in fine jewellery dropdown
<img width="1050" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/142577916/3532e55b-f124-4e4d-8ae1-8762bf3178c3">

thank you

**Comment by salimi-my** [comment]
Updated.

**Comment by Shellytsy** [comment]
Hi Salimi, thanks for the update, please help hide the entire page from being viewable by visitors, thank you

**Comment by salimi-my** [comment]
Updated.
