### ISSUE TITLE
Homepage dropdown

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#34]
[![Screenshot_2022-06-07_07-58-04.png](https://mrkr.io/s/629f050c4dce011acb20bdae/2)](https://mrkr.io/s/629f050c4dce011acb20bdae/0)

- Description standardize body size 18px
- When press button, change image
- First dropdown expanded by default

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629f050c4dce011acb20bdc6_254f04ca99ad28f5?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629f050c4dce011acb20bdc6_254f04ca99ad28f5)

**Console:** [⚠️  20 warnings ℹ️  1 info ](https://app.marker.io/i/629f050c4dce011acb20bdc6_254f04ca99ad28f5?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629f050c4dce011acb20bdc6_254f04ca99ad28f5) - This issue was marked as resolved in Marker.io.
