### ISSUE TITLE
Direct home page buttons' to contact us page

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#340]
Change the below banner buttons to direct to Contact Us page
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/4028b5b1-16b9-488f-996d-69561b2db20f)
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/28f4524b-7633-49df-9d8c-c6797ebf3143)
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/f619cdc4-2715-482f-98a2-c20807a02a83)
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/52cca232-41ee-40b1-96e5-3f471380fec3)
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/60823627-d75b-4458-8a74-d255b2867e38)

**Comment by salimi-my** [comment]
Updated.
