### ISSUE TITLE
Add Pop Up for our promo

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#342]
Pop up will appear when people land on our website.

Attached sample visual where the button should be.
https://drive.google.com/drive/folders/1DgxuH2bB895BHoj7Ze63yeyozvp7em7t

Button to lead to Contact Us page.

**Comment by giselle724** [comment]
Hi,

Replace the first pop up with the new one. The pop up will only disappear
when user clicks on it (either close it or click on CTA button).

The second pop up can remain.

Thanks.

**Comment by giselle724** [comment]
Sorry to summarize.

1st pop up (replace the current with new one): immediately appear when user
land on our page.

2nd pop up: in 120seconds. (Remain as per)

**Comment by salimi-my** [comment]
Updated.
