### ISSUE TITLE
Redirection & Tagging Update 

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#343]
Hi Team,

Kindly assist with the following items : 

1. Redirection of the corresponding collection pages for International site 

Most international pages redirect to homepage even if it's a collection page; kindly assist to amend 

2. Add a self-reference canonical tag to every page for both local & international

Kindly refer to samples as below : 

![WhatsApp Image 2024-02-08 at 16 05 59](https://github.com/logicwisesoftware/zcova/assets/156041223/7533f2eb-a4e9-4f87-b6ad-8ae38defddd0)
![WhatsApp Image 2024-02-08 at 16 06 14](https://github.com/logicwisesoftware/zcova/assets/156041223/795ebf27-7a8c-44bb-bb6f-a943e94e0309)
![image](https://github.com/logicwisesoftware/zcova/assets/156041223/de31db5e-dfbd-45e4-a208-3b89d8334fe5)

Thank you!

**Comment by salimi-my** [comment]
Updated.
