### ISSUE TITLE
New Landing Page Template

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#345]
Hi team

Need your help to build a landing page template for our future promotions use.

**Page sections:**
1. Header (linked to [zcova.com](https://zcova.com/))
2. Banner
3. Page headlines & description
4. CTA button (linked to [zcova.com/contact](https://zcova.com/contact))
9. T&Cs
5. Why Choose ZCOVA?
6. Customer Reviews
7. Media
8. Our Location
10. Contact Us button (linked to [zcova.com/contact](https://zcova.com/contact))

**Note:**
1. None of the images or texts will be clickable except Header and the 2 CTA Buttons.
2. This page will serve a standalone landing page.
3. We will create new landing page with this template for new promotions, which would be redirected from:
- Homepage banner
- Google ads (SEM, GDN)

Here are the layout design for your reference: 
1. [Desktop](https://drive.google.com/file/d/1y8cKvOKRNjP0BSVRQ7Dplxg0YQVv-we2/view?usp=sharing)
2. [Mobile](https://drive.google.com/file/d/1y5YPsF8WOC__hKyKcj33VD-jG0O6YJC-/view?usp=sharing)

Why Choose ZCOVA visual assets can be found [here](https://drive.google.com/drive/folders/1EE0VQCTFeD04Wg72OEpKY10RLHn63-IX?usp=sharing)

Please share over the page preview when it's done.
We will share over the details for March promo soon.

Let me know if clarification needed. Thank you :)

cc @giselle724

**Comment by salimi-my** [comment]
The promotion landing page has been completed. If there are any adjustments needed, please reopen the issue and provide feedback. Thank you.

**Comment by Shellytsy** [comment]
Hi team, please remove all floating plug ins from the current promo landing page, and dont include in future landing pages as well
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/661ba592-bc79-4ba7-912c-6ab5f96ab22d)

Thank you

**Comment by salimi-my** [comment]
Updated.
