### ISSUE TITLE
Appointment Booking Function - International Site

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#346]
Hi Team,

As discussed, kindly enable the appointment booking function on the International Site only. 

Do advise if any assets/other details are required from us. 

Thank you!

**Comment by kimberlyljw** [comment]
Hi Team, may I know what is the progress on this? 

Would like to get confirmation on the timeline for this to go-live as well as I understand that the function was already available on the backend. 

Kindly update when possible, thanks

**Comment by kimberlyljw** [comment]
Hi Team, checking in on this ticket again. 

Could we get an update as to where we are on this? Are there any issues that's causing a lag in the process?

Kindly update, thanks

**Comment by logicwisesoftware** [comment]
Create appointment btn at the front end

**Comment by giselle724** [comment]
may I know where is the appointment button?

**Comment by logicwisesoftware** [comment]
Can we put the btn at Contact Us page?

**Comment by giselle724** [comment]
Can you put throughout the page?
<img width="372" alt="Screenshot 2024-04-09 at 4 18 47 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/9b31a01b-e85d-480a-a3ff-c9908cd07873">

**Comment by salimi-my** [comment]
Book appointment button has been added to header, marking this issue as completed. Should any further adjustments or modifications be required, please do not hesitate to create a new issue.
