### ISSUE TITLE
March promotion to be updated on Homepage banner and Promotional page

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#347]
March promo
1. Homepage banner- to upload new promo banner
- Working files: https://drive.google.com/drive/folders/1FLjINTwxUViISM8g_H9ejTfkqMjed7-Z?usp=sharing
- Samples and logo: https://drive.google.com/drive/folders/1EkWRe2m1LkBDcm2q6TZlq28Wp6NRjIgX?usp=sharing
- Button in the banner: Find out more (lead to below promotional page)

2. Promotional page
- Use the newly created template. Only change the promotion details
- Mockup and T&Cs here: https://docs.google.com/document/d/1Ih00fhwjCWUA_sgyIbeBzM6vzEM3lVo8Uj0u-XXrE0o/edit
- Asset: https://drive.google.com/drive/folders/1Ek3mLRaSxilM9giOj0FZD-mCLWTZPciD?usp=sharing

All the above needs to be live by 1 Mar.

**Comment by giselle724** [comment]
March promotional page URL: /MarchPromo24

**Comment by salimi-my** [comment]
The promotion landing page has been completed. If there are any adjustments needed, please reopen the issue and provide feedback. Thank you.

**Comment by giselle724** [comment]
Only live 1 Mar. Our promo is not ready yet

**Comment by Shellytsy** [comment]
Hi team please fix the location image linking ASAP, thank you
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/47233589-9245-4dad-aa46-ce7b768fd04a)

**Comment by salimi-my** [comment]
Images fixed.
