### ISSUE TITLE
Referral Miniprogram - International Site 

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#348]
Hi Team,

Kindly assist to resolve the following issue : 

- Initially when logged in, user is unable to see any customer details (this is correct & not an issue at the moment) 
![Screenshot 2024-02-27 at 12 21 42 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/c5db1b54-0e2d-4650-b43e-1bcac6c1fac6)

- When clicking on any of the blue text/headers, data populates in the table below 
![Screenshot 2024-02-27 at 12 23 41 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/b452ed85-5cc2-456a-8b5f-95c9f403ae40)

- Unsure if data there is actually ZCOVA's current customer database or if it's mock data, but it should not be showing 
![Screenshot 2024-02-27 at 12 24 57 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/f07c5f6f-b1b3-4439-931f-729f9fc7d4bb)

- When clicking on "Reset", populated data disappears & it goes back to the original screen (correct as well) 
![Screenshot 2024-02-27 at 12 26 24 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/c7cc7769-53ab-4602-8b4f-4fbf364ade83)

Please amend accordingly. 

Additionally, what does the status "Enabled" mean in the table? What are the other labels besides "Enabled"?  

Thank you!

**Comment by salimi-my** [comment]
The sorting bug has been successfully resolved. In response to your inquiry about the status column, it indicates the access status of the customer's account. Administrators have the ability to enable or disable a customer's account. When disabled, the customer is unable to sign in or access their account. Let me know if you want to hide the status column.

**Comment by kimberlyljw** [comment]
Hi @salimi-my 

Thanks for resolving the issue promptly. 

Kindly proceed with hiding the status column as well.

Thank you!

**Comment by salimi-my** [comment]
Status column hidden.
