### ISSUE TITLE
Jan and Feb - Content Layerings 

### ISSUE THREAD

**Issue by aprilcheong123** [logicwisesoftware/zcova#349]
Hi, please help to make the changes for the content on these drives,

for virtual ring try-on page, please create a landing page on the main site. Suggested url: http://zcova.com/virtual-try-on-rings

Jan - https://drive.google.com/drive/folders/1yjirbI-qLo9SKidwkNMBwAeoHR2vMw3Z
Feb - https://drive.google.com/drive/folders/1DCoFcZqC2tHBRyQQVch08Y1-cCqAStp4

Please let us know once it's implemented, thanks!

**Comment by salimi-my** [comment]
Requested content changes for all pages on this drive directory [https://drive.google.com/drive/folders/1yjirbI-qLo9SKidwkNMBwAeoHR2vMw3Z](https://drive.google.com/drive/folders/1yjirbI-qLo9SKidwkNMBwAeoHR2vMw3Z) has been updated.

Requested content changes for mined diamond page on this drive directory [https://drive.google.com/drive/folders/1DCoFcZqC2tHBRyQQVch08Y1-cCqAStp4](https://drive.google.com/drive/folders/1DCoFcZqC2tHBRyQQVch08Y1-cCqAStp4) has also been updated.

For virtual ring try-on page, please provide all the images assets and design mockup if available.

There is lack of context & explanation for the Copy of Lab-Grown vs. Natural Diamonds. Could you provide more details about the specific changes you are looking for? Also, the URL displayed is …/lab-grown-vs-natural-diamonds-differences. Please do provide full URL.

**Comment by giselle724** [comment]
URL display: www.zcova.com/lab-grown-vs-natural-diamonds-differences

Ignore the virtual try-on-page for now.

**Comment by logicwisesoftware** [comment]
Kindly reopen if this needed to be attended. Thanks
