### ISSUE TITLE
Homepage dropdown content

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#35]
[![Screenshot_2022-06-07_08-12-01.png](https://mrkr.io/s/629f08518e54436d1e4d53cf/2)](https://mrkr.io/s/629f08518e54436d1e4d53cf/0)

Picture 1: https://drive.google.com/open?id=1n5Gk8jsO42ENlok8pE6mLcy6g777876x&authuser=eewern%40zcova.com&usp=drive_fs
Title 1: Honesty & Expertise
Description 1: We are dedicated to providing you with honest and knowledgeable offerings for a confident purchase, no matter your price range.
Button 1: Book A Slot ( link to https://blog.zcova.com/2020/04/15/zcova-virtual-consultation )

Picture 2: https://drive.google.com/open?id=1n4lF86mquFPHd4uwXjswORNwiLg2is2h&authuser=eewern%40zcova.com&usp=drive_fs
Title 2: ZCOVA Journey
Description 2: Your very own personal Curator will be by your side every step of the way to ensure first-class service befitting your once-in-a-lifetime occasion.
Button 2: Know More ( link to https://zcova.com/customer-care )

Picture 3: https://drive.google.com/open?id=1n4H-UB6ZJRNdIam8zVGfU49Kf3vMxLTK&authuser=eewern%40zcova.com&usp=drive_fs
Title 3: Master Craftsmanship
Description 3: With 40 years of expertise, every detail is taken into account significantly during the jewellery crafting process so you can have peace of mind.
Button 3: Shop Engagement Ring ( link to https://zcova.com/engagement-ring )

Picture 4: https://drive.google.com/open?id=1n7mqMjxq1P8MaSEBVngooTYX7DhMfPyn&authuser=eewern%40zcova.com&usp=drive_fs
Title 4: Lifetime Warranty
Description 4: Our services are all designed to evoke your happiness. Hence we put forward our brand to warrant your purchase from ZCOVA.
Button 4: Know More ( link to https://zcova.com/warranty )

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629f08518e54436d1e4d53f1_7f0fb46afdbc9c7d?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629f08518e54436d1e4d53f1_7f0fb46afdbc9c7d)

**Console:** [⚠️  30 warnings ℹ️  1 info ](https://app.marker.io/i/629f08518e54436d1e4d53f1_7f0fb46afdbc9c7d?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629f08518e54436d1e4d53f1_7f0fb46afdbc9c7d) - **Isabel (isabel@zcova.com)** commented via Marker.io:

> Button 2 link to https://zcova.com/our-promises

[Reply here](https://app.marker.io/i/629f08518e54436d1e4d53f1_7f0fb46afdbc9c7d)

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629f08518e54436d1e4d53f1_7f0fb46afdbc9c7d) - This issue was marked as resolved in Marker.io.
