### ISSUE TITLE
Remove first pop up and replace with new promo [live 1 Mar]

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#350]
Remove the below pop up:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/ceb5a6c0-ebf6-4f2b-a2c3-ff3ff72cfb33)

Replace with new pop up:
https://drive.google.com/file/d/1F2PzLRONTObw_3J2M2vCVazFY29noCvM/view?usp=sharing

Only live 1 Mar.

Thanks

**Comment by giselle724** [comment]
New pop up:
https://drive.google.com/file/d/1F2PzLRONTObw_3J2M2vCVazFY29noCvM/view?usp=sharing

Use the same CTA as the old pop up: Book an appointment with us now!

**Comment by salimi-my** [comment]
Image replaced.

**Comment by giselle724** [comment]
Only live 1 Mar. Our promo is not ready yet.

**Comment by giselle724** [comment]
The promotional page, showroom locations not loading
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/0aa58f94-bedf-4596-91cf-1d40ae6d3063)

**Comment by salimi-my** [comment]
Images fixed.
