### ISSUE TITLE
Remove Feb promo banners (1 Mar)

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#351]
Remove the below banners on 1 Mar
<img width="1641" alt="Screenshot 2024-02-29 at 4 45 39 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/9a0d4acb-3840-44b4-ae0d-3715018a3003">
<img width="1649" alt="Screenshot 2024-02-29 at 4 45 31 PM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/c327fb9c-7902-4f09-8b47-f49f5ee50597">

**Comment by salimi-my** [comment]
Updated.
