### ISSUE TITLE
Referral Site Password Reset Function - International Site 

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#353]
Hi Team,

Kindly assist to update to include a password reset function if the below error occurs : 

<img width="520" alt="Screenshot 2024-03-01 at 10 15 03 AM" src="https://github.com/logicwisesoftware/zcova/assets/156041223/db6d5c70-b6b4-4b66-b764-e037787fc22e">

Thank you!

**Comment by giselle724** [comment]
Hi, can we get an update on this please?

**Comment by salimi-my** [comment]
Referral account reset password request feature has been implemented.
