### ISSUE TITLE
Banner Typo - Malaysia Site 

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#356]
Hi Team,

Kindly revise the typo from "March into Sparker" to "March into Sparkle"

<img width="925" alt="Screenshot 2024-03-08 at 10 48 25 AM" src="https://github.com/logicwisesoftware/zcova/assets/156041223/643c3aad-0b09-4f85-8108-d088096f6d2b">

Thank you

**Comment by logicwisesoftware** [comment]
Ok it's updated.
