### ISSUE TITLE
Promo T&C Landing Page Update - Malaysia Site

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#358]
Hi Team,

Kindly update the promo T&C landing page (https://zcova.com/marchpromo24) with the text from the attached file.

Thank you!

[March '24 Promo T&C.pdf](https://github.com/logicwisesoftware/zcova/files/14566580/March.24.Promo.T.C.pdf)

**Comment by logicwisesoftware** [comment]
Created a T&C link under the button since it's quite lengthy.

<img width="628" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/c9b7e988-4db0-45e3-ba98-a9b1636b7135">
