### ISSUE TITLE
Promo Landing Page - International Site

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#359]
Hi Team,

Kindly assist to create a new landing page on the international site for the ongoing promotions; similar to what was created for the Malaysia site : https://zcova.com/marchpromo24

Kindly find attached the visual banner for the promo landing page. 

Kindly use the copy as follows for the promo landing page : 
![Screenshot 2024-03-12 at 3 57 18 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/4976f099-00aa-41aa-82de-ae219b55235e)
Big Heading -  Our Australia Opening Promo
Smaller Subtitle - Don't miss these exclusive deals for maximum savings!
CTA Button - Get Now (should redirect to the international site's contact form - https://zcova.com/international/contact )
T&C - Read Terms & Conditions here (should redirect to the pdf file attached) 

Additionally, kindly replace the CTA button as pictured on the website's home page:
![Screenshot 2024-03-12 at 3 51 30 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/eed0f5dc-e04f-4e27-ad38-980a05b1f425)
New CTA Button : "Find Out More"
The button should redirect to the newly created promo landing page 

Thank you!
[AU Opening Promo T&C.pdf](https://github.com/logicwisesoftware/zcova/files/14569113/AU.Opening.Promo.T.C.pdf)
![AU_1680x 770px](https://github.com/logicwisesoftware/zcova/assets/156041223/8553316d-7265-4b6a-8abe-7312d3b21977)

**Comment by salimi-my** [comment]
The promotion landing page for international site has been created. Here is the page URL [https://zcova.com/international/au-opening-promo](https://zcova.com/international/au-opening-promo).

As the URL path for the landing page was not clearly stated, /au-opening-promo has been selected temporarily. If any changes are required, please provide the updated URL path.

It is suggested that the "Our Location" section should be updated, as the current location images represent Malaysia's Galeria.

Additionally, please provide a visual banner image specifically tailored for the mobile layout. In the absence of a designated mobile image, the current image will be utilized as both the desktop and mobile banner.

The new promotion landing page has been successfully deployed, marking this issue as completed. If any adjustments or amendments are necessary, please feel free to create a new issue.
