### ISSUE TITLE
Promo Landing Page Amendments - International Site

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#361]
Hi Team,

Thanks for the work & comments on Closed Ticket #359. Have reviewed & noticed as follows: 

1. Kindly update the T&C doc to a new pdf as attached
2. Kindly amend the locations from the Malaysia Galerias to the Australian one found here (https://zcova.com/international/contact)
![Screenshot 2024-03-14 at 9 50 43 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/8a053690-ca49-41ec-96a5-f3f90b01b675)
Use the copy : 
Header : Our Location
Text : We are always reachable online but to provide you with an extensive 360-degree ZCOVA Experience, we’ve extended our Galeria to Adelaide. Our friendly ZCOVA Curators will be there to provide you with a red carpet service while buying your ideal fine jewellery piece during your visit.

[AU Opening Promo T&C (1).pdf](https://github.com/logicwisesoftware/zcova/files/14596216/AU.Opening.Promo.T.C.1.pdf)

Thanks!

**Comment by salimi-my** [comment]
Page updated.
