### ISSUE TITLE
Change headline for Customise ring section

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#362]
Please change the below headline from "Your Engagement Ring, Your Way" to "Customised Engagement Rings, Wedding Rings & Jewellery"

![image](https://github.com/logicwisesoftware/zcova/assets/144078599/d0f4bb31-50cf-439e-925d-901dcdbf04db)

**Comment by logicwisesoftware** [comment]
Updated.

<img width="1270" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/3ded424f-7839-4be7-85cf-b8fe03fa1fa6">
