### ISSUE TITLE
IOI Retail Landing Page

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#363]
Hi team, please prepare a landing page with the following details

Page url: zcova.com/zcova-ioi-city-mall

Desktop mockup [link](https://drive.google.com/open?id=11ZE1HehLFSkremZx7bPbZJXn2sbMMU3t&usp=drive_fs)
Mobile mockup [link](https://drive.google.com/open?id=11WCfOpREa6EFe4wVX4Ao7SrCkedojqiO&usp=drive_fs)
Images [link](https://drive.google.com/drive/folders/1XlKZkx92rd74jz0x2THlv3O2dq4kCcmQ?usp=sharing)

Note: all navigation menu and inpage image links should be clickable, floating buttons are also applicable.

This page should be live this Friday 22 March 2024.
Landing page copy content will be shared when ready, meantime please build the mock page. 

**Homepage banner**

Desktop banner [link](https://drive.google.com/open?id=1xgqAAqjKI-v8wsSynR8cHHMM9LY4qRmO&usp=drive_fs)
Mobile banner [link](https://drive.google.com/open?id=1n4LGMRIWkBgPDf2EIKfgFyBCYZhNLzME&usp=drive_fs)

Headline: ZCOVA Is Finally Going Retail
Subhead: Celebrate Life Your Way at ZCOVA's 1st Ever Retail Store IOI City Mall Putrajaya.
CTA: Learn More (link: zcova.com/zcova-ioi-city-mall)

Note: 
- to add this banner to MY site only
- add as 2nd slide after promo
- only live this banner when landing page is live

Thank you

**Comment by Shellytsy** [comment]
Hi team, updated docs here 

Content [link](https://docs.google.com/document/d/143wGd79hIDA8pH3SWrTvLTWBi9T4zUw7I35d26KHI3k/edit?usp=sharing)

Final desktop mockup [link](https://drive.google.com/open?id=128mlwhgMkFBCPlLe5IlFh_aJ3VQTzE5U&usp=drive_fs)
Final mobile mockup [link](https://drive.google.com/open?id=12BwSn9I6XbP-My09P0nSLf3gKau2Cho9&usp=drive_fs)

Do note that product photos are updated, you may find in the same link.
 
 
Please follow the spacing and styling:

Dark text colour: #002a3a
Light text colour: white
Highlighted beige text colour: #d6cbab

**Desktop**
Full width text box max width: 820px
Section padding: 42px

**Mobile**
Margin: 30px
Section padding: 30px

Let us know if you need additional info, thank you very much

**Comment by salimi-my** [comment]
Kindly provide map direction icons.

**Comment by Shellytsy** [comment]
Updated in the same folder

**Comment by salimi-my** [comment]
Page updated.

**Comment by Shellytsy** [comment]
Headline alignment and one of the body text margin is off in mobile view, please update according to mockup 
![IMG_1571](https://github.com/logicwisesoftware/zcova/assets/142577916/fed7a572-64a0-46ae-b946-d0214191830a)
![IMG_1572](https://github.com/logicwisesoftware/zcova/assets/142577916/66e578ef-57cf-4b22-ae9a-688063a3a8bc)

**Comment by salimi-my** [comment]
Page updated.
