### ISSUE TITLE
Promo Page Content Update - International Site

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#364]
Hi Team,

Kindly replace the T&C doc used in the landing page (https://zcova.com/international/au-opening-promo) with the new PDF as attached; everything else can be maintained as is

Thank you
[AU Opening Promo T&C (2).pdf](https://github.com/logicwisesoftware/zcova/files/14663031/AU.Opening.Promo.T.C.2.pdf)

**Comment by salimi-my** [comment]
Updated.
