### ISSUE TITLE
Website Pop Up for new promo (LIVE BY 21 MAR)

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#365]
Please add a pop up for the below promo:
https://drive.google.com/drive/folders/1YIJ94kKuGPuSu7gkhSf3SGrtwSjH8TUK?usp=sharing

Claim Now button to lead to contact form

**Comment by salimi-my** [comment]
Kindly provide image without button.

**Comment by salimi-my** [comment]
Updated.
