### ISSUE TITLE
April Promo website updates [ONLY LIVE 1 APRIL]

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#367]
**REMOVE BY 31 MAR 1159PM**

1. Remove the below banner and pop up **on 31 Mar**
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/0f640348-ea4c-4b0c-91f7-907b345a64b9)
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/771034d4-b562-4388-8a62-ae0497a22113)

**[EVERYTHING BELOW ONLY LIVE 1 APRIL]**

**1. Homepage banner**
Banner: https://drive.google.com/drive/folders/1ajUa7hm3KbWBV1G560Gbfet70rUbPdoF?usp=sharing 
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/efe6540c-15cc-4cd7-b4f9-107fa59c35e1)
Headline: Free 18k Setting with Diamond Purchase
Sub copy: Check out how you can maximise your savings!
CTA: Find out more (lead to promo page)

**2. Promo page (URL: https://zcova.com/FreeSettingAprPromo )**
Banner: https://drive.google.com/drive/folders/1ai1wiCUPBCgBSo5bjcbqhWfLotgns-AU?usp=sharing
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/86d07075-4aea-40ef-af39-dfba1272bda8)
Headline: Free 18k Setting with Diamond Purchase
Sub copy: Check out how you can maximise your savings!
CTA: Get Now (lead to Contact Us page)
Read T&Cs here (hyperlink below pdf)
[April '24 Promo T&C.pdf](https://github.com/logicwisesoftware/zcova/files/14770376/April.24.Promo.T.C.pdf)

**Comment by giselle724** [comment]
Promo page use the existing template. Thanks

**Comment by giselle724** [comment]
Sorry T&Cs please use this instead.
[April '24 Promo T&C.pdf](https://github.com/logicwisesoftware/zcova/files/14799683/April.24.Promo.T.C.pdf)

**Comment by salimi-my** [comment]
Please provide promo page banner image without the button.

**Comment by giselle724** [comment]
We have some minor changes to our promotion.
1. DO NOT REMOVE THE BELOW BANNER
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/a60ad623-f7aa-4afc-9b32-213559c93150)

2. Please update the T&Cs on the Mar promo page. Under "Read Terms and Conditions Here"
[March '24 Promo T&C.pdf](https://github.com/logicwisesoftware/zcova/files/14810465/March.24.Promo.T.C.pdf)

3. Only remove the 5% setting pop up
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/45c064a9-b5f0-4a38-9ba1-7325a8b1dfb1)

4. The NEW promotions as per brief above. Not change.
[EVERYTHING BELOW ONLY LIVE 1 APRIL]

1. Homepage banner
Banner: https://drive.google.com/drive/folders/1ajUa7hm3KbWBV1G560Gbfet70rUbPdoF?usp=sharing
image
Headline: Free 18k Setting with Diamond Purchase
Sub copy: Check out how you can maximise your savings!
CTA: Find out more (lead to promo page)

2. Promo page (URL: https://zcova.com/FreeSettingAprPromo )
Banner: https://drive.google.com/drive/folders/1ai1wiCUPBCgBSo5bjcbqhWfLotgns-AU?usp=sharing
image
Headline: Free 18k Setting with Diamond Purchase
Sub copy: Check out how you can maximise your savings!
CTA: Get Now (lead to Contact Us page)
Read T&Cs here (hyperlink below pdf)
[April '24 Promo T&C.pdf](https://github.com/logicwisesoftware/zcova/files/14810469/April.24.Promo.T.C.pdf)

**Comment by giselle724** [comment]
Please help to update the t&cs to the below:
[April '24 Promo T&C.pdf](https://github.com/logicwisesoftware/zcova/files/14819542/April.24.Promo.T.C.pdf)

**Comment by salimi-my** [comment]
The 5% off promo pop up has been removed and the T&Cs PDF file has been updated.

The new promotional banner image for the homepage carousel has been officially added, and the corresponding landing page for the promotion has been successfully launched and is now live.

The requested promo page banner image without a button has not been provided. As a result, the current banner image with a button is being used for the promo landing page.

The new promotional banner image and promotion landing page has been successfully deployed, marking this issue as completed. Should any further adjustments or modifications be required, please do not hesitate to create a new issue.
