### ISSUE TITLE
IOI direction links 

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#368]
Hi team please add these links to the store location links in [IOI landing page](https://zcova.com/zcova-ioi-city-mall), thank you

![image](https://github.com/logicwisesoftware/zcova/assets/142577916/4ed787ff-642d-4291-ab35-274589c31666)

Waze: https://www.waze.com/en/live-map/directions/ioi-city-mall-lebuh-irc-putrajaya?place=w.66650142.666566953.5702458
Google map: https://maps.app.goo.gl/83naiWDDip5MKugy6
Apple map: https://maps.apple.com/?address=Lebuh%20IRC,%20IOI%20Resort%20City,%2062502%20Putrajaya,%20Selangor,%20Malaysia&auid=2243520326302053067&ll=2.970185,101.713527&lsp=9902&q=IOI%20City%20Mall&t=m

**Comment by salimi-my** [comment]
Can check and confirm the google map link? It shows the navigation direction from ZCOVA Kota Damansara instead of the exact location only.

**Comment by Shellytsy** [comment]
Oops, please use this (https://maps.app.goo.gl/kF6grVg8zpzDr5Rg6) instead, thanks for checking!

**Comment by salimi-my** [comment]
Store location links added.
