### ISSUE TITLE
Homepage Diamond section

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#37]
[![Screenshot_2022-06-07_08-31-12.png](https://mrkr.io/s/629f0cd07e880051bb186ed6/2)](https://mrkr.io/s/629f0cd07e880051bb186ed6/0)

- Image change
- Add in text

Title: Shop Wedding Rings
Image: https://drive.google.com/open?id=1n7l7yyMn2zM4Sh6SryizN1Mimb0BplSa&authuser=eewern%40zcova.com&usp=drive_fs
Link to: https://zcova.com/fine-jewellery/wedding-bands

Title: Guaranteed Brilliant Diamonds
Body: You asked for a diamond with the best cut and brilliance, we found you the solution! ZCOVA offers Dual-Certification to guarantee your diamond’s brilliance. 
Image: https://drive.google.com/open?id=1n7_VuSGJ0-tbddQm0DTMU8OicgFfeyd9&authuser=eewern%40zcova.com&usp=drive_fs
Button: Shop Diamonds ( link to https://zcova.com/diamond )

Title: Propose with ZCOVA Signatures
Body: Our range of unique engagement rings are made by our in-house jewellery designers with dedication and creativity.
Image: https://drive.google.com/open?id=1n6I2Dzc5eInSaeFgXSUCpwT_g8lIXAcT&authuser=eewern%40zcova.com&usp=drive_fs
Button: Shop Now ( link to https://zcova.com/engagement-ring -> filter by Signature Engagement Rings)

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629f0cd07e880051bb186f12_113e1c4e5fa4063b?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629f0cd07e880051bb186f12_113e1c4e5fa4063b)

**Console:** [⚠️  56 warnings ℹ️  1 info ](https://app.marker.io/i/629f0cd07e880051bb186f12_113e1c4e5fa4063b?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629f0cd07e880051bb186f12_113e1c4e5fa4063b) - This issue was marked as resolved in Marker.io.
