### ISSUE TITLE
IOI Landing Page Visual Update

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#371]
Hi team, please update [IOI landing page](https://zcova.com/zcova-ioi-city-mall) visuals as follow:

[Homepage banner desktop](https://drive.google.com/open?id=15jVyJsPB72crQ0xjgngXwKSlVMdA_4f0&usp=drive_fs)
[Homepage banner mobile](https://drive.google.com/open?id=1NSh9o33lZYuJY7i3KuWYnrq7TzcWrWR2&usp=drive_fs)
[Landing page banner desktop](https://drive.google.com/open?id=15jVyJsPB72crQ0xjgngXwKSlVMdA_4f0&usp=drive_fs)
[Landing page banner mobile](https://drive.google.com/open?id=1NSh9o33lZYuJY7i3KuWYnrq7TzcWrWR2&usp=drive_fs)
For showroom image, use the slideshow if possible (if able to compress and not drag loading speed)
[gif](https://drive.google.com/open?id=1nUzwGZr1cWsbltgZUXeogenmcC7ncPmp&usp=drive_fs) | [mp4](https://drive.google.com/open?id=195Fd2th71RsxJocT-xtS6WsDYpk9FcTD&usp=drive_fs)
If not, we can use [static](https://drive.google.com/open?id=15xwBT4-c_Cp0JaP2l7kU9uqq8AY_dg8s&usp=drive_fs)

All the files can be found [here](https://drive.google.com/open?id=1XlKZkx92rd74jz0x2THlv3O2dq4kCcmQ&usp=drive_fs)

Thank you

**Comment by Shellytsy** [comment]
Hi Salimi, we are referring to this
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/a683e00c-385d-4090-b5ce-b4dd5ab95997)

**Comment by salimi-my** [comment]
The homepage & landing page banner images have been updated. For showroom section, I'm able to reduce the file size from 5.35MB to just 695KB by converting it to .webm format.
