### ISSUE TITLE
Extract customer data for natural and lab diamond

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#373]
Could you guys extract customer data (name (first and last name), contact number, email) for those who bought natural diamond and lab diamond respectively? We want to use it for our ad targeting.

**Comment by logicwisesoftware** [comment]
Separated by sheets
<img width="242" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/ea90dc76-320c-426b-86b9-90a02171c092">
[natural-lab-customer-list.xlsx](https://github.com/logicwisesoftware/zcova/files/14914338/natural-lab-customer-list.xlsx)

**Comment by giselle724** [comment]
Can we re-export the list with the phone number country code please? Meta needs it for tracking. Thanks!

**Comment by logicwisesoftware** [comment]
Updated excel with country code.

[mined-and-lab-diamond-customer-list.xlsx](https://github.com/logicwisesoftware/zcova/files/15329357/mined-and-lab-diamond-customer-list.xlsx)
