### ISSUE TITLE
[URGENT] Update promo homepage banners and promotional page 

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#374]
**1. Replace below homepage banners:**
Remove:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/833c6ce2-dd1c-4cc5-8ad1-15ba31009998)
Replace with:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/4464e551-89eb-4e28-8515-7a3549d40f7a)
Visual: https://drive.google.com/drive/folders/1CENcmy7h74UZeboMRVfFY0ZCqD8QGskg

Copy:
Headline- MAXIMISE SAVINGS
Sub headline: Check out how you could save more with our natural diamond promotions!
CTA: Find Out More (land to https://zcova.com/freesettingaprpromo) Change URL to **https://zcova.com/AprNaturalPromo**

**2. Change banner on promotional page: https://zcova.com/AprNaturalPromo**
Remove:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/8e83baf6-3b5b-4531-a5d8-e46bc2292410)
Replace with:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/c4980b15-80b4-4a4d-a284-702f154efc5a)
Visuals: https://drive.google.com/drive/folders/1CDsy-BVAHITjX9edyQdGLolic7LugOpG

Headline- MAXIMISE SAVINGS
Sub headline: Check out how you could save more with our natural diamond promotions!
CTA: Get Now (land to Contact Us page)
T&Cs link: [April Natural Promo T&Cs.pdf](https://github.com/logicwisesoftware/zcova/files/14973440/April.Natural.Promo.T.Cs.pdf)

**3. Replace below homepage banners:**
Remove:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/4535b24d-e489-4421-b014-a3bc2075d77f)
Replace with:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/3683e538-0e6f-4573-8646-eee1d6105be6)
Visuals: https://drive.google.com/drive/folders/1yC_kSrm8Vwq6EaxeiuKM8HNwBrL0vpE7

Copy:
Headline- MAXIMISE SAVINGS
Sub headline: Check out how you could save more with our lab grown diamond promotions!
CTA: Find Out More (land to https://zcova.com/marchpromo24) Change URL to **https://zcova.com/AprLabPromo**

**4. Change banner on promotional page: https://zcova.com/AprLabPromo**
Remove:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/7d36a2d5-2cff-4bbe-9133-d87b4e075cb1)
Replace with:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/ea330924-734c-4a77-927f-cca3e58d44e9)
Visuals: https://drive.google.com/drive/folders/1yDStTZoZXRFEqM6VitiRmRXnUhLVWlmt

Headline- MAXIMISE SAVINGS
Sub headline: Check out how you could save more with our lab grown diamond promotions!
CTA: Get Now (land to Contact Us page)
T&Cs link: [April Lab Promo T&Cs.pdf](https://github.com/logicwisesoftware/zcova/files/14973441/April.Lab.Promo.T.Cs.pdf)

**Comment by salimi-my** [comment]
Promo pages & carousel images updated.
