### ISSUE TITLE
Update Lab grown promo on banners

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#375]
1. Homepage banner:
Remove
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/d871ca5f-bb39-45ee-845e-e22485868332)
Replace with:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/84e0a48e-ec7d-41a1-8215-c19938ee2ad0)
Visual: https://drive.google.com/drive/folders/1zA0ONvOz6twOA-XNW8uqwxxKFA18Iywb

Copy:
Headline: LIMITED TIME DEAL!
Sub headline: Don't miss out this limited time lab grown promo. Only valid until 30 April!
CTA: Find out more (land to https://zcova.com/aprlabpromo)

2. Change banner on https://zcova.com/aprlabpromo
Remove
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/21c163ee-83ec-4629-b208-a7062eca724b)
Replace with:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/93bfbdc6-0bab-4888-bac6-64835058dc69)
Visual: https://drive.google.com/drive/folders/1z6q3U9Ad3tznnQBwD0cUNOjrpWlBOLhS

Headline: LIMITED TIME DEAL!
Sub headline: Don't miss out this limited time lab grown promo. Only valid until 30 April!
CTA: Get Now (Contact Us)
T&Cs link: [20% off Lab April Promo.pdf](https://github.com/logicwisesoftware/zcova/files/14994667/20.off.Lab.April.Promo.pdf)

**Comment by salimi-my** [comment]
Carousel images updated.
