### ISSUE TITLE
International Site - Appointment Booking Page Update 

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#377]
Hi Team, 

Kindly assist to update the Appointment Booking page (https://zcova.com/international/appointment) as follows : 

<img width="893" alt="Screenshot 2024-04-22 at 9 07 01 AM" src="https://github.com/logicwisesoftware/zcova/assets/156041223/6229959f-d88e-42b2-a2a0-ec77046955af">

1. (Refer to above picture) Change title text from "Appointment" to "Book an Appointment Now!"

2. Replace the filler text with the location image & opening hours as pictured here. Kindly ensure that the location pin is still clickable & redirects accordingly. 
![Screenshot 2024-04-22 at 9 20 49 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/6ca75be8-cdb9-41ca-aa32-d6297b6e7b69)

<img width="364" alt="Screenshot 2024-04-22 at 9 06 56 AM" src="https://github.com/logicwisesoftware/zcova/assets/156041223/52dbade6-eaf6-49c2-8b4f-69957830aa2b">

3. (Refer to above picture) Change "Office Location" to "Appointment Type". Change "Select Office Location" to "Select Appointment Type". Change "ZCOVA Adelaide" to "Physical Appointment - Adelaide". Add in another option - "Virtual Appointment - Google Meet".

4. (Refer to above picture) Replace the "Service Type" selection with the checklist & options as pictured here. Kindly ensure that multiple choices can be selected. Add on "Others" & if they check it, pls include a textbox for the user to fill 
![Screenshot 2024-04-22 at 9 28 01 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/4cedb40d-38e2-4070-b759-3a1ee0898ecc)

5. @Fendy, kindly advise when we can have the meeting to discuss the backend of the appointment booking on CMS as there's some things we need to clarify. 

Thank you!

**Comment by kimberlyljw** [comment]
Hi Team,

Is there any update on this ticket?

Thanks

**Comment by kimberlyljw** [comment]
Hi Team,

From the CMS admin side, there's an issue with selecting consultant & booking as pictured below : 
![WhatsApp Image 2024-05-02 at 11 12 42](https://github.com/logicwisesoftware/zcova/assets/156041223/aae1a85b-cd9b-4ed1-933d-f04b6be36711)

From the website front end side, consultation slots can be submitted but if choosing other topics, there's no timeslot option & the booking can't be submitted as shown below : 
![Screenshot 2024-05-02 at 11 16 41 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/12807797-c452-4e42-afea-d55fef127428)
![Screenshot 2024-05-02 at 11 16 33 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/5197c6ab-6742-49c9-a2db-3ef6ff44a4f0)


Kindly assist, thanks

**Comment by salimi-my** [comment]
Updated.

**Comment by logicwisesoftware** [comment]
Would like to ask times selection for the Time Slot. Example 9-10 11-12 1-2 etc

<img width="264" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/41b2ea61-3765-4b29-b7b5-5ca7d4437369">

**Comment by kimberlyljw** [comment]
> Would like to ask times selection for the Time Slot. Example 9-10 11-12 1-2 etc
> 
> <img alt="image" width="264" src="https://private-user-images.githubusercontent.com/106665593/327764902-41b2ea61-3765-4b29-b7b5-5ca7d4437369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjAzMTcsIm5iZiI6MTcxNTIyMDAxNywicGF0aCI6Ii8xMDY2NjU1OTMvMzI3NzY0OTAyLTQxYjJlYTYxLTM3NjUtNGIyOS1iN2I1LTVjYTdkNDQzNzM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwMjAwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTc3ZjYxMWY4YTY1NjcxMDE5Y2Y4MWEyOWI3ODliNTNmZWE5MzQzNTYwZWIxNTQ0OGRhYzZiNDgxNDFhMzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rQ76a4zonC7gRJJv01ju99RtACPyDOqb9b1hbTrGlKg">

Hi Team,

Time slots should be 45mins starting at every hour; meaning = 11am - 11.45am / 12pm - 12.45pm / 1pm - 1.45pm etc. 

Is it possible to have the time selections / time slots follow the opening hours of each day? Or does it have to be fixed every day? 

Example : 
1. Tuesday until Thursday = first time slot is 11am - 11.45am; last time slot is 6pm - 6.45pm
2. Friday & Saturday = first time slot is 9am - 9.45am; last time slow is 4pm - 4.45pm
3. Sunday & Monday = no available timeslots 

Thanks

**Comment by kimberlyljw** [comment]
Additionally, we're able to see "Salimi" on the front-end as pictured below. Kindly amend. 

![Screenshot 2024-05-09 at 9 59 19 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/21d9fba9-7697-4389-9988-8a39dc0846d1)

**Comment by salimi-my** [comment]
Yes, we can do that. I'll change the time slots to follow the opening hours you provide.

**Comment by salimi-my** [comment]
Appointment timeslots updated. If any new adjustments or amendments are necessary, please feel free to create a new issue.
