### ISSUE TITLE
International Site - Opening Hours Update

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#378]
Hi Team,

Kindly assist to update the opening hours on the website as pictured here : 
![Screenshot 2024-04-22 at 9 20 49 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/5ca4dfec-5579-4872-a6d8-3f86b5f89f5f)

Change to the following : 

Monday: Closed
Tuesday: 11am - 7pm
Wednesday: 11am - 7pm
Thursday: 11am - 7pm
Friday: 9am - 5pm
Saturday: 9am - 5pm 
Sunday: Closed

The opening hours should be found on the following pages: 
1. Contact Us (https://zcova.com/international/appointment)
2. Appointment Booking (https://zcova.com/international/contact)

Thank you!

**Comment by logicwisesoftware** [comment]
Updated 

<img width="738" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/634f66b3-88aa-4a1a-bfce-8077227ae952">

**Comment by kimberlyljw** [comment]
Hi Team,

Noticed that the Saturday timing is still 9am - 6pm when it should be 9am - 5pm. Kindly revise.

Thank you

**Comment by salimi-my** [comment]
Opening hours fixed.
