### ISSUE TITLE
Remove details on Price Match Guarantee page

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#379]
Please amend the copy to below in https://zcova.com/price-match-guarantee 
Headline: PRICE MATCH GUARANTEE
Description: We believe that our diamond prices are extremely competitive. If you find a diamond with a comparable price elsewhere, let us know and we will honour the price!

Headline: CONTACT ZCOVA
Description: Have questions or inquiries? Feel free to reach out to our dedicated curators. We're here to assist you.
CTA button: Contact Us

Headline and description for Compact Diamond Prices (remain)

Headline and description for STRESS-FREE BUYING EXPERIENCE (remove entirely)

**Comment by salimi-my** [comment]
Updated.
