### ISSUE TITLE
Homepage Banner Sliders CMS

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#383]
Hi team, as discussed in Whatsapp, please setup a system in cms for homepage banner content update.

Things we would need to edit:
1. headline copy
2. subheadline copy
3. cta button copy
4. cta button link
5. desktop visual upload
6. mobile visual upload
7. sorting banners sequence
8. deleting banner
9. schedule publish time (if possible), otherwise can we save as draft and your side can help to schedule
10. (optional but best to have) preview layout

Stylings should follow the current one, standardised across. Thank you very much

**Comment by salimi-my** [comment]
Carousel management feature has been implemented. Can be checked here [https://zcova.com/admin/carousel/listing](https://zcova.com/admin/carousel/listing). Please do review.

**Comment by Shellytsy** [comment]
Hi Salimi, looks good! Thank you very much
