### ISSUE TITLE
May Promo Page Updates

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#384]
Hi Team,

Kindly assist with the following - 

1. Upload new & replace old Ch'ya homepage slider banner as pictured :
![Screenshot 2024-04-30 at 9 47 22 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/53b5d7ca-4769-40b1-a400-4441d8a6a721)
a. Button should be "Find out more" & leads to promo page 
b. Attached are the visuals here : 
(1280 X 650)
![1280x650px_Website Home Page](https://github.com/logicwisesoftware/zcova/assets/156041223/97ca34a5-68ea-4793-967d-7c3c5783738e)

2. Upload new & replace old Ch'ya promo page details (https://zcova.com/aprlabpromo) as below : 
a. Attached are the visuals here : 
(1680 X 770) 
![1680x 770px_Promo page](https://github.com/logicwisesoftware/zcova/assets/156041223/1ff951cc-9713-4a41-89f8-0dd7713d0d8b)
(1200 X 1200) 
![1200x1200px_Mobile](https://github.com/logicwisesoftware/zcova/assets/156041223/b54f501f-b9ef-433b-8550-a94714eef5d3)

b. Attached are the T&C here : [May Lab Promo T&C.pdf](https://github.com/logicwisesoftware/zcova/files/15156841/May.Lab.Promo.T.C.pdf)
c. Change the page URL from https://zcova.com/aprlabpromo (existing) to https://zcova.com/labpromo (new) 

3. Change the page URL from https://zcova.com/aprnaturalpromo (existing) to https://zcova.com/naturalpromo (new)
a. Change the T&C on this page as attached here : 
[April_May Natural Promo T&Cs.pdf](https://github.com/logicwisesoftware/zcova/files/15159579/April_May.Natural.Promo.T.Cs.pdf)

b. Maintain everything else from this Natural Diamond promo page & banners 

Thank you!

**Comment by salimi-my** [comment]
The homepage carousel images & lab promo page images have been updated. The pdf files for both natural & lab promo page also has been updated. Since mobile image for the homepage carousel was not provided, the mobile image for the lab promo page has been used.
