### ISSUE TITLE
Urgent - Lab-Grown Diamond May Promo Update 

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#385]
Hi Team,

Kindly assist to urgently update the following : 

1. Homepage Carousel 
![Screenshot 2024-05-02 at 10 23 13 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/c615fe2a-da22-4f8b-963f-2190d732cf33)
Update Copy : 
Header - LIMITED TIME DEAL
Body Text - Shop our limited-time offer on stunning lab-grown diamonds 

2. Promo Page
![Screenshot 2024-05-02 at 10 24 19 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/1c2fe2be-8bf4-45ec-bcd5-4a9b1265e778)
Update Copy : 
Header - LIMITED TIME DEAL
Body Text - Don't miss out! Explore our exclusive lab-grown diamond collection with limited-time discounts.

Thank you!

**Comment by salimi-my** [comment]
Updated.
