### ISSUE TITLE
Checkout page to add Enquiry Button

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#386]
Please add "Talk to our Curator" button under the CHECKOUT button.
This applies to every checkout page.

"Talk to our Curator" button to use the below style:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/9a19ac78-4c48-40b1-8127-575fecf82c83)
Land to open messenger button.

Checkout page:
<img width="380" alt="Screenshot 2024-05-02 at 11 24 47 AM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/3d3e7523-2394-4705-ae7f-6691ad31e056">

**Comment by logicwisesoftware** [comment]
Btn added.

However do take note that, the messenger chatbox may not appear immediately at first load of the page bcs it takes time for the plugin to load from FB website. Once the plugin is loaded, clicking at the Send Message btn will show the chatbox instantly.

<img width="528" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/ab482f3e-c969-4b4f-a01d-8ab458f4a345">
