### ISSUE TITLE
Change homepage banner copy

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#387]
Headline: Please change "Maximise saving" to "LOWEST PRICE"
Subheadline: Please change to "We are not the lowest? We have PRICE MATCH GUARANTEE for our natural diamond!"
<img width="1567" alt="Screenshot 2024-05-03 at 10 25 10 AM" src="https://github.com/logicwisesoftware/zcova/assets/144078599/f72beb57-db96-4d86-9537-9438b388f2df">

**Comment by salimi-my** [comment]
Updated.
