### ISSUE TITLE
Website Image Updates - Malaysia

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#390]
Hi Team,

Kindly assist with changing the banner images for the following (desktop & mobile); text to maintain: 

1. Home Page - Slider Banner CHYA (https://zcova.com/)
Old Image : 
![Screenshot 2024-05-15 at 9 24 22 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/e35eadf3-e0c3-4bc5-b9fd-537aa58ca42e)
Replace With : 
https://drive.google.com/file/d/17OW5DGLGqVEob1Y5ozMNhnclXeeQmJPN/view?usp=drive_link
https://drive.google.com/file/d/17O8j7ZQXTjvpWvSKhgvdgc_w5chDsf36/view?usp=drive_link

2. Home Page - Slider Banner HONEST RECOMMENDATION (https://zcova.com/)
Old Image : 
![Screenshot 2024-05-15 at 9 28 05 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/8274cf56-7ea7-4e15-aa53-7fc6d17dbba2)
Replace With : 
https://drive.google.com/file/d/17MXatitpD8IKlIj0o11AOCnWQRJUt3Nv/view?usp=drive_link
https://drive.google.com/file/d/17Ni1-SXV91ukmjxbGoWgC3W62yUjm2k6/view?usp=drive_link

3. Engagement Ring Page - Header (https://zcova.com/engagement-ring-education)
Old Image : 
![Screenshot 2024-05-15 at 9 30 05 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/0ed0c918-5f83-4737-a05b-8ca507f7e4ec)
Replace With : 
https://drive.google.com/file/d/17Wz296D84P-5vtF4MboHP0RtoxBJVokc/view?usp=drive_link

4. Wedding Ring Page - Header (https://zcova.com/wedding-ring-education)
Old Image : 
![Screenshot 2024-05-15 at 9 33 10 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/a8bf744e-979f-4fb5-bc70-40924a55269a)
Replace With : 
https://drive.google.com/file/d/17YtpGjwIcFyYl4oPsOK6lST6ykJRxZmP/view?usp=drive_link

5. Diamond Page - Section Image BEYOND 4CS (https://zcova.com/mined-diamond-education)
Old Image : 
![Screenshot 2024-05-15 at 9 35 59 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/c3c3b053-64e1-40d0-a162-f357e7a0137b)
Replace With : 
https://drive.google.com/file/d/17SQzIq-F2GMcqchC0nzW31_epvnyBcbK/view?usp=drive_link

6. Diamond Page - Menu Icon MINED DIAMONDS
Old Image : 
![Screenshot 2024-05-15 at 9 40 15 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/4922ff67-2f5c-4d46-b327-ad89c1bf09f3)
Replace With : 
https://drive.google.com/file/d/17S7p4ekpUN__Hutw0Xsj3kXn2BbTEK9G/view?usp=drive_link

7. Gemstone Page - Section Image BIRTHSTONE BY ZCOVA (https://zcova.com/gemstone-education)
Old Image : 
![Screenshot 2024-05-15 at 9 43 52 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/9ef43d9e-b074-4564-ac18-c188e9aa845e)
Replace With : 
https://drive.google.com/file/d/17V27aoWCh2Gopgz1avRi6y0784CP8XE4/view?usp=drive_link

8. Fine Jewellery Page - Sectgion Image BIRTHSTONE JEWELLERY (https://zcova.com/fine-jewellery-education)
Old Image : 
![Screenshot 2024-05-15 at 9 47 00 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/c73be877-7d70-4a3a-95b8-c21a3683177d)
Replace With : 
https://drive.google.com/file/d/17UF8-pSXA4tz09No1FbCBjCAkVGlsRWI/view?usp=drive_link

Thank you!

**Comment by kimberlyljw** [comment]
Hi @salimi-my 

Kindly find the assets linked here : https://drive.google.com/drive/folders/1KJPq5En3I3xM6DeiUShVbCD_uCtsusJr?usp=sharing

If you can't open, kindly request access & I'll approve it. 

Thank you!

**Comment by salimi-my** [comment]
Updated.

**Comment by kimberlyljw** [comment]
Hi @salimi-my , 

Have checked through & saw that : 

1. Diamonds Page - Section Image BEYOND 4 Cs (https://zcova.com/mined-diamond-education) has not been updated as pictured below : 
![Screenshot 2024-05-17 at 9 34 36 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/48f1dd89-8e9e-4667-bb79-4790c2480106)

Kindly amend using the image under the "Malaysia > Diamonds" file from the Google Drive link provided previously. The image name should be "Diamond_Banner_Sec7_1470x770px.jpg"

2. Gemstones Page - Section Image BIRTHSTONE BY ZCOVA (https://zcova.com/gemstone-education) has not been updated as pictured below : 
![Screenshot 2024-05-17 at 9 38 43 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/52af06b1-27e2-4702-b050-d7381b11ecb6)

Kindly amend using the image under the "Malaysia > Gemstone" file. The image name should be "Gemstone_Banner_1470x770px.jpg"

Thank you!

**Comment by salimi-my** [comment]
Updated.
