### ISSUE TITLE
Website Image Updates - International 

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#391]
Hi Team,

Kindly assist with changing the banner images for the following; text to maintain:

1. Engagement Ring Page - Header (https://zcova.com/international/engagement-ring-education)
Old Image : 
![Screenshot 2024-05-15 at 10 21 45 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/09f0f797-3d1c-4dcd-8c81-f3883c412ba8)
Replace With :
https://drive.google.com/file/d/17Wz296D84P-5vtF4MboHP0RtoxBJVokc/view?usp=drive_link

2. Wedding Ring Page - Header (https://zcova.com/international/wedding-ring-education)
Old Image :
![Screenshot 2024-05-15 at 9 33 10 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/79b748a7-3831-405b-aa22-b68ebd8f80fd)
Replace With :
https://drive.google.com/file/d/17YtpGjwIcFyYl4oPsOK6lST6ykJRxZmP/view?usp=drive_link

3. Diamond Page - Section Image BEYOND 4CS (https://zcova.com/international/mined-diamond-education)
Old Image : 
![Screenshot 2024-05-15 at 9 35 59 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/f2615e2c-6f0e-4c49-9a6a-776eee1a4ff0)
Replace With :
https://drive.google.com/file/d/17SQzIq-F2GMcqchC0nzW31_epvnyBcbK/view?usp=drive_link

4. Diamond Page - Menu Icon MINED DIAMONDS
Old Image : 
![Screenshot 2024-05-15 at 9 40 15 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/2c512407-57a0-4916-ac01-1500ba65c302)
Replace With :
https://drive.google.com/file/d/17S7p4ekpUN__Hutw0Xsj3kXn2BbTEK9G/view?usp=drive_link

5. Gemstone Page - Section Image BIRTHSTONE BY ZCOVA (https://zcova.com/international/gemstone-education)
Old Image : 
![Screenshot 2024-05-15 at 9 43 52 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/9ef898ff-1bfd-4ea8-b22e-aaabea5f4c4c)
Replace With :
https://drive.google.com/file/d/17V27aoWCh2Gopgz1avRi6y0784CP8XE4/view?usp=drive_link

6. Fine Jewellery Page - Sectgion Image BIRTHSTONE JEWELLERY (https://zcova.com/international/fine-jewellery-education)
Old Image : 
![Screenshot 2024-05-15 at 9 47 00 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/eb143aae-8249-474a-81be-04cfd3fba87a)
Replace With :
https://drive.google.com/file/d/17UF8-pSXA4tz09No1FbCBjCAkVGlsRWI/view?usp=drive_link

Thank you!

**Comment by kimberlyljw** [comment]
Hi @salimi-my 

Kindly find the assets linked here : https://drive.google.com/drive/folders/1KJPq5En3I3xM6DeiUShVbCD_uCtsusJr?usp=sharing

If you can't open, kindly request access & I'll approve it. 

Thank you!

**Comment by salimi-my** [comment]
Updated.

**Comment by kimberlyljw** [comment]
Hi @salimi-my 

For the Gemstone Page - Section Image BIRTHSTONE BY ZCOVA (https://zcova.com/international/gemstone-education), the text is overlapping with the image as pictured : 
![Screenshot 2024-05-17 at 9 45 24 AM](https://github.com/logicwisesoftware/zcova/assets/156041223/ac3326b0-df61-49ec-a26a-dcccf7f52247)

Kindly shift the text & button to the right side where the empty space is. 

Thank you!

**Comment by salimi-my** [comment]
Updated.
