### ISSUE TITLE
Homepage Image Update - International 

### ISSUE THREAD

**Issue by kimberlyljw** [logicwisesoftware/zcova#392]
Hi Team,

Kindly assist with changing the banner images for the following; text to maintain: (all these images can be found on https://zcova.com/international/)

1. Slinding Banner - CHYA (mobile & desktop) 
Old Image : 
![Screenshot 2024-05-15 at 12 06 34 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/cd69d49f-a85c-4bb0-9a79-04b52144793a)
Replace With :
https://drive.google.com/file/d/1x2NzgVx8M0Vj2AjE54GHIYH-nmhKdQiE/view?usp=drive_link
https://drive.google.com/file/d/199pwGMPd78y7BGRTfxeOEiwUS0WBCXQP/view?usp=drive_link

2. Sliding Banner - HONEST RECOMMENDATIONS (mobile & desktop) 
Old Image : 
![Screenshot 2024-05-15 at 12 08 57 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/af22feac-ffc3-4f61-97e9-046f139f58c9)
Replace With :
https://drive.google.com/file/d/1JDP3N32viuvkY5YQX1eck-uzlpDZgbsu/view?usp=drive_link
https://drive.google.com/file/d/1YP48qpLgKQ3bXd7SBR_ki58sq4kBaLG0/view?usp=drive_link

3. Section Image - SHOP WEDDING RINGS 
Old Image :
![Screenshot 2024-05-15 at 12 09 58 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/01ad3542-9e4e-453e-b4cf-1a4bfbfc3b05)
Replace With :
https://drive.google.com/file/d/1Y32rnRG5kfPMhF_VFGfFDRMmo4k0Lbtq/view?usp=drive_link

4. Section Image - GEMSTONE JEWELLERY 
Old Image :
![Screenshot 2024-05-15 at 12 11 07 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/d530cf2a-a4bf-45ff-a948-279cd9bd09fa)
Replace With :
https://drive.google.com/file/d/13VFeNAnIYN7Nnvt_XqgRcjpEiZ4dbK22/view?usp=drive_link

5. Section Image - ICL CERTIFIED 
Old Image :
![Screenshot 2024-05-15 at 12 12 13 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/75cc0304-8e84-41cc-ba73-87ab1437c81f)
Replace With :
https://drive.google.com/file/d/17WTxRH_yLjxw95SBfBU9rKo8I10iV4Ck/view?usp=drive_link

6. Section Image - SHOP FINE JEWELLERY 
Old Image :
![Screenshot 2024-05-15 at 12 13 24 PM](https://github.com/logicwisesoftware/zcova/assets/156041223/82d6af6e-9371-47ac-b20d-8fbab7cd2cca)
Replace With :
https://drive.google.com/file/d/1nC8Yk767wbdZsmM3gkU_6oj5j7ayk2at/view?usp=drive_link

Thank you!

**Comment by kimberlyljw** [comment]
Hi @salimi-my 

Kindly find the assets linked here : https://drive.google.com/drive/folders/1KJPq5En3I3xM6DeiUShVbCD_uCtsusJr?usp=sharing

If you can't open, kindly request access & I'll approve it. 

Thank you!

**Comment by salimi-my** [comment]
Updated.
