### ISSUE TITLE
New Blog Landing Page - Natural vs Lab Diamonds

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#395]
Hi team, need your help to create new blog landing page

1. [Figma working file](https://www.figma.com/design/AKCSX5lpe8ApdrYYybILGf/Dev-Blog-natural-vs-lab?node-id=0-1&t=NatHOop1Rec1fRc0-1) (sign in to edit and see stylings)
2. [Content gdoc ](https://docs.google.com/document/d/1EoSKXf7s0gHXG_aRVIjSrE1SMiefecmE9eD7sDNj0jc/edit?usp=sharing)
^ please follow the heading hierarchy as set in google doc
3. [Visuals folder](https://drive.google.com/drive/folders/1jLWLXloUh8jcQpGW6AwsI9oM6uUyAP0y?usp=sharing)

Please let me know there's any question, thank you

**Comment by salimi-my** [comment]
hi @Shellytsy. What URL should this page be?

**Comment by Shellytsy** [comment]
Hi Salimi, please use this
zcova.com/lab-grown-vs-natural-diamonds-differences

**Comment by Shellytsy** [comment]
Hi Salimi, how's the progress going for this page? :)

**Comment by salimi-my** [comment]
Hi @Shellytsy, this is still in progress. Currently still mainly doing the homepage banner upload feature. But this landing page can be expected to be completed at the latest end of this week.

**Comment by Shellytsy** [comment]
Okay thanks for the update, can we prioritise publishing this landing page on top of the cms?

**Comment by salimi-my** [comment]
Yes, we can do that. I'll prioritize completing this landing page first.

**Comment by Shellytsy** [comment]
Great, thanks Salimi! :)

**Comment by Shellytsy** [comment]
Hi Salimi, the page looks great! Just one minor thing: can you help add a line break in the headline
Lab-Grown vs. Natural Diamonds: 
< break >
What Are the Differences?

The rest looks perfect, thank you!

**Comment by salimi-my** [comment]
The page has been successfully deployed and requested changes has been updated, marking this issue as completed. If any adjustments or amendments are necessary, please feel free to create a new issue.
