### ISSUE TITLE
[URGENT] Update lab promo page with new flash sales

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#398]
Current lab promo page:
https://zcova.com/labpromo

Replace with the below:
![image](https://github.com/logicwisesoftware/zcova/assets/144078599/fe61d6db-2759-4c77-a277-06f843d086e5)
Working file: https://drive.google.com/file/d/1okScsZvkuOq-RG67ixBCKlN18t3LK4oi/view?usp=sharing

Headline: Get 15% OFF lab grown diamonds
Sub-headline: Limited time deal only. Book an appointment with us now!
CTA: Get Now

T&Cs: 
[Flash Sale June '24 Promo T&C.pdf](https://github.com/user-attachments/files/15879522/Flash.Sale.June.24.Promo.T.C.pdf)

**Comment by logicwisesoftware** [comment]
Do you also have the design for mobile view?

Example: https://zcova.com/assets/front/images/promo/may-lab-promo-mobile.webp

**Comment by logicwisesoftware** [comment]
Both desktop and mobile have been updated.
