### ISSUE TITLE
New Blog - Virtual Try On Rings

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#399]
Hi team, need your help to create new blog landing page

url: zcova.com/virtual-try-on-rings

[Figma working file](https://www.figma.com/design/HfLpJLIB9aV00vz46QOFXX/BLOG-LANDING-PAGE%3A-ZCOVA%E2%80%99s-Virtual-Rings-Try-On?node-id=0-1) (sign in to edit and see stylings)
[Content gdoc ](https://docs.google.com/document/d/1XCI8a3ohWwEjIoZXFyXLgcvOzulah5g1J8Uz4Z26i3s/edit)
^ please follow the heading hierarchy as set in google doc
[Visuals folder](https://drive.google.com/drive/folders/1QqcBOnYhneO_J71rJ0tSDH80-dN5bZlC)

Please let me know there's any question, thank you

**Comment by salimi-my** [comment]
Hi @Shellytsy. Please give link for "Try on a Ring" & "Shop Now" button.

**Comment by Shellytsy** [comment]
Hi Salimi, please use the links as followed

Try on a ring: 
https://www.zcova.com?utm_source=blog&utm_medium=post&utm_campaign=virtualar

Shop Now: 
https://zcova.com/engagement-ring?start=setting?utm_source=blog&utm_medium=post&utm_campaign=virtualar

**Comment by salimi-my** [comment]
Page completed. Please do check and review.

[https://zcova.com/virtual-try-on-rings](https://zcova.com/virtual-try-on-rings)

**Comment by Shellytsy** [comment]
Hi Salimi, few edits needed:

1. Replace > Blog Banner (Desktop & Mobile)
[Desktop](https://drive.google.com/open?id=1RB4K8h4Thnj_tYVY32DGDKZivcKA-IRQ&usp=drive_fs)
[Mobile](https://drive.google.com/open?id=1RF-BFIIv90AkkvDWBEmNhNYeWR6XmXwt&usp=drive_fs)

2. All section 3 (Steps 1,2,3)- pictures do not need to be compressed, they look a bit pixelated now.

3. The font size please follow the size in Figma / follow the size of the blog (natural vs lab)

4. Samsung Model phone display (Mobile) - ALL the paragraph gap is too near the screen.
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/8f4f4cb0-94e1-4bf8-9cf4-fa6ffd630092)

5. Section 4 (Under the GIF) - Please change the paragraph > lower 2 font sizes? 
(Desktop & Mobile)
![image](https://github.com/logicwisesoftware/zcova/assets/142577916/c1a7f19e-5fac-4882-a5e7-bd308e45864d)

Thank you

**Comment by salimi-my** [comment]
The page has been successfully deployed and requested changes has been updated, marking this issue as completed. If any adjustments or amendments are necessary, please feel free to create a new issue.
