### ISSUE TITLE
Homepage Speak to us

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#40]
[![Screenshot_2022-06-07_09-06-28.png](https://mrkr.io/s/629f1514518e98007dacd8c2/2)](https://mrkr.io/s/629f1514518e98007dacd8c2/0)

- Change image
- add text and icon links

Image: https://drive.google.com/open?id=1vsMF9L6jpXAY2FHWzdeWl7iJbEao4Pth&authuser=eewern%40zcova.com&usp=drive_fs

Title 1 (left): Speak To A ZCOVA Curator
Body (left): Our friendly Curators offer hands-on help with your ring shopping. We will be by your side every step of the way.
Icon:
FB messenger icon- m.me/zcovajewels
IG icon- https://www.instagram.com/zcova/
WhatsApp icon- https://wa.me/message/AVA3LXQFLI5LG1
Email icon- service@zcova.com

Title 2 (right): Make an Appointment to Visit Our ZCOVA Galeria!
Body 2 (right): Our Curators are always ready to provide you with a red carpet service during your visit to our Galeria. 
Botton: Contact ( link to https://zcova.com/appointment )

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629f1514518e98007dacd93b_525e46af5cf666a9?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629f1514518e98007dacd93b_525e46af5cf666a9)

**Console:** [⚠️  118 warnings ](https://app.marker.io/i/629f1514518e98007dacd93b_525e46af5cf666a9?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629f1514518e98007dacd93b_525e46af5cf666a9) - This issue was marked as resolved in Marker.io.
