### ISSUE TITLE
Homepage review

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#41]
[![Screenshot_2022-06-07_09-09-15.png](https://mrkr.io/s/629f15bb4dce011acb20f968/2)](https://mrkr.io/s/629f15bb4dce011acb20f968/0)

- remove logo divider

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629f15bb4dce011acb20f9e3_d889402d5e31f318?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629f15bb4dce011acb20f9e3_d889402d5e31f318)

**Console:** [⚠️  119 warnings ](https://app.marker.io/i/629f15bb4dce011acb20f9e3_d889402d5e31f318?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1707 x 813</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629f15bb4dce011acb20f9e3_d889402d5e31f318) - This issue was marked as resolved in Marker.io.
