### ISSUE TITLE
Homepage Social Proof

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#42]
[![Screenshot_2022-06-07_09-21-36.png](https://mrkr.io/s/629f18a08e54436d1e4d8d85/2)](https://mrkr.io/s/629f18a08e54436d1e4d8d85/0)

- change content
- Add dots to change page (auto slider 3 seconds. 7 icons per slide)

Social Proof:
- RM28mil+
Saved

- 6100
Happy Customers

- 5
Star Ratings

- 600+
Reviews

Media Icon:
- Add dots to change (auto slider 3 seconds. 7 icons per slide)

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629f18a08e54436d1e4d8dff_f414368046dc90a0?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629f18a08e54436d1e4d8dff_f414368046dc90a0)

**Console:** [⚠️  119 warnings ](https://app.marker.io/i/629f18a08e54436d1e4d8dff_f414368046dc90a0?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1707 x 813</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629f18a08e54436d1e4d8dff_f414368046dc90a0) - This issue was marked as resolved in Marker.io.
