### ISSUE TITLE
Homepage Newsletter

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#43]
[![Screenshot_2022-06-07_09-25-15.png](https://mrkr.io/s/629f197b890e47855e275ea4/2)](https://mrkr.io/s/629f197b890e47855e275ea4/0)

- change title & body

Title: Don’t Miss Our New Promotions!
Body 1 : Sign Up For Our Newsletter

Body 2: By signing up you confirm that you have read the Privacy Policy and agree to the terms stated.

*Body 2 "Privacy Policy" link to https://zcova.com/privacy

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/629f197b890e47855e275f1e_a8d994a41a7bf9c7?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629f197b890e47855e275f1e_a8d994a41a7bf9c7)

**Console:** [⚠️  119 warnings ](https://app.marker.io/i/629f197b890e47855e275f1e_a8d994a41a7bf9c7?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1707 x 813</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/629f197b890e47855e275f1e_a8d994a41a7bf9c7) - This issue was marked as resolved in Marker.io.
