### ISSUE TITLE
Homepage footer

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#44]
[![Screenshot_2022-06-08_08-04-28.png](https://mrkr.io/s/62a0580c890e47855e2b4988/2)](https://mrkr.io/s/62a0580c890e47855e2b4988/0)

- change title & body
- add link

Title 1 : ABOUT ZCOVA
- Home (link to https://zcova.com/)
- About Us (link to https://zcova.com/about)
- Education (link to https://blog.zcova.com/)
- Contact Us (link to https://zcova.com/contact)
- Virtual Appointment (link to https://zcova.com/appointment)
- Our Promises (link to https://zcova.com/our-promises)
- FAQs (link to https://zcova.com/faq)
- Sitemap

Title 2: PRODUCTS
- Diamonds (link to https://zcova.com/diamond)
- Gemstones (link to https://zcova.com/gemstone)
- Engagement Rings (link to https://zcova.com/engagement-ring)
- Fine Jewellery (link to https://zcova.com/fine-jewellery)
- Wedding Rings (link to https://zcova.com/fine-jewellery/wedding-rings)
- Necklace (link to https://zcova.com/fine-jewellery/necklaces)
- Bracelet (link to https://zcova.com/fine-jewellery/bracelets)
- Earrings (link to https://zcova.com/fine-jewellery/earrings)
- Birthstones (link to https://zcova.com/birthstone)

Title 3: WHY ZCOVA?
- Lifetime Warranty (link to https://www.zcova.com/warranty)
- Dual-Certified Diamonds (link to https://blog.zcova.com/2020/02/05/guaranteed-brilliant-diamonds-dual-certified-gia-gemex/)
- ICL Certified Gemstones (link to https://blog.zcova.com/2020/12/24/icl-cert/)
- Free Global Insured Shipping (link to https://www.zcova.com/shipping)
- Free Resizing (link to https://www.zcova.com/resizing)
- Price Match Guarantee (link to https://www.zcova.com/price-match-guarantee)
- Packaging (link to https://www.zcova.com/packaging)
- 10x Magnified 360° HD Videos (link to https://www.zcova.com/360-video-technology)
- 3D Print & 3D Renders (link to https://www.zcova.com/3d-printing)

Title 4: POLICIES
- Privacy Policy (link to https://www.zcova.com/privacy)
- Terms & Conditions (link to https://www.zcova.com/terms-and-conditions)
- Return Policy (link to https://www.zcova.com/returns)
- Payment Method (Malaysia) (link to https://www.zcova.com/payment)
- Payment Method (International) (link to https://www.zcova.com/international-payment)
- Shipping (link to https://www.zcova.com/shipping)

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a0580c890e47855e2b498c_55155fbe611578f3?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a0580c890e47855e2b498c_55155fbe611578f3)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/62a0580c890e47855e2b498c_55155fbe611578f3?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 731</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a0580c890e47855e2b498c_55155fbe611578f3) - This issue was marked as resolved in Marker.io.
