### ISSUE TITLE
Homepage banner mobile design

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#45]
[![Screenshot_2022-06-08_08-21-20.png](https://mrkr.io/s/62a05c006aea27ab0bc3c7bb/2)](https://mrkr.io/s/62a05c006aea27ab0bc3c7bb/0)

- on mobile devices, please follow this design https://www.graff.com/international-en/home/
- image size 445px x 445 px
-Title, description and button below image

SAMPLE: https://drive.google.com/open?id=1gVAKbn8yfYp8N1bMJt3opKnDDrOxnpFo&authuser=eewern%40zcova.com&usp=drive_fs

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a05c006aea27ab0bc3c7bf_baa3aad0c217a10f?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a05c006aea27ab0bc3c7bf_baa3aad0c217a10f)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/62a05c006aea27ab0bc3c7bf_baa3aad0c217a10f?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1800 x 914</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a05c006aea27ab0bc3c7bf_baa3aad0c217a10f) - This issue was marked as resolved in Marker.io.
