### ISSUE TITLE
Homepage desktop banner

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#46]
[![Screenshot_2022-06-08_08-44-49.png](https://mrkr.io/s/62a061816aea27ab0bc3d8ea/2)](https://mrkr.io/s/62a061816aea27ab0bc3d8ea/0)

- change the title, description & button
- change all iamges

Title 1: Everyone Deserves A Beautiful Love Story
Body: Your story begins here in ZCOVA with the perfect diamond and gemstone jewellery.
Button: Shop Now (link to https://zcova.com/fine-jewellery?utm_source=website&utm_medium=banner&utm_campaign=homebannerlovestory)
DESKTOP Image: https://drive.google.com/open?id=1xN-lbBWAN4JEahnmp5xq-3pq4UZ7Fg5y&authuser=eewern%40zcova.com&usp=drive_fs
MOBILE Image: https://drive.google.com/open?id=1xNyMvI5FcodLLcYVH7r-y00K5iZFkWlp&authuser=eewern%40zcova.com&usp=drive_fs

Title 2: Secret To Brilliant Diamonds
Body: Go beyond Triple Excellent Diamonds. LUMOS by ZCOVA diamonds are Dual-Certified by GIA & GemEx to guarantee brilliance.
Button: Shop LUMOS by ZCOVA (link to https://zcova.com/diamond?utm_source=website&utm_medium=banner&utm_campaign=homebannerlumos - filter LUMOS diamond)
DESKTOP Image: https://drive.google.com/open?id=1xMp3kgwSccD27UITrpJv3J2W7kXcs3ec&authuser=eewern%40zcova.com&usp=drive_fs
MOBILE Image: https://drive.google.com/open?id=1xNtDYyfE5cvyU2djCalX567qKf6JlINR&authuser=eewern%40zcova.com&usp=drive_fs

Title 3: We’re With You Every Step Of The Way
Body: From choosing your perfect diamond or gemstone to customizing your dream jewellery, our ZCOVA Curators are there with you. Don’t listen to us, listen to our 500+ happy online 5-star reviews.
Button: Customer Reviews (link to https://g.page/r/CbqXnlM-Soe1EAE)
DESKTOP Image: https://drive.google.com/open?id=1xN6EijIFqyh0Nza084RV9Z0H5GEJw2h0&authuser=eewern%40zcova.com&usp=drive_fs
MOBILE Image: https://drive.google.com/open?id=1xNbE4nMN__3xDfw6EPuK3ICsBkH4Ggs8&authuser=eewern%40zcova.com&usp=drive_fs

Title 4: 10x Clearer, 10x Better
Body: See diamonds in 10x detail to be 100% sure of your choice & the quality.
Button: Browse Diamond (link to https://zcova.com/diamond?utm_source=website&utm_medium=banner&utm_campaign=homebanner10x)
DESKTOP Image: https://drive.google.com/open?id=1xNTSKg-ZZJfHOOhPwoqyIT7wn_vEnhJe&authuser=eewern%40zcova.com&usp=drive_fs
MOBILE Image: https://drive.google.com/open?id=1xNaLExz5kkyS7_Dux_GMlt8LQqkpI8A9&authuser=eewern%40zcova.com&usp=drive_fs

Title 5: Why Is an ICL Certificate Important?
Body: Be certain of your gemstone’s identity. Carat, Colour & Origin can greatly affect your gemstone’s value! 
Button: Learn More (link to https://blog.zcova.com/2020/12/24/icl-cert/?utm_source=website&utm_medium=banner&utm_campaign=homebannericl)
DESKTOP Image: https://drive.google.com/open?id=1xNK2050usGeiHUKYEJvnkegIU1llwuee&authuser=eewern%40zcova.com&usp=drive_fs
MOBILE Image: https://drive.google.com/open?id=1xQr_1RGs_rTUOERpB47EvESbyCraCouy&authuser=eewern%40zcova.com&usp=drive_fs

Title 6: Compare Diamond Choices With Ease
Body: It is our promise to you to be transparent. With all prices and specifications displayed on our website, you can compare your choices and choose wisely.
Button: Browse Diamond (link to https://zcova.com/diamond?utm_source=website&utm_medium=banner&utm_campaign=homebannercompare)
DESKTOP Image: https://drive.google.com/open?id=1xN9ftLwb8VukAU-5TngBvZ15QO10XnVB&authuser=eewern%40zcova.com&usp=drive_fs
MOBILE Image: https://drive.google.com/open?id=1xPyW1T0Kz1Jh6vnHXLhE9gmmu9BtB6wl&authuser=eewern%40zcova.com&usp=drive_fs

Title 7: Honest Recommendation
Body: A ZCOVA Experience like no other. Learn about diamonds through 1-to-1 consultations with ZCOVA Curators anytime, anywhere!
Button: Talk To Us (link to https://zcova.com/contact?utm_source=website&utm_medium=banner&utm_campaign=homebannerhonest)
DESKTOP Image: https://drive.google.com/open?id=1xOFS99FGZkG-153RZyGxol2A4mgAQt3W&authuser=eewern%40zcova.com&usp=drive_fs
MOBILE Image: https://drive.google.com/open?id=1xOcBbCr81tYCTVUN19hgIjPjV2laVbkS&authuser=eewern%40zcova.com&usp=drive_fs

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a061816aea27ab0bc3d8f0_91ccff83ffea9918?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a061816aea27ab0bc3d8f0_91ccff83ffea9918)

**Console:** [⚠️  2 warnings ℹ️  1 info ](https://app.marker.io/i/62a061816aea27ab0bc3d8f0_91ccff83ffea9918?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1800 x 914</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a061816aea27ab0bc3d8f0_91ccff83ffea9918) - This issue was marked as resolved in Marker.io.
