### ISSUE TITLE
Footer Social

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#47]
[![Screenshot_2022-06-08_08-55-04.png](https://mrkr.io/s/62a063e7f3030f2a4b92ed06/2)](https://mrkr.io/s/62a063e7f3030f2a4b92ed06/0)

Title: Follow us
Icon: Facebook
- link to https://www.instagram.com/zcova/

Icon IG
- link to https://www.facebook.com/zcovajewels

Icon Xiao Hong Shu
- link to http://www.xiaohongshu.com/user/profile/615be1280000000002021bcf

Icon TikTok
- link to https://www.tiktok.com/@zcova

Icon Pinterest
- link to link to https://www.pinterest.com/zcovajewel/

Icon YouTube
- link to https://www.youtube.com/channel/UCV1sZAxr7d6V9PC_8VTuExA

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a063e7f3030f2a4b92ed10_750d3973fa7701a6?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a063e7f3030f2a4b92ed10_750d3973fa7701a6)

**Console:** [⚠️  6 warnings ℹ️  1 info ](https://app.marker.io/i/62a063e7f3030f2a4b92ed10_750d3973fa7701a6?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1800 x 914</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a063e7f3030f2a4b92ed10_750d3973fa7701a6) - This issue was marked as resolved in Marker.io.
