### ISSUE TITLE
Engagement Ring landing banner

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#48]
[![Screenshot_2022-06-08_09-08-57.png](https://mrkr.io/s/62a06729890e47855e2b7b0c/2)](https://mrkr.io/s/62a06729890e47855e2b7b0c/0)

- change image & text
- add link

Title: Diamond Engagement Rings
Body: Your love chapter starts here. Handcrafted engagement rings for the perfect fitting, made perfect for your marriage proposal.
Button: Browse Now (link to https://zcova.com/engagement-ring)
Image: https://drive.google.com/open?id=1m2RdXznvFaN3L_Tz3soy15HElrzb3m-e&authuser=eewern%40zcova.com&usp=drive_fs

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a06729890e47855e2b7b12_171b9696384138ae?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a06729890e47855e2b7b12_171b9696384138ae)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/62a06729890e47855e2b7b12_171b9696384138ae?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1800 x 914</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a06729890e47855e2b7b12_171b9696384138ae) - **Isabel (isabel@zcova.com)** commented via Marker.io:

> Standardise body size to 18px.
> Max width of text is 40% like homepage banner

[Reply here](https://app.marker.io/i/62a06729890e47855e2b7b12_171b9696384138ae)

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a06729890e47855e2b7b12_171b9696384138ae) - This issue was marked as resolved in Marker.io.
