### ISSUE TITLE
Engagement ring landing start with a diamond

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#49]
[![Screenshot_2022-06-08_09-13-20.png](https://mrkr.io/s/62a0682f890e47855e2b7e48/2)](https://mrkr.io/s/62a0682f890e47855e2b7e48/0)

- image & text

Title: Create Your Own Engagement Ring
Body: Pair any 18k gold ring design of your choice with the perfect GIA certified diamond.
Image: https://drive.google.com/open?id=1m2wxOMSir1-7e4K4QPQOVRxZHxPGfmcn&authuser=eewern%40zcova.com&usp=drive_fs

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a06830890e47855e2b7e4e_ae5ec8ae24a1c88f?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a06830890e47855e2b7e4e_ae5ec8ae24a1c88f)

**Console:** [⚠️  2 warnings ℹ️  1 info ](https://app.marker.io/i/62a06830890e47855e2b7e4e_ae5ec8ae24a1c88f?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1800 x 914</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a06830890e47855e2b7e4e_ae5ec8ae24a1c88f) - This issue was marked as resolved in Marker.io.
