### ISSUE TITLE
Engagement ring landing zcova signature rings

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#50]
[![Screenshot_2022-06-08_09-31-22.png](https://mrkr.io/s/62a06c6a4dce011acb2535c7/2)](https://mrkr.io/s/62a06c6a4dce011acb2535c7/0)

- add arrow
- Follow the bottom spacing

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a06c6a4dce011acb2535d1_daa4181dff29bdce?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a06c6a4dce011acb2535d1_daa4181dff29bdce)

**Console:** [⚠️  6 warnings ℹ️  1 info ](https://app.marker.io/i/62a06c6a4dce011acb2535d1_daa4181dff29bdce?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1800 x 914</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a06c6a4dce011acb2535d1_daa4181dff29bdce) - This issue was marked as resolved in Marker.io.
