### ISSUE TITLE
Homepage diamond

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#52]
[![Screenshot_2022-06-09_01-29-52.png](https://mrkr.io/s/62a14d10f3030f2a4b961849/2)](https://mrkr.io/s/62a14d10f3030f2a4b961849/0)

- Make the "Shop wedding rings" clickable

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a14d10f3030f2a4b96184d_c939e5a608008630?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a14d10f3030f2a4b96184d_c939e5a608008630)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/62a14d10f3030f2a4b96184d_c939e5a608008630?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>2160 x 1096</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a14d10f3030f2a4b96184d_c939e5a608008630) - This issue was marked as resolved in Marker.io.
