### ISSUE TITLE
Homepage footer & social

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#57]
[![Screenshot_2022-06-09_01-46-07.png](https://mrkr.io/s/62a150df0458e0eedc10eb5a/2)](https://mrkr.io/s/62a150df0458e0eedc10eb5a/0)

- Footer: Change to the same colour as the title
- Social: Change this bug

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a150df0458e0eedc10eb5e_f9bc1702eed5e016?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a150df0458e0eedc10eb5e_f9bc1702eed5e016)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/62a150df0458e0eedc10eb5e_f9bc1702eed5e016?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1800 x 914</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.600000023841858x</td></tr></table>

**Comment by salimi-my** [comment]
Please force refresh or clear cache.

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a150df0458e0eedc10eb5e_f9bc1702eed5e016) - This issue was marked as resolved in Marker.io.
