### ISSUE TITLE
Homepage Navigation bar dropdown Engagement ring

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#58]
[![Screenshot_2022-06-09_01-49-47.png](https://mrkr.io/s/62a151bb890e47855e2ea63f/2)](https://mrkr.io/s/62a151bb890e47855e2ea63f/0)

- fix this bug

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a151bb890e47855e2ea647_1e705b23535dff3f?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a151bb890e47855e2ea647_1e705b23535dff3f)

**Console:** [⚠️  2 warnings ℹ️  1 info ](https://app.marker.io/i/62a151bb890e47855e2ea647_1e705b23535dff3f?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>2880 x 1462</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Please force refresh or clear cache

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a151bb890e47855e2ea647_1e705b23535dff3f) - This issue was marked as resolved in Marker.io.
