### ISSUE TITLE
Engagement Ring landing LUMOS by ZCOVA

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#59]
[![Screenshot_2022-06-09_02-09-59.png](https://mrkr.io/s/62a15677518e98007db43ef9/2)](https://mrkr.io/s/62a15677518e98007db43ef9/0)

- change the image
- change the title and body
- change title to H2; body standardize to 18px
- standardize spacing

Title: LUMOS by ZCOVA (SIZE H2)
Body: The only brand in Malaysia & Singapore to guarantee your diamond’s brilliance using GIA & GemEx certificates.  (SIZE 18px)
Button: Shop Now (link to https://zcova.com/diamond - filter by LUMOS diamond
Image: https://drive.google.com/file/d/1m2vxsHWO2m4OZ3nlTumTJE7k98GwEA-p/view?usp=sharing

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a15677518e98007db43efd_c62c510958d2fb90?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a15677518e98007db43efd_c62c510958d2fb90)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/62a15677518e98007db43efd_c62c510958d2fb90?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a15677518e98007db43efd_c62c510958d2fb90) - This issue was marked as resolved in Marker.io.
