### ISSUE TITLE
Engagement Ring landing Popular Engagement Ring

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#60]
[![Screenshot_2022-06-10_03-40-26.png](https://mrkr.io/s/62a2bd2a22488bb20e59a355/2)](https://mrkr.io/s/62a2bd2a22488bb20e59a355/0)

- spacing align with the photo below
- add arrow, same as above ZCOVA Signature Ring

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a2bd2a22488bb20e59a359_9182c71900037a12?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a2bd2a22488bb20e59a359_9182c71900037a12)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/62a2bd2a22488bb20e59a359_9182c71900037a12?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 731</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed
