### ISSUE TITLE
Engagement landing Diamond & gemstone engagement button

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#61]
[![Screenshot_2022-06-10_03-42-45.png](https://mrkr.io/s/62a2bdb48e54436d1e59cc91/2)](https://mrkr.io/s/62a2bdb48e54436d1e59cc91/0)

- change the button text to size H2

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a2bdb58e54436d1e59cc9b_951c7c8b7a8dded9?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a2bdb58e54436d1e59cc9b_951c7c8b7a8dded9)

**Console:** [⚠️  6 warnings ℹ️  1 info ](https://app.marker.io/i/62a2bdb58e54436d1e59cc9b_951c7c8b7a8dded9?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 975</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a2bdb58e54436d1e59cc9b_951c7c8b7a8dded9) - This issue was marked as resolved in Marker.io.
