### ISSUE TITLE
Engagement Ring Landing Shop By Style

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#62]
[![Screenshot_2022-06-13_01-45-34.png](https://mrkr.io/s/62a696be0458e0eedc1de2ac/2)](https://mrkr.io/s/62a696be0458e0eedc1de2ac/0)

- Add "Previous" and "Next" button at the side above the photos
- Change text & Images
- Link them
- Follow the photo size given

1. Halo
Image: https://drive.google.com/file/d/1mA_hcPVB396bD-Ie0WI8ARfyOvluspgM/view?usp=sharing
Link to: https://zcova.com/engagement-ring/halo

2. Pave
Image: https://drive.google.com/file/d/1mAIJggwKGH46htRCRX0YBkYY9QTIlUTw/view?usp=sharing
Link to: https://zcova.com/engagement-ring/pave

3. Solitaire
Image: https://drive.google.com/file/d/1mAAfhoqeINYbH2qHaF3hdMvHVevJFKwT/view?usp=sharing
Link to: https://zcova.com/engagement-ring/solitaire

4. Three-stone
Image: https://drive.google.com/file/d/1m7l7f-FMImeNDSe090qjAc_TVoC9hMnk/view?usp=sharing
Link to: https://zcova.com/engagement-ring/three-stone

5. White Gold
Image: https://drive.google.com/file/d/1m7esncl3zoDLc0StRkKUViQTyJlGZgIE/view?usp=sharing
Link to: https://zcova.com/engagement-ring/white-gold

6. Rose Gold
Image: https://drive.google.com/file/d/1m7dHTjnXV86el-ES307M0TzEd6Yihs_o/view?usp=sharing
https://zcova.com/engagement-ring/rose-gold

7. Yellow Gold
Image: https://drive.google.com/file/d/1m7ZW-sbpXEf9NfIQggBvnOA5FagbIaKh/view?usp=sharing
Link to: https://zcova.com/engagement-ring/yellow-gold

8. Vintage
Image: https://drive.google.com/file/d/1m7BTs7cO_lRN1EO1kpS6rYY-cIHeB9LQ/view?usp=sharing
Link to: https://zcova.com/engagement-ring/vintage

9. Oval
Image: https://drive.google.com/file/d/1m6oETO7W05QGKuCB3D8SxkempjT015Wb/view?usp=sharing
Link to: https://zcova.com/engagement-ring/oval

10. Sapphire
Image: https://drive.google.com/file/d/1mAJ9oRLW9HYResqx-4J0BEy2U_wTNtwE/view?usp=sharing
Link to: https://zcova.com/engagement-ring/sapphire

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a696be0458e0eedc1de2b0_ba257b0c8c2f77f2?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a696be0458e0eedc1de2b0_ba257b0c8c2f77f2)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/62a696be0458e0eedc1de2b0_ba257b0c8c2f77f2?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1916 x 972</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed
