### ISSUE TITLE
Engagement ring landing Shop By Diamond Shape

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#63]
[![Screenshot_2022-06-13_02-02-36.png](https://mrkr.io/s/62a69abc518e98007dc1396a/2)](https://mrkr.io/s/62a69abc518e98007dc1396a/0)

- Change the diamond shapes with the photos given
- add link

1. Round
Image: https://drive.google.com/file/d/1m6hnB_28nN1QKxcfK4AFvosRrCHUFuMs/view?usp=sharing
Link to: https://zcova.com/diamond (filter by round diamond)

2. Oval
Image: https://drive.google.com/file/d/1m5_7Fmt0-UEl_iaGy5NEw0_S-chxU4vA/view?usp=sharing
Link to: https://zcova.com/diamond (filter by oval diamond)

3. Cushion
Image: https://drive.google.com/file/d/1m6Xpu3YOwnCB5JnOpsYXeT_fKi56JTvD/view?usp=sharing
Link to: https://zcova.com/diamond (filter by cushion diamond)

4. Pear
Image: https://drive.google.com/file/d/1m5EeXI3LzrYP_crGCaNZ8k4g6T2dTSMj/view?usp=sharing
Link to: https://zcova.com/diamond (filter by pear diamond)

5. Princess
Image: https://drive.google.com/file/d/1m4w9qdl-mpY28LWrfC8yhZXtc5ySMR5v/view?usp=sharing
Link to: https://zcova.com/diamond (filter by princess diamond)

6. Emerald
Image: https://drive.google.com/file/d/1m68R9sYltuV1KA6mzPqJ7J0hx2NX2XMC/view?usp=sharing
Link to: https://zcova.com/diamond (filter by emerald diamond)

7. Marquise
Image: https://drive.google.com/file/d/1m5p5reQSaCCjYv9e3vJZqvlkNMQTOGxa/view?usp=sharing
Link to: https://zcova.com/diamond (filter by marquise diamond)

8. Asscher
Image: https://drive.google.com/file/d/1m6ilLBbFJVZr19lS_W4UDjaQ3aQJBpxA/view?usp=sharing
Link to: https://zcova.com/diamond (filter by asscher diamond)

9. Radiant
Image: https://drive.google.com/file/d/1m4uToEsgvVKWXnIBajrzJtpM_7olfTQb/view?usp=sharing
Link to: https://zcova.com/diamond (filter by radiant diamond)

10. Heart
Image: https://drive.google.com/file/d/1m5zkhPPwD-1t72eSC0IOrsEHuRt8WQwH/view?usp=sharing
Link to: https://zcova.com/diamond (filter by heart diamond)

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a69abc518e98007dc1396e_865d3530d2eb7d96?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a69abc518e98007dc1396e_865d3530d2eb7d96)

**Console:** [ℹ️  1 info ](https://app.marker.io/i/62a69abc518e98007dc1396e_865d3530d2eb7d96?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1411 x 972</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a69abc518e98007dc1396e_865d3530d2eb7d96) - This issue was marked as resolved in Marker.io.
