### ISSUE TITLE
Engagement Ring landing Customise your dream ring

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#64]
[![Screenshot_2022-06-13_02-12-00.png](https://mrkr.io/s/62a69cf0518e98007dc13e19/2)](https://mrkr.io/s/62a69cf0518e98007dc13e19/0)

- change image
Change title, body and add link

Title: Customize Your Dream Engagement Ring
Body: Concerned that your dream ring will turn out bad? At ZCOVA you don’t have to worry. We provide 3D Renders & 3D Print services in order for you to get the perfect version of your dream engagement ring. Try it out!
Button: Contact Us (Link to https://zcova.com/contact ) 
Image: https://drive.google.com/file/d/1m3wFUhBRHNyFEgYgHZJdU55k1WecYq-P/view?usp=sharing

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a69cf0518e98007dc13e23_7f1178e366b03ff9?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a69cf0518e98007dc13e23_7f1178e366b03ff9)

**Console:** [⚠️  6 warnings ℹ️  1 info ](https://app.marker.io/i/62a69cf0518e98007dc13e23_7f1178e366b03ff9?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1859 x 972</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a69cf0518e98007dc13e23_7f1178e366b03ff9) - This issue was marked as resolved in Marker.io.
