### ISSUE TITLE
Engagement Ring landing Average Diamond ring size

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#65]
[![Screenshot_2022-06-13_02-23-05.png](https://mrkr.io/s/62a69f89518e98007dc14417/2)](https://mrkr.io/s/62a69f89518e98007dc14417/0)

- change image
- change body & link them

1. How soon should you start shopping for engagement rings? 
Link to: https://blog.zcova.com/2022/01/14/how-soon-should-you-start-shopping-for-engagement-rings/ 
Image: https://drive.google.com/file/d/1m3jEOseDCD7WYq_CvW1Cq5oQX0Mq1AoP/view?usp=sharing

2. Which Diamond Shape Should You Buy?
Link to: https://blog.zcova.com/2020/08/07/picking-the-right-diamond-shapes/ 
Image: https://drive.google.com/file/d/1m3Jb05zk7hxY2MwnS6j6b2v7kLe6M3P9/view?usp=sharing

3. Propose With ZCOVA Service
Link to: https://blog.zcova.com/2019/09/01/how-to-propose-with-a-diamond-at-zcova/ 
Image: https://drive.google.com/file/d/1m3HF8KvdTTqxOrJAWYmEkpfdIrbEBWuV/view?usp=sharing

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a69f89518e98007dc14427_f8f9e1410dd02592?comments=1)

**Source URL:** [https://zcova-uat.com/engagement-rings](https://zcova-uat.com/engagement-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a69f89518e98007dc14427_f8f9e1410dd02592)

**Console:** [⚠️  12 warnings ℹ️  1 info ](https://app.marker.io/i/62a69f89518e98007dc14427_f8f9e1410dd02592?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1859 x 972</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a69f89518e98007dc14427_f8f9e1410dd02592) - This issue was marked as resolved in Marker.io.
