### ISSUE TITLE
Homepage Revi

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#66]
[![Screenshot_2022-06-13_03-13-53.png](https://mrkr.io/s/62a6ab71af476bee706b06e3/2)](https://mrkr.io/s/62a6ab71af476bee706b06e3/0)

- change image
- change the review customer name & text
- add spacing after stars (padding-top -> 25px)

1. Ganesh Jayakumar
I truly had an amazing experience with Zcova, that I simply had to go back the second time with my wife to get out wedding bands. And truth to be told, we are both very satisfied and in love with our rings. I’m so glad I chose ZCOVA. Thank you Zcova for such an impressive craftsmanship! Me and my other half love it so so so much.

2. XiaoFen Lee
The proposal ring is unique and beautiful, I really love it! I have been incredibly pleased with everything from Zcova. Highly recommended, not only for their outstanding customer service and gorgeous rings, also for the great ambiance of the showroom.

3. Stephanie B
Highly recommended! Your customer service is outstanding, the packaging is beautiful and the rings I have received so far are gorgeous and wonderful, I really love it! I have been incredibly pleased with everything from Zcova.

4. Wei Cong Yee
The team very friendly and very patience to help me find out what I want for my budget. After almost a month they finally found a perfect stone for me and deal. After 20 working days of production they delivered the ring on time.

Overall, I'm SO HAPPY and very satisfied with the price and their service. You guys are awesome and professional! Thanks Zcova, ❤️

5. James Nch
Salesperson is very professional in answering all questions. They provide a lot of information and knowledge about diamonds. Definitely match lowest price with highest quality.

I've been looking for many customized brands and commercial brand. Zcova definitely offers the best range. Highly recommended.

6. Ian Ooi
If you have problem seeking an engagement ring. Head to Zcova is never a mistake, great staffs, great boss will guide you through and help you with all they can. Their price is also very reasonable and I can say is cheaper than outside shop. Most importantly is their service.

7. Adelyn Wong
ZCOVA is a wonderful place to pick your dream jewellery piece! My husband got my beautiful engagement ring with the expertise of the consultants that were very helpful in explaining each and every detail… ZCOVA has excellent after sales service. They arranged door-to-door service to minimize contact during the pandemic and kept us informed of the shipment and the whereabouts of the rings.

8. Paggie Foo
Thanks to Zcova, i really like the ring and the spec of my proposal diamond ring. Besides this,  my ring come with proper enveloped cert too. According to my fiancee, Zcova providing many design and they did provide a mock up ring to test on your finger if you wish to check for the compatibility of it. Overall, we are highly recommending Zcova with good service provided, trusted service & product and most importantly reasonable price too!

9. Andy Pang
Truly amazing and worth to buy from Zcova. The online buying experience from consultation to deliver was very pleasant. The diamond ring really beautiful and my wife love it very much! Thank you very much Zcova for providing such as memorable experience to me. Highly recommended and trusted seller!

10. Zipporah Koh
I am so glad my now fiancé chose to get an engagement ring from Zcova as I’ve always loved Zcova’s brand and also a huge huge fan of personalised or customised items. Zcova provided us with just that! 😍

I was able to re-pick the design & colour of my engagement ring 💍

11. Ferlynna Zainuddin
About quality and workmanship wise, it is beyond our expectations! Affordable and worth every penny! Perhaps, it is way better than those branded names in the market.

We are satisfied with our purchases and would come back to purchase more jewellery pieces in time to come. It is highly recommended!

12. Chong W. 
Very good and attentive staffs, they gave me unbiased opinions and giving suggestions based on my preferences. It is indeed a unique experience and I'm glad Zcova helped me choose the best possible diamond ring.

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62a6ab71af476bee706b06e9_2c31bcdbd2ff916b?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a6ab71af476bee706b06e9_2c31bcdbd2ff916b)

**Console:** [⚠️  2 warnings ℹ️  1 info ](https://app.marker.io/i/62a6ab71af476bee706b06e9_2c31bcdbd2ff916b?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1859 x 972</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Please provide image

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62a6ab71af476bee706b06e9_2c31bcdbd2ff916b) - This issue was marked as resolved in Marker.io.
