### ISSUE TITLE
Jewellery backend

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#68]
[![Screenshot_2022-06-17_02-14-22.png](https://mrkr.io/s/62abe37e37eef797533861fd/2)](https://mrkr.io/s/62abe37e37eef797533861fd/0)

Sorting by product type is not actually sorted by ABC

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62abe37e37eef79753386200_1cb204701173f2b0?comments=1)

**Source URL:** [https://zcova-uat.com/admin/jewellery/listing](https://zcova-uat.com/admin/jewellery/listing)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62abe37e37eef79753386200_1cb204701173f2b0)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1291 x 686</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62abe37e37eef79753386200_1cb204701173f2b0) - This issue was marked as resolved in Marker.io.
