### ISSUE TITLE
Homepage Speak to a zcova curator

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#70]
[![Screenshot_2022-06-20_07-13-15.png](https://mrkr.io/s/62b01e0bbfea10500c49a1d8/2)](https://mrkr.io/s/62b01e0bbfea10500c49a1d8/0)

- Contact button change to this link for now

Contact button: https://zcova.com/contact

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b01e0bbfea10500c49a1db_720b206fa16349cd?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b01e0bbfea10500c49a1db_720b206fa16349cd)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2290 x 1222</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b01e0bbfea10500c49a1db_720b206fa16349cd) - This issue was marked as resolved in Marker.io.
