### ISSUE TITLE
Gemstone page Gemstone education

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#71]
[![Screenshot_2022-06-20_07-42-01.png](https://mrkr.io/s/62b024c9e1e5033aed87fc7f/2)](https://mrkr.io/s/62b024c9e1e5033aed87fc7f/0)

- change the body & links

Body: Birthstone by Month
Link to:  https://blog.zcova.com/2021/07/30/birthstones-month/ 

Body: Greenland Ruby
Link to: https://blog.zcova.com/2021/08/09/greenland-ruby/ 

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b024c9e1e5033aed87fc82_09fd8d36b06415c3?comments=1)

**Source URL:** [https://zcova-uat.com/gemstone-landing](https://zcova-uat.com/gemstone-landing)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b024c9e1e5033aed87fc82_09fd8d36b06415c3)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2290 x 1222</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b024c9e1e5033aed87fc82_09fd8d36b06415c3) - This issue was marked as resolved in Marker.io.
