### ISSUE TITLE
Fine Jewellery landing Shop by category

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#72]
[![Screenshot_2022-06-20_07-52-00.png](https://mrkr.io/s/62b027203cd9f43339ca5f70/2)](https://mrkr.io/s/62b027203cd9f43339ca5f70/0)

- Change photos and links

Body: Rings
Image: https://drive.google.com/open?id=1mOMnW3ZTIF-x7An3IuP2CqHPpQKAEwfH&authuser=eewern%40zcova.com&usp=drive_fs
Link to: https://zcova.com/wedding-ring

Body: Earrings
Image: https://drive.google.com/open?id=1mOGOI5qHLGLmGjRHWG8aMCX4VGbowECE&authuser=eewern%40zcova.com&usp=drive_fs
Link to: https://zcova.com/earrings

Body: Necklace
Image: https://drive.google.com/open?id=1mOB0XwhmUlx-nwkOxiV1Cly1y6nnWylZ&authuser=eewern%40zcova.com&usp=drive_fs
Link to:  https://zcova.com/necklaces

Body: Bracelet
Image: https://drive.google.com/open?id=1mTa1UgVUeTO9F4e-j8vM9djVfFafImcM&authuser=eewern%40zcova.com&usp=drive_fs
Link to: https://zcova.com/bracelets

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b027203cd9f43339ca5f73_f094ed533ff68551?comments=1)

**Source URL:** [https://zcova-uat.com/fine-jewellery](https://zcova-uat.com/fine-jewellery)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b027203cd9f43339ca5f73_f094ed533ff68551)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2290 x 1222</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b027203cd9f43339ca5f73_f094ed533ff68551) - This issue was marked as resolved in Marker.io.
