### ISSUE TITLE
Fine Jewellery landing Make it personal

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#73]
[![Screenshot_2022-06-20_07-59-20.png](https://mrkr.io/s/62b028d837eef797533f727f/2)](https://mrkr.io/s/62b028d837eef797533f727f/0)

- Change button text and link for now

Button: Contact us
Link to: https://zcova.com/contact

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b028d837eef797533f7282_9fc05acf3c79a89f?comments=1)

**Source URL:** [https://zcova-uat.com/fine-jewellery](https://zcova-uat.com/fine-jewellery)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b028d837eef797533f7282_9fc05acf3c79a89f)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2290 x 1222</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b028d837eef797533f7282_9fc05acf3c79a89f) - This issue was marked as resolved in Marker.io.
