### ISSUE TITLE
Fine Jewellery landing Find your inspiration

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#74]
[![Screenshot_2022-06-20_08-02-41.png](https://mrkr.io/s/62b029a13cd9f43339ca67bd/2)](https://mrkr.io/s/62b029a13cd9f43339ca67bd/0)

- change button and link

Button: Contact Us
Link to: https://zcova.com/contact

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b029a13cd9f43339ca67c0_df745cfcd94236f9?comments=1)

**Source URL:** [https://zcova-uat.com/fine-jewellery](https://zcova-uat.com/fine-jewellery)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b029a13cd9f43339ca67c0_df745cfcd94236f9)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2290 x 1222</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b029a13cd9f43339ca67c0_df745cfcd94236f9) - This issue was marked as resolved in Marker.io.
