### ISSUE TITLE
Gemstone landing ICL certificate

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#75]
[![Screenshot_2022-06-20_08-08-40.png](https://mrkr.io/s/62b02b08bfea10500c49caae/2)](https://mrkr.io/s/62b02b08bfea10500c49caae/0)

- change button and link

Button: Find Our More
Link to: https://blog.zcova.com/2020/12/24/icl-cert/

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b02b08bfea10500c49cab1_9cd918e9cae00c5e?comments=1)

**Source URL:** [https://zcova-uat.com/gemstone-landing](https://zcova-uat.com/gemstone-landing)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b02b08bfea10500c49cab1_9cd918e9cae00c5e)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2290 x 1222</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b02b08bfea10500c49cab1_9cd918e9cae00c5e) - This issue was marked as resolved in Marker.io.
