### ISSUE TITLE
Wedding page landing body

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#76]
[![Screenshot_2022-06-20_08-23-34.png](https://mrkr.io/s/62b02e86df693ccce7e9795d/2)](https://mrkr.io/s/62b02e86df693ccce7e9795d/0)

- change the body text

Tie the knot with ZCOVA made-to-order wedding bands. Couple wedding rings are known as the symbol of eternal love. You can create your own custom made wedding band sets in 18k Rose Gold, White Gold or Yellow Gold. If you’re looking for a unique marriage ring, we offer customised wedding bands with free designing.

Ranging from Men’s wedding bands to women’s wedding bands, ZCOVA’s wedding rings are made to mix & match. You can shop for any wedding ring of your choice online. Some of our popular rings are eternity rings, diamond infinity bands, plain minimalist wedding bands, diamond wedding rings, men’s platinum rings and other custom wedding bands.

Don’t wait, buy wedding bands online in Malaysia at ZCOVA today!

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b02e86df693ccce7e97960_e5a81812b334d3d9?comments=1)

**Source URL:** [https://zcova-uat.com/wedding-rings](https://zcova-uat.com/wedding-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b02e86df693ccce7e97960_e5a81812b334d3d9)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1527 x 815</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b02e86df693ccce7e97960_e5a81812b334d3d9) - This issue was marked as resolved in Marker.io.
