### ISSUE TITLE
Gemstone landing 

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#77]
[![Screenshot_2022-06-20_08-25-13.png](https://mrkr.io/s/62b02ee9e1e5033aed881e30/2)](https://mrkr.io/s/62b02ee9e1e5033aed881e30/0)

- change the body text

Design your dream gemstone by choosing your ideal colour, shape and grade from Asia’s biggest virtual gemstone inventory!
Quality gemstones with certificates. Free customisation into gemstone rings, gemstone necklaces, gemstone bracelets, gemstone
earrings or any gemstone jewelry.

Shop for loose ruby gemstones, green tourmaline, pink sapphire, pink tourmaline, emerald gemstones, green sapphires gemstones, alexandrite stones, spinel stones, tsavorite and more. Popular gemstone jewellery include blue sapphire rings, emerald rings, sapphire rings, yellow sapphire rings, pink sapphire rings, sapphire necklace, emerald pendant, and birthstone necklaces.

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b02ee9e1e5033aed881e33_48e7fd4712c8282d?comments=1)

**Source URL:** [https://zcova-uat.com/gemstones?start=gemstone](https://zcova-uat.com/gemstones?start=gemstone)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b02ee9e1e5033aed881e33_48e7fd4712c8282d)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1527 x 815</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b02ee9e1e5033aed881e33_48e7fd4712c8282d) - This issue was marked as resolved in Marker.io.
