### ISSUE TITLE
Footer lSocial

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#78]
[![Screenshot_2022-06-20_08-35-56.png](https://mrkr.io/s/62b0316cbfea10500c49e059/2)](https://mrkr.io/s/62b0316cbfea10500c49e059/0)

Homepage Footer
- Add graded by, we accept, instalment options
- Add logos

Graded By
GIA logo: https://drive.google.com/open?id=1zEeDjTSEhU7pF_LlDbNrPPZY8E9qrJI-&authuser=eewern%40zcova.com&usp=drive_fs
GemEx logo: https://drive.google.com/open?id=1zDz1jEspvKqQo9bImIfvAc29JMxmAa8Y&authuser=eewern%40zcova.com&usp=drive_fs
IGI logo: https://drive.google.com/open?id=1zEi6DCtzI7eLgkDgaGGqDpCCSmAuI8VX&authuser=eewern%40zcova.com&usp=drive_fs
ICL logo: https://drive.google.com/open?id=1zCfIi0A5zIEk0L8mkuY7lMZB1IQnOx17&authuser=eewern%40zcova.com&usp=drive_fs

We Accept
- Visa logo: https://drive.google.com/file/d/1xvNF3dm0KquqsYBxVmzGuHdB418clXDm/view?usp=sharing
- Master card logo:
https://drive.google.com/file/d/1xv8Q0e5TM9HA-wknguFomRkml9QfQGzP/view?usp=sharing
- ipay88 logo:
https://drive.google.com/file/d/1xvS130pFxNTYpnUzUdRn6it_o3XnA6DK/view?usp=sharing

Instalment Options
- Maybank logo:
https://drive.google.com/file/d/1xuaMoVxc3Qx72Yi5J7j1CFSV_O9izFbd/view?usp=sharing
- CIMB bank logo:
https://drive.google.com/file/d/1xuI7_AKVgqtcR4Cd63BawuUQdJ_9jkPy/view?usp=sharing
- Public Bank
https://drive.google.com/file/d/1xuEih9XK47ntvNTcdqgKs0WO97o7c6Xu/view?usp=sharing

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b0316cbfea10500c49e05c_32d21a593372c51a?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b0316cbfea10500c49e05c_32d21a593372c51a)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2290 x 1222</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b0316cbfea10500c49e05c_32d21a593372c51a) - This issue was marked as resolved in Marker.io.
