### ISSUE TITLE
Wedding Ring landing

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#79]
[![Screenshot_2022-06-20_08-49-22.png](https://mrkr.io/s/62b03492c3d4394788e2af3a/2)](https://mrkr.io/s/62b03492c3d4394788e2af3a/0)

- Remove these three button TEMPORARY for now

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b03492c3d4394788e2af3d_b5e6cafe36cffed6?comments=1)

**Source URL:** [https://zcova-uat.com/wedding-rings](https://zcova-uat.com/wedding-rings)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b03492c3d4394788e2af3d_b5e6cafe36cffed6)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1717 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b03492c3d4394788e2af3d_b5e6cafe36cffed6) - This issue was marked as resolved in Marker.io.
