### ISSUE TITLE
clicking at clarity will also open cut

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#8]
[![Screenshot_2022-06-01_12-41-11.png](https://mrkr.io/s/62975e67a7e44a763e052e78/2)](https://mrkr.io/s/62975e67a7e44a763e052e78/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/diamonds/selected-diamond/7438553648?start=diamond](https://zcova-uat.com/diamonds/selected-diamond/7438553648?start=diamond)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62975e67a7e44a763e052e81_1c70b34a5ba65d00)

**Console:** [ℹ️  2 info 📃  2 logs ](https://app.marker.io/i/62975e67a7e44a763e052e81_1c70b34a5ba65d00?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1144</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62975e67a7e44a763e052e81_1c70b34a5ba65d00) - This issue was marked as resolved in Marker.io.
