### ISSUE TITLE
Fine Jewellery landing, earring page

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#80]
[![Screenshot_2022-06-20_09-14-50.png](https://mrkr.io/s/62b03a8a47082cd8354a4391/2)](https://mrkr.io/s/62b03a8a47082cd8354a4391/0)

- hide description for now

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b03a8a47082cd8354a4394_51760a61c26297f6?comments=1)

**Source URL:** [https://zcova-uat.com/earrings?style=Stud](https://zcova-uat.com/earrings?style=Stud)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b03a8a47082cd8354a4394_51760a61c26297f6)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1717 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b03a8a47082cd8354a4394_51760a61c26297f6) - This issue was marked as resolved in Marker.io.
