### ISSUE TITLE
Fine Jewellery landing, Necklace

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#81]
[![Screenshot_2022-06-20_09-16-32.png](https://mrkr.io/s/62b03af0c3d4394788e2c429/2)](https://mrkr.io/s/62b03af0c3d4394788e2c429/0)

- change description

Go with a classic single pendant diamond necklace for every occasion or you can also go bold by embracing the harmony of diamonds altogether to make a diamond eternity necklace or diamond tennis necklace. Either way, ZCOVA has it all for you. From 18k yellow gold necklace, 18k white gold necklace, 18k rose gold necklace to customised necklace with name.

Browse diamond gold chain necklace for men, diamond gold necklace for women, gold pendant, diamond pendant, custom design necklaces, ruby necklace, sapphire necklace, emerald necklace, birthstone necklace, gemstone necklace and more. 

Talk to our gemologist to know more about diamonds and gemstones. Get free customized design with experienced in-house jewellery designers.

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b03af0c3d4394788e2c42c_3248e887c953a5ad?comments=1)

**Source URL:** [https://zcova-uat.com/necklaces?style=Pendant+Necklace](https://zcova-uat.com/necklaces?style=Pendant+Necklace)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b03af0c3d4394788e2c42c_3248e887c953a5ad)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1717 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b03af0c3d4394788e2c42c_3248e887c953a5ad) - This issue was marked as resolved in Marker.io.
