### ISSUE TITLE
Fine Jewellery landing, Earring

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#82]
[![Screenshot_2022-06-20_09-18-07.png](https://mrkr.io/s/62b03b4fba944a36d7eca978/2)](https://mrkr.io/s/62b03b4fba944a36d7eca978/0)

- change the description

Extensive design range of beautiful & delicate gold earrings and diamond earrings. Browse from diamond studs, diamond drop earrings, diamond hoop earrings, diamond stud earrings, pearl earrings, dangle diamond earrings to red ruby earrings, blue sapphire earrings, green emerald earrings, gemstone earrings, latest earring designs and more!

No matter if you’re looking for earrings for men or earrings for women, ZCOVA provides for all gender and age. Shop your earrings in 18k yellow gold, 18k rose gold, or 18k white gold. If you’re looking for a one-of-a-kind jewellery piece, get Free Customization service with ZCOVA’s in-house jewellery designer. 

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b03b4fba944a36d7eca97b_6b745acd3ca8b690?comments=1)

**Source URL:** [https://zcova-uat.com/earrings?style=Stud](https://zcova-uat.com/earrings?style=Stud)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b03b4fba944a36d7eca97b_6b745acd3ca8b690)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1717 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b03b4fba944a36d7eca97b_6b745acd3ca8b690) - This issue was marked as resolved in Marker.io.
