### ISSUE TITLE
Fine Jewellery landing, Bracelets

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#83]
[![Screenshot_2022-06-20_09-19-32.png](https://mrkr.io/s/62b03ba4c0839fbb77805352/2)](https://mrkr.io/s/62b03ba4c0839fbb77805352/0)

- change description

If you’re looking for a gold bracelet for men or a gold bracelet for women, look no further. Browse through an array of ZCOVA’s classic and timeless bracelets where each scintillating piece incorporates exceptionally rare diamonds & gemstones.

Explore these bracelets in many styles and type of gold, including delicate diamond chain bracelets, tennis bracelets, 18k yellow gold bracelets, 18k white gold bracelets, 18k rose gold bracelets, gold charm bracelets, tourmaline bracelets, amethyst bracelets, ruby bracelets, blue sapphire bracelets, emerald bracelets, gemstone bracelets, aquamarine bracelets, and more. 

Customize your unique bracelet design for free with our experienced in-house jewellery designer.

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b03ba4c0839fbb77805355_44537375e5995da6?comments=1)

**Source URL:** [https://zcova-uat.com/bracelets?style=Tennis+Bracelet](https://zcova-uat.com/bracelets?style=Tennis+Bracelet)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b03ba4c0839fbb77805355_44537375e5995da6)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1717 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b03ba4c0839fbb77805355_44537375e5995da6) - This issue was marked as resolved in Marker.io.
