### ISSUE TITLE
Homepage landing Customise any design for your price range

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#84]
[![Screenshot_2022-06-21_02-44-44.png](https://mrkr.io/s/62b1309c37eef79753429a23/2)](https://mrkr.io/s/62b1309c37eef79753429a23/0)

- change the layout
- Add a solid colour with title & description on the left and a png video on the right
- Solid colour background: #fcf9f7 ; 6126px (W) x 3209px (H)

On the left:-
Title (font size H2): Customise Any Design For Your Price Range
Description (font 18): With endless options for customisation, create an amazing piece that captures your love story perfectly!

Click on a button below to start (font 18)
Button: Diamond, Gemstone, Setting (with the same link)

On the right (png video):-
Video: https://drive.google.com/open?id=1zAL28026DE4msl4eagXDpq1YcNxY6ZEx&authuser=eewern%40zcova.com&usp=drive_fs

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b1309c37eef79753429a26_2f169bfa1934b2ec?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b1309c37eef79753429a26_2f169bfa1934b2ec)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2316 x 1222</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b1309c37eef79753429a26_2f169bfa1934b2ec) - This issue was marked as resolved in Marker.io.
