### ISSUE TITLE
Birthstone

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#85]
[![Screenshot_2022-06-21_07-08-28.png](https://mrkr.io/s/62b16e6cba944a36d7f00a55/2)](https://mrkr.io/s/62b16e6cba944a36d7f00a55/0)

Remove lorem ipsum description temporarily

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b16e6cba944a36d7f00a58_0a2962e58a1ba472?comments=1)

**Source URL:** [https://zcova-uat.com/birthstones](https://zcova-uat.com/birthstones)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b16e6cba944a36d7f00a58_0a2962e58a1ba472)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1230 x 722</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b16e6cba944a36d7f00a58_0a2962e58a1ba472) - This issue was marked as resolved in Marker.io.
