### ISSUE TITLE
Fine jewellery landing Shop by style

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#86]
[![Screenshot_2022-06-21_07-56-37.png](https://mrkr.io/s/62b179b5bd1c844823163cd2/2)](https://mrkr.io/s/62b179b5bd1c844823163cd2/0)

- change image & body
- add link

Body: Stud Earrings
Image: https://drive.google.com/open?id=1mSItcxUbvj6nh8Kv84slbDfju9EP6Tjs&authuser=eewern%40zcova.com&usp=drive_fs
Link to: https://zcova-uat.com/earrings?style=Stud

Body: Personalised 
Image: https://drive.google.com/open?id=1mS64IC_TZ3niT_Cjsr-a8-5520b96zm6&authuser=eewern%40zcova.com&usp=drive_fs
Link to: https://zcova-uat.com/personalised (filter all personalised ring, earring, bracelet, necklace)

Body: Gemstone Necklace
Image: https://drive.google.com/open?id=1mRx03KVOR5sFZX4lZRDyWeEfMaz7jAYv&authuser=eewern%40zcova.com&usp=drive_fs
Link to: https://zcova-uat.com/necklaces?style=Gemstone+Necklaces

Body: Tennis Bracelet
Image: https://drive.google.com/open?id=1mRmH3Y_pyMhCDHBvfoUyrzXE7K7E-V6O&authuser=eewern%40zcova.com&usp=drive_fs
Link to: https://zcova-uat.com/bracelets?style=Tennis+Bracelet

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b179b5bd1c844823163cd5_6343797710fc06d9?comments=1)

**Source URL:** [https://zcova-uat.com/fine-jewellery](https://zcova-uat.com/fine-jewellery)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b179b5bd1c844823163cd5_6343797710fc06d9)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1737 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b179b5bd1c844823163cd5_6343797710fc06d9) - This issue was marked as resolved in Marker.io.
