### ISSUE TITLE
Fine jewellery Find your inspiration

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#87]
[![Screenshot_2022-06-21_07-59-31.png](https://mrkr.io/s/62b17a62c0839fbb7783ccbc/2)](https://mrkr.io/s/62b17a62c0839fbb7783ccbc/0)

- change link to https://www.pinterest.com/zcovajewel/

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b17a62c0839fbb7783ccbf_c33b81f4a60e2e9c?comments=1)

**Source URL:** [https://zcova-uat.com/fine-jewellery](https://zcova-uat.com/fine-jewellery)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b17a62c0839fbb7783ccbf_c33b81f4a60e2e9c)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1737 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b17a62c0839fbb7783ccbf_c33b81f4a60e2e9c) - This issue was marked as resolved in Marker.io.
