### ISSUE TITLE
Lab grown landing

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#88]
[![Screenshot_2022-06-21_08-11-47.png](https://mrkr.io/s/62b17d43bd1c84482316464f/2)](https://mrkr.io/s/62b17d43bd1c84482316464f/0)

- remove this whole thing temporarily. Will need to change the text

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b17d43bd1c844823164652_dd41c7150896e48d?comments=1)

**Source URL:** [https://zcova-uat.com/diamonds?start=diamond&lab=yes](https://zcova-uat.com/diamonds?start=diamond&lab=yes)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b17d43bd1c844823164652_dd41c7150896e48d)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1737 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b17d43bd1c844823164652_dd41c7150896e48d) - This issue was marked as resolved in Marker.io.
