### ISSUE TITLE
diamond images jumble up with others not related image

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#9]
[![Screenshot_2022-06-01_12-43-06.png](https://mrkr.io/s/62975edaf027f7dffe8a8347/2)](https://mrkr.io/s/62975edaf027f7dffe8a8347/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Affendy Iskandar (fendy@fendy.org)

**Source URL:** [https://zcova-uat.com/diamonds?start=diamond](https://zcova-uat.com/diamonds?start=diamond)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62975edaf027f7dffe8a834e_7afe8c3897bce6cd)

**Console:** [ℹ️  2 info 📃  2 logs ](https://app.marker.io/i/62975edaf027f7dffe8a834e_7afe8c3897bce6cd?console=1)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 2560</td></tr><tr><td><strong>OS</strong></td><td>OS X 11.6.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>1414 x 1144</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62975edaf027f7dffe8a834e_7afe8c3897bce6cd) - This issue was marked as resolved in Marker.io.
