### ISSUE TITLE
Fine Jewellery landing jewellery thats uniquely

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#90]
[![Screenshot_2022-06-21_09-19-07.png](https://mrkr.io/s/62b18d0bbd1c84482316744e/2)](https://mrkr.io/s/62b18d0bbd1c84482316744e/0)

- Change button to "Contact Us"
- Link to: https://zcova-uat.com/contact

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b18d0bbd1c844823167451_4a4909af790548c8?comments=1)

**Source URL:** [https://zcova-uat.com/fine-jewellery](https://zcova-uat.com/fine-jewellery)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b18d0bbd1c844823167451_4a4909af790548c8)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1737 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b18d0bbd1c844823167451_4a4909af790548c8) - This issue was marked as resolved in Marker.io.
