### ISSUE TITLE
Fine jewellery landing blog

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#91]
[![Screenshot_2022-06-21_09-24-25.png](https://mrkr.io/s/62b18e49df693ccce7ed5792/2)](https://mrkr.io/s/62b18e49df693ccce7ed5792/0)

- change the "Personalised Jewellery" link

Link to: https://blog.zcova.com/2022/04/04/personalised-name-jewellery/

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b18e49df693ccce7ed5795_b2eb407804a2b837?comments=1)

**Source URL:** [https://zcova-uat.com/fine-jewellery](https://zcova-uat.com/fine-jewellery)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b18e49df693ccce7ed5795_b2eb407804a2b837)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1737 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b18e49df693ccce7ed5795_b2eb407804a2b837) - This issue was marked as resolved in Marker.io.
