### ISSUE TITLE
Homepage Review

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#94]
[![Screenshot_2022-06-22_02-09-00.png](https://mrkr.io/s/62b279bc83c72308b1a35302/2)](https://mrkr.io/s/62b279bc83c72308b1a35302/0)

- change image to https://drive.google.com/open?id=1SG-Rs6kVxH1wLbnG2FRiwPLNilvmZB57&authuser=eewern%40zcova.com&usp=drive_fs

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b279bc83c72308b1a35305_306472d05d485f03?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b279bc83c72308b1a35305_306472d05d485f03)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1756 x 916</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b279bc83c72308b1a35305_306472d05d485f03) - This issue was marked as resolved in Marker.io.
