### ISSUE TITLE
Diamond Landing Design own engagement ring

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#95]
[![Screenshot_2022-06-22_02-14-13.png](https://mrkr.io/s/62b27af5bd1c844823194afd/2)](https://mrkr.io/s/62b27af5bd1c844823194afd/0)

- change the image to https://drive.google.com/open?id=1mbZxvIXEJn7HYa6CXAE9BKuftFgtbuEg&authuser=eewern%40zcova.com&usp=drive_fs

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b27af5bd1c844823194b00_5b5f4f032dec24d5?comments=1)

**Source URL:** [https://zcova-uat.com/diamond-landing](https://zcova-uat.com/diamond-landing)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b27af5bd1c844823194b00_5b5f4f032dec24d5)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1639 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b27af5bd1c844823194b00_5b5f4f032dec24d5) - This issue was marked as resolved in Marker.io.
