### ISSUE TITLE
Diamond landing page shop by jewellery

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#96]
[![Screenshot_2022-06-22_02-16-11.png](https://mrkr.io/s/62b27b6bef721b797126ec8c/2)](https://mrkr.io/s/62b27b6bef721b797126ec8c/0)

Links are wrong
Ring > /engagement-rings

Necklace > /necklaces?style=Diamond+Necklace

Bracelet > /bracelets?style=Diamond+Bracelet

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b27b6bef721b797126ec8f_b772072d98553831?comments=1)

**Source URL:** [https://zcova-uat.com/diamond-landing](https://zcova-uat.com/diamond-landing)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b27b6bef721b797126ec8f_b772072d98553831)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1269 x 722</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b27b6bef721b797126ec8f_b772072d98553831) - This issue was marked as resolved in Marker.io.
