### ISSUE TITLE
Homepage Dropdown Honesty & expertise...

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#97]
[![Screenshot_2022-06-22_02-37-45.png](https://mrkr.io/s/62b28079c0839fbb7786ed38/2)](https://mrkr.io/s/62b28079c0839fbb7786ed38/0)

- remove the photo shadow & change all the image for each dropdown

Honesty & Expertise Image change to:
https://drive.google.com/open?id=1xqCuIuH1om3O9r65jonk_3yYcGUlZaF-&authuser=eewern%40zcova.com&usp=drive_fs

ZCOVA Journey image change to:
https://drive.google.com/open?id=1xq96-FEVDL3guVyz81SxFnoOguXCoiHB&authuser=eewern%40zcova.com&usp=drive_fs

Master Craftsmanship image change to:
https://drive.google.com/open?id=1xplMdSWCvPWVPxe_3NMBpsEka1WGK6I7&authuser=eewern%40zcova.com&usp=drive_fs

Lifetime Warranty image change to:
https://drive.google.com/open?id=1xqrkCzcXYPklcnUmwEdXjoxWrYISH-NN&authuser=eewern%40zcova.com&usp=drive_fs

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b28079c0839fbb7786ed3b_476bbef51182c8ff?comments=1)

**Source URL:** [https://zcova-uat.com/](https://zcova-uat.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b28079c0839fbb7786ed3b_476bbef51182c8ff)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1651 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b28079c0839fbb7786ed3b_476bbef51182c8ff) - This issue was marked as resolved in Marker.io.
