### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#98]
[![Screenshot_2022-06-22_07-30-23.png](https://mrkr.io/s/62b2c50f47082cd835516c40/2)](https://mrkr.io/s/62b2c50f47082cd835516c40/0)

- change banner image and title

Banner Image: 
https://drive.google.com/open?id=1zGxMGJasuXpJmpqSw9hZDyeA7UhLqq7t&authuser=eewern%40zcova.com&usp=drive_fs

Text on Image: Create Happiness with Brilliant Jewellery

--------
Pls refer this image to understand better:
https://drive.google.com/open?id=17Mk-WE0MM4qHq_eAlKhPLQPHMq7rckNK&authuser=eewern%40zcova.com&usp=drive_fs

---

**Reported by:** Ee Wern (eewern@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62b2c50f47082cd835516c43_3c457e3bc29de72d?comments=1)

**Source URL:** [https://zcova-uat.com/about](https://zcova-uat.com/about)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62b2c50f47082cd835516c43_3c457e3bc29de72d)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1560 x 915</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.3333333730697632x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62b2c50f47082cd835516c43_3c457e3bc29de72d) - This issue was marked as resolved in Marker.io.
